### ISSUE TITLE
Error message on registration

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#10]
![screenshot_21](https://cloud.githubusercontent.com/assets/25616317/22700267/b970008e-ed62-11e6-8258-ae9ec32efe14.png)

I get this message when trying to register on localhost, ive setup the recaptcha and all that

**Comment by sant0ro** [comment]
Please download latest binaries (uploaded has few minutes ago).

Also please check if your age is bigger than 13year old.

**Comment by resrvoir** [comment]
@sant0ro the problem still exists... here is my register credentials
![screenshot_22](https://cloud.githubusercontent.com/assets/25616317/22704919/206e6f14-ed72-11e6-9366-4eb1e2a0ef42.png)

**Comment by sant0ro** [comment]
Downloaded latest binaries? That really doesn't make any sense.

**Comment by resrvoir** [comment]
https://github.com/sant0ro/chocolatey/releases/tag/1.850
if its this one then yes

**Comment by resrvoir** [comment]
still cant register after updating to 1.901 (same error)

**Comment by sant0ro** [comment]
This error doesn't happens with me @resrvoir ...

**Comment by sant0ro** [comment]
I can't replicate your error.

**Comment by resrvoir** [comment]
I noticed that the migrations didnt complete and got them right but still the same error

**Comment by sant0ro** [comment]
@resrvoir i really don't know why this is happening.. You're using original Arcturus Database?

This error just doesn't happens with me :/ and with the other users

**Comment by resrvoir** [comment]
@sant0ro arcturus-1.3.0.sql that comes with Arcturus 1.3.0

**Comment by sant0ro** [comment]
That's really weird. Can you show the console in Network Tab if the Request "api/register/new" (something like that) return a 500 Internal Server Error?

Remember that if you already used the e-mail, error will be given.

**Comment by resrvoir** [comment]
@sant0ro yeah I get 500 on api/public/register/new
heres the laravel error http://pastebin.com/0ZSxWEEr

**Comment by sant0ro** [comment]
Oh shet. Will try fix it now.

**Comment by resrvoir** [comment]
@sant0ro just noticed that I only get the error from "api/public/register/new" while on incognito and on non-incognito nothing shows up in the console or network tab

**Comment by sant0ro** [comment]
I'm uploading fixed binaries. Wait a minute

**Comment by sant0ro** [comment]
Try again please.

**Comment by resrvoir** [comment]
@sant0ro works on incognito but non-incognito still the ToS message, Im looking if its something with my Chrome

**Comment by sant0ro** [comment]
Okay! Maybe a Plugin. But i'm glad to hear that started to working for you ;O

**Comment by resrvoir** [comment]
Had to clear my "chrome account"

**Comment by sant0ro** [comment]
Nice that you fixed it. I wish a great experience with Chocolatey.
