### ISSUE TITLE
Register does not work

### ISSUE THREAD

**Issue by TheTelephon** [sant0ro/chocolatey#103]
.The registration site where you change your clothes and selecting a room no longer works
Page remains black
See image: http://imgur.com/LUf8QJy

**Comment by s150217754** [comment]
@TheTelephon Unable to replicate this. Able to register, go through NUX figure, name + room selection and login via the client.

**Comment by sant0ro** [comment]
I'm not able to replicate this.

I think you didn't configued your SWF links correctly.

Closing.
