### ISSUE TITLE
Mail Issue

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#104]
Hi,

Despite configuring properly the **config/mail.php** file and enabling the mail option in there, Chocolatey can't seem to send out email automatically. However, there is a green pop-up showing that the mail has been successfully sent.

Also, unlike before, Chocolatey DOES NOT create a row in chocolatey_users_mail_requests table.

No lumen or Chrome Console log generated.

**Comment by s150217754** [comment]
^ Trying to send out Verification Email via "Settings > Email"

Also tried creating a new account - which automatically sents out a verification. However, it DOES create a row in chocolatey_users_mail_requests table.

**Comment by sant0ro** [comment]
Okay! Will check it out.

**Comment by sant0ro** [comment]
Will Fix It on next Release.

**Comment by sant0ro** [comment]
Fixed. Next Release will have it.
