### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by ialert** [sant0ro/chocolatey#109]
I get registration error that users table doesn't exist.Is it missing in migrations or why?Please,check it.

[lumen.txt](https://github.com/sant0ro/chocolatey/files/878709/lumen.txt)

**Comment by s150217754** [comment]
The logs shows that you're missing the default Arcturus SQL. 

Please execute Arcturus Emulator SQL and then use Chocolatey Migration command.

**Comment by s150217754** [comment]
Closing this issue as it is invalid. 

If you need assistance, feel free to respond to this ticket.
