### ISSUE TITLE
Issues with reCaptcha

### ISSUE THREAD

**Issue by KugaTog** [sant0ro/chocolatey#112]
Hello,
I was working on setting up the CMS and I ran into this issue,
I was working with S150217754 and I figured i'd make a post since it has been unsolved so far.

http://imgur.com/a/Ee2RO

Troubleshooting attempts:
making a few new ones
Updating Xampp to the latest version
Disabling Mail
Changing .htacsess mispelling of bootstrap
C:\xampp\php\php artisan migrate (Twice)

**Comment by s150217754** [comment]
Thanks for opening a issue. I will try to setup the latest version and replicate the problem you have faced when I get back home.

**Comment by iHxFall** [comment]
I have the same issue...

**Comment by KugaTog** [comment]
any updates?

**Comment by s150217754** [comment]
@KugaTog Please use the latest binaries and let me know if you're experiencing any issues.

https://github.com/sant0ro/chocolatey/releases/tag/2.415

**Comment by KugaTog** [comment]
Nope, Same issue

**Comment by KugaTog** [comment]
This is the latest error:

![image](https://cloud.githubusercontent.com/assets/26791733/24553328/2a85822e-15e7-11e7-9c42-57c8f69dad46.png)

**Comment by s150217754** [comment]
@KugaTog Hi, unfortunately I am unable to replicate your problem.

I have tried creating a account from scratch and have not encountered any issues and was able to:

1. Register a New Account
2. Go through NUX Figure, Name and Room
3. Login

As frustrating as it may sound, your best bet is to re-setup from scratch again:
- Reinstall [XAMPP with PHP7.1.1](https://www.apachefriends.org/xampp-files/7.1.1/xampp-win32-7.1.1-0-VC14-installer.exe)
- Redownload [Chocolatey 2.415](https://github.com/sant0ro/chocolatey/releases/tag/2.415) Binaries and Extract to C:\xampp\htdocs\ (Re(move) all XAMPP default file - please)
- Run Arcturus SQL Database from Scratch
- Run Chocolatey Migration Command on the new Arcturus Database

**Comment by sant0ro** [comment]
I'm waiting to @KugaTog reply on the RZ, where I asked if the Database connection it's really working.

**Comment by KugaTog** [comment]
Same issue still... Here is the new Lumen Log:

[2017-04-01 06:37:47] lumen.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swf_hotel.chocolatey_users_id' doesn't exist in C:\xampp\htdocs\vendor\illuminate\database\Connection.php:319
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(319): PDO->prepare('select count(*)...')
#1 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select count(*)...', Array)
#2 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#3 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(326): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#4 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1718): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#5 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1703): Illuminate\Database\Query\Builder->runSelect()
#6 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(2094): Illuminate\Database\Query\Builder->get(Array)
#7 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(2022): Illuminate\Database\Query\Builder->aggregate('count', Array)
#8 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(1329): Illuminate\Database\Query\Builder->count()
#9 C:\xampp\htdocs\app\Http\Controllers\LoginController.php(78): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#10 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#12 C:\xampp\htdocs\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#14 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#15 C:\xampp\htdocs\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#17 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#19 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#41 C:\xampp\htdocs\index.php(26): Laravel\Lumen\Application->run()
#42 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swf_hotel.chocolatey_users_id' doesn't exist (SQL: select count(*) as aggregate from `chocolatey_users_id` where `mail` = KugaTog@gmail.com) in C:\xampp\htdocs\vendor\illuminate\database\Connection.php:647
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(326): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1718): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1703): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(2094): Illuminate\Database\Query\Builder->get(Array)
#5 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(2022): Illuminate\Database\Query\Builder->aggregate('count', Array)
#6 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(1329): Illuminate\Database\Query\Builder->count()
#7 C:\xampp\htdocs\app\Http\Controllers\LoginController.php(78): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#12 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#13 C:\xampp\htdocs\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#14 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#15 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#17 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#19 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#29 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#39 C:\xampp\htdocs\index.php(26): Laravel\Lumen\Application->run()
#40 {main}

**Comment by KugaTog** [comment]
FIXED, when running C:\xampp\php\php artisan migrate it only did the first three tables, once I deleted those from mitigation folder, it did the remainder.

**Comment by sant0ro** [comment]
I'I'm really glad that you figured it out.
