### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by dominicusdev** [sant0ro/chocolatey#114]
When navigating around, I often run into having a blank page.
No lumen logs or whatsoever, this occurs on almost every page change (I have to clear my browsing history every time..)

**Comment by sant0ro** [comment]
What tha fuck?

This doesn't happens with me.

**Comment by sant0ro** [comment]
@dominicusdev are you still experiencing this?

**Comment by dominicusdev** [comment]
No, I figured that it was me forgetting a ";" on window.session, sorry

**Comment by sant0ro** [comment]
No problem!
