### ISSUE TITLE
client-new-user error

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#115]
Bug after registration. 
Nothing happens when we click on "I'm ready". 

http://i.imgur.com/ONopgAt.png

**Comment by sant0ro** [comment]
Give me the logs of console tab.

@s150217754 can you check this bug?

**Comment by BobyTS** [comment]
[log-1490906606237.txt](https://github.com/sant0ro/chocolatey/files/883766/log-1490906606237.txt)

**Comment by BobyTS** [comment]
If I try to skip this step or refresh page, I have another error :
(Require empty cookies to solve the problem)
[log-1490907213937.txt](https://github.com/sant0ro/chocolatey/files/883787/log-1490907213937.txt)

**Comment by sant0ro** [comment]
Now give me the Network tab logs.

**Comment by BobyTS** [comment]
![1](https://cloud.githubusercontent.com/assets/26801809/24527670/7cd280ac-15a3-11e7-8998-04902c37a046.PNG)
![2](https://cloud.githubusercontent.com/assets/26801809/24527674/7f164934-15a3-11e7-87bb-aed07926ed07.PNG)

**Comment by sant0ro** [comment]
OK, based on the logs, Isn't a Chocolatey problem. But a JavaScript Security Policy thing.

Check your CORS configuration on crossdomain.xml of your SWF, and the CORS rules on config/chocolatey.php

Also ensure that you're requesting in exactly same domain.

The NUX system it's coded inside Habbo.swf, Angular only retrieves the methods from it.

Closing, this Issue. If the solution described aboved doesn't work, please reopen it.

**Comment by BobyTS** [comment]
CORS rules and crossdomain.xml is well configured and CMS/SWF are on the same domain.

I do not understand why nothing happens when I press the button "I'm ready".
I still get  Javascript error that I provided

**Comment by BobyTS** [comment]
> Closing, this Issue. If the solution described aboved doesn't work, please reopen it.
@sant0ro We do not have permissions to reopen closed tickets

**Comment by BobyTS** [comment]
Problem resolved with https:// protocol

**Comment by sant0ro** [comment]
Nice!
