### ISSUE TITLE
Vendor

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#117]
I got this error on console's log:
http://prntscr.com/eqp0t3

**Comment by sant0ro** [comment]
This error happens when tries to like a photo?

**Comment by lStickerz** [comment]
no its when you access the https://url/community/photos the error appear in the console

**Comment by lStickerz** [comment]
Also when you view the photo in https://url/profile/username/photo/id?pool=photos it shows the same error

**Comment by sant0ro** [comment]
Can you send a screenshot of the photos page? Does the photo appears correctly?

What exactly happens? Does you be able to like a photo? Liking a photo and refreshin page does the like continues?

**Comment by lStickerz** [comment]
http://prnt.sc/eqxy7g a pic of the page and the console

**Comment by sant0ro** [comment]
Okay, but are those images loading? I need more detailed logs. Please save a .HAR file from the Network tab.

How to get a HAR file.: https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-

Attach it here.

**Comment by Ninktos** [comment]
This problem was caused by chocolatey_users_photos_likes, i didn't cleared the table correctly.

**Comment by sant0ro** [comment]
Okay!
