### ISSUE TITLE
Photos not loading

### ISSUE THREAD

**Issue by dominicusdev** [sant0ro/chocolatey#118]
Photos not loading?
Link loaded like:
http://****/profile/Dominic/photo/https:://arcturus.wf/camera/*****/1_1491030136.png

**Comment by dominicusdev** [comment]
Since Habbo's scripts adds "https:", your str_replace is wrong
`return str_replace('http:', '', str_replace('https:', '', $this->attributes['url']));`
Should work, at least does for me.

**Comment by sant0ro** [comment]
If you want, you can create a Pull Request for that.

I'll be glad if you do.
