### ISSUE TITLE
ADS

### ISSUE THREAD

**Issue by lStickerz** [sant0ro/chocolatey#122]
Can you please help me code the ads in the cms....

**Comment by BobyTS** [comment]
I can help you, but know ADS is conceived to work with DoubleClick for Publisher, not Adsense

**Comment by sant0ro** [comment]
Exactly like @BobyTS, I'm not sure if the whole CMS Ads are for DoubleClick or for Adsene, but I remember that one of the Ads systems only uses DoubleClick, I think that isn't the Client Ads but the CMS Ads.

Anyways, If you want to Inject the Original Ads Templates on your CMS...
It would require the following steps.:

Open your `public/habbo-web/scripts.js`

Replace
<pre>
angular.module("playing.habbo", ["header", "locale", "router", "tabs", "templates", "web.pages"])
</pre>
BY
<pre>
angular.module("playing.habbo", ["ad.unit", "header", "locale", "router", "tabs", "templates", "web.pages"])
</pre>

Replace
<pre>
angular.module("header.ad", ["templates"])
</pre>
BY
<pre>
angular.module("header.ad", ["ad.unit", "templates"])
</pre>

Replace
<pre>
angular.module("news", ["compile", "locale", "moderation.notification", "promos.service", "router", "templates", "web.pages"])
</pre>
BY
<pre>
angular.module("news", ["ad.unit", "compile", "locale", "moderation.notification", "promos.service", "router", "templates", "web.pages"])
</pre>

Replace
<pre>
angular.module("fansites", ["locale", "router", "templates", "web.pages"])
</pre>
BY
<pre>
angular.module("fansites", ["ad.unit", "locale", "router", "templates", "web.pages"])
</pre>

Replace
<pre>
angular.module("category", ["category.service", "compile", "locale", "router", "templates", "web.pages"])
<pre>
BY
<pre>
angular.module("category", ["ad.unit", "category.service", "compile", "locale", "router", "templates", "web.pages"])
</pre>

Replace
<pre>
angular.module("category", ["category.service", "compile", "locale", "router", "templates", "web.pages"])
</pre>
BY
<pre>
angular.module("article", ["ad.unit", "article.service", "compile", "lightbox", "locale", "router", "social.share", "templates", "web.pages"])
</pre>

**I need to warn you that in the moment that you add those modifications on your CMS, I will not longer be responsible of any bugs/problems/dmca's/etc** that may/would/can happen with you.

Good luck. Support for Ads will not be given if any bug appears.

**Comment by lStickerz** [comment]
after i do all of that how do i add the adsense code?
