### ISSUE TITLE
Predefined random nicknames

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#125]
Can you add a similar function to this library? It would be better to have random nicknames more aesthetic like Habbo. We can also configure it to choose predefined funny words like "Mister-$partialMail-Duck"

Exemple : https://github.com/nubs/random-name-generator

**Comment by sant0ro** [comment]
Okay! Would adding it soon as possible. Loved this library.

**Comment by sant0ro** [comment]
Okay! Doing it exactly as how you said.

Coded.
Commiting.

**Comment by BobyTS** [comment]
Thank you very much, happy to participate in this project :)

**Comment by sant0ro** [comment]
No problem, @BobyTS. Any suggestion I would appreciate!
