### ISSUE TITLE
HabboMail Security Enhancement

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#127]
Hi,

Some security enhancement for HabboMail is to:

- Add Expiry Time for HabboMail Links (If I'm not wrong its 48 hours)
- Invalidating previous HabboMail Link if a new link is being sent out

**Comment by sant0ro** [comment]
As I stated before, I only coded the basics of Transactions. The security would be made by the End-User.

But those things I think I can code.
Added to BackLog.

**Comment by sant0ro** [comment]
I coded it, but didn't tested. Please give a try.

Remember to create a record on `chocolatey_shop_payments_checkout`

**Comment by s150217754** [comment]
Hey @sant0ro ,

I think you might have misread my Issue.. I was talking about HabboMail (Email) not HabboMall (Shop)..

Regarding how the Activation token should last and expire if a new one is being generated.

**Comment by sant0ro** [comment]
Oh, I see. But the token already is expired after used.

Only the mail links wanna expire. As far I know they don't expire.

**Comment by s150217754** [comment]
@sant0ro 

Actually, Email tokens do expire within 48 hours (it's stated on the Email Template :P) or if a new token is generated for the account. Anyway, its just a _low_-security enhancement so probably can do it when you're done with your backlog.

_Off topic:_

I will be updating Chocolatey to 528e952 (Pre-Beta) on my end tomorrow. Will give it a test and report any issues that I may encounter. Great work 👍

**Comment by sant0ro** [comment]
Thanks @s150217754 It would be awesome reporting bugs. I'll also need help to migrate all languages.

**Comment by sant0ro** [comment]
Coding expire time.

**Comment by sant0ro** [comment]
Coded.
