### ISSUE TITLE
chocolatey path bug?

### ISSUE THREAD

**Issue by mclucario** [sant0ro/chocolatey#128]
I installed the current version of chocolatey to my Apache2 Server. The paths of the script files seem to be in the wrong path though.

![screenshot_20170402_192532](https://cloud.githubusercontent.com/assets/10533763/24589469/1f626042-17db-11e7-87d2-e9fde372bdde.png)

This is my [current settings file](https://pastebin.com/EiR0Pxvi)
PHP Version: PHP 7.0.17-2+deb.sury.org~yakkety+1 (cli) (built: Mar 15 2017 09:24:37) ( NTS )

Edit: Could it have something to do with web.config and the fact that im using apache2?

**Comment by sant0ro** [comment]
I can't see what is wrong here.

**Comment by sant0ro** [comment]
Okay I fixed it. If you're using latest binaries, you will get a weird scripts.js bug.

Next release will have fixed it. (Was an ISO excolation)

**Comment by mclucario** [comment]
Thank you. Im glad I could help.

**Comment by sant0ro** [comment]
No problem! I'm really sorry that you had that problem.
