### ISSUE TITLE
Photos card__meta dimensions

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#133]
http://prntscr.com/esby2j

**Comment by dominicusdev** [comment]
Fixed in fced462e8d9c2f1a579e19f74463053f2ef8474a

**Comment by Ninktos** [comment]
Updated, and stills appearing like that for me

**Comment by dominicusdev** [comment]
HMU on skype,
wizcsharp

**Comment by Ninktos** [comment]
Sorry, I do not use Skype. I would be glad if you could help me here

**Comment by dominicusdev** [comment]
Teamviewer? Easier to find the bugs if I'm able to look at the code from a proper perspective

**Comment by Ninktos** [comment]
https://pastebin.com/SH7WRWZX

**Comment by sant0ro** [comment]
What's happening here?

**Comment by Ninktos** [comment]
The first problem that I had is fixed.
Now, I have that on log's file.

**Comment by s150217754** [comment]
@Ninktos Kindly update if you require this Issue to be open. Will be closing it in a couple hours or so.

**Comment by s150217754** [comment]
Closing this. @Ninktos if you're still experiencing issue, please feel free to re-open this Issue.
