### ISSUE TITLE
Language stuck to NL?

### ISSUE THREAD

**Issue by mclucario** [sant0ro/chocolatey#135]
I kidna only get dutch as an language even though I kept the default settings which seem to be english.

![screenshot_20170404_230745](https://cloud.githubusercontent.com/assets/10533763/24679502/9939401c-198d-11e7-9879-5c58043eb1a2.png)

![firefox_2017-04-04_23-25-30](https://cloud.githubusercontent.com/assets/10533763/24679669/2c91ecec-198e-11e7-8b68-3c322ae8ff02.png)

**Comment by RetroPiggy** [comment]
That's your catalogue which is in Dutch. The catalogue is managed by the database, not the CMS.

**Comment by s150217754** [comment]
As what @RetroPiggy has mentioned, this is a Catalogue Issue not a CMS issue.

For a English catalogue, do consider using Jmandupree's release on RZ.

Closing this.

**Comment by mclucario** [comment]
Alright, thank you.

**Comment by Seblar** [comment]
Hi, did you solve this? If so how? I experience the same problem and I've checked the database and it shows no sign of dutch.

**Comment by mclucario** [comment]
Hey, Habbo works following way:
Server
Content (Catalouge)
Client (Your Game)

The client loads all the text and pictures from your content. The position and rooms of the players come from the server. So that means you need to get content in english.
