### ISSUE TITLE
News dont show up

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#14]
![screenshot_23](https://cloud.githubusercontent.com/assets/25616317/22831136/e33be35a-efb1-11e6-9798-eaceff85b886.png)

I have the original test article still in my database. this might be linked with my last problem that I might be missing something (im using xampp with apache 2.4 and php 7.1.1) and of course [2.000](https://github.com/sant0ro/chocolatey/releases/tag/2.000)

INSERT INTO `arc`.`chocolatey_articles` (`id`, `title`, `description`, `content`, `author`, `categories`, `imageUrl`, `thumbnailUrl`, `roomId`, `created_at`, `updated_at`) VALUES ('1', 'Welcome to Chocolatey', 'You had successfully installed Chocolatey. Now let\'s drink a cup of Hot Chocolate?', '<b>It\'s good see that you chosed right!</b><br><h4>Chocolatey</h4> it\'s the right choose. We\'re glad you chosed us.<br><i>- Claudio Santoro</i>', 'System', 'technical.updates', 'https://habboo-a.akamaihd.net/web_images/habbo-web-articles/lpromo_gen15_51.png', 'https://habboo-a.akamaihd.net/web_images/habbo-web-articles/lpromo_gen15_51_thumb.png', '0', '2017-02-10 16:53:28', '2017-02-10 16:53:28');

**Comment by sant0ro** [comment]
Here news show up correctly.

I don't know what's happening in your PC.

**Comment by sant0ro** [comment]
@resrvoir i recommend you delete all chocolatey_* tables, and delete the migration table.

After that run php artisan migrate again.

Remember you need run "php artisan migrate" before start using Chocolatey.

**Comment by resrvoir** [comment]
didnt migrate completely fixed by migrating again

**Comment by sant0ro** [comment]
@resrvoir i'm glad thar you fixed.
