### ISSUE TITLE
Client Stuck 76%

### ISSUE THREAD

**Issue by dracau18** [sant0ro/chocolatey#15]
Hi !
I know i can found much issue like that on internet but the only solution i found is about the client page configuration.
All that i tested work, but when i went to go on the client, the loading stuck at 76%.
I have configured the .env with my mysql password and also the chocolatey.php in config folder, and setup correctly my game port of the emu.
Firstly i used the default SWF (default link) but it doesn't work, and after i use my own SWF (Habboon SWF found on sulake.cc and recommanded in the Artcurus forum PRODUCTION-201601012205-226667486)
But nothing to do..
The client stay stuck at 76% and it show that on the emu:
Screen emu: http://prnt.sc/e73bn9
Screen Console (F12): http://prnt.sc/e73brj
(I use XAMPP with no virtual hosts and all files in the htdocs folder)

**Comment by sant0ro** [comment]
You need check if this is the correct SWF from Arcturus 1.3.0.

After that check if the client configuration it's totally correct.

**Comment by dracau18** [comment]
My bad...
I have forgot to replace that Habbo.swf
Now that's work !
Thank

**Comment by sant0ro** [comment]
I'm glad to hear that.

@dracau18 so Chocolatey it's working totally for you? Register, etc?

**Comment by dracau18** [comment]
@sant0ro In the build of yesterday i had the same problem than an other issue (the reCaptcha bug) but with the latest release, no problem.
I haven't tested all it yet but if there is any problem i will report it to you :)

**Comment by sant0ro** [comment]
@dracau18 thanks ;)
