### ISSUE TITLE
[Suggestion] Logged on the last Avatar used

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#159]
It would be better to be logged on the last Avatar used. It's annoying to get into the preference every time for choose his Avatar

**Comment by BobyTS** [comment]
Then, the "client-new-user" page should be disabled when creating a new avatar from preferences. (Like Habbo)

**Comment by sant0ro** [comment]
@BobyTS as far I know the client-new-user page doesn't show to avatars created by preferences.

Can you confirm that this happens? If yes, Is it a bug that appeared recently.

Also I will code this feature of last avatar ID.

**Comment by s150217754** [comment]
Unable to verify this (client-new-user page upon creating a new avatar) at the moment because of Issue #164

**Comment by sant0ro** [comment]
**REMEBER** this issue it's about a suggestion and NOT about the bugs.

**Comment by sant0ro** [comment]
Coded.
