### ISSUE TITLE
isAvailable = true in api/user/avatars/check-name

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#160]
Well here is a big problem, wanting to create an avatar via the preference page, I realized a few things. It displays the value isAvailable = "true" when the user exists. This suddenly create huge SQL error on my site.

http://localhost/api/user/avatars/check-name?name=[username]

**Comment by BobyTS** [comment]
Well the function to create a new avatar seems completely broken, when I insert any pseudo, it try registers with the username of my existing account

**Comment by s150217754** [comment]
Thanks for reporting this @BobyTS 

I am able to verify this via the API link @sant0ro 

It returns` isAvailable=false only` on Blacklisted names (defined in chocolatey.php) **BUT** not registered names.

**Comment by BobyTS** [comment]
@s150217754 We can no longer create an avatar from the preference page, i get an error.
It does not take into account the "input" value and inserts the nickname of the current username, which causes an SQL duplication error

**Comment by s150217754** [comment]
@BobyTS Got it! Will try it on my end in the evening after updating to the latest release. 

Thanks again!

**Comment by sant0ro** [comment]
Okay, that's a huge bug. Annotated. Will fix it as soon as possible.

**Comment by s150217754** [comment]
Ok. Was able to confirm this issue (partially) on Chocolatey 2.800 b5d0345

### 1. Register new Avatar on a existing account (under Settings > Preference):

**Blacklisted Name**

![blacklist](https://cloud.githubusercontent.com/assets/25793165/24967656/6c7a2c20-1fdd-11e7-9e06-943d3183375b.png)

_Findings_
1. Functions as per expected. No issue or bug.

**Name that Exists in users (a.k.a registered user)**

![noerror](https://cloud.githubusercontent.com/assets/25793165/24967748/b64ee598-1fdd-11e7-82cd-0850f4efde7b.png)

_Findings_
1. Bug exists. Should prompt an error showing that name is in use
2. "Create" button can be clicked. When clicked:
    a) Chocolatey did not create the row on the users table (phew!)
    b) Entered client using avatar registered with the account (no security breach)

### 2. Register new Account via "Create a New Account"

**Blacklisted Name**

![nuxblacklist](https://cloud.githubusercontent.com/assets/25793165/24967987/5a2440fa-1fde-11e7-8829-e7c6efe91486.png)

_Findings_
1. Functions as per expected. No issue or bug.

**Name that Exists in users (a.k.a registered user)**

![nuxused](https://cloud.githubusercontent.com/assets/25793165/24967992/5e1d643e-1fde-11e7-94f4-8697e27c5973.png)

_Findings_
1. Functions as per expected. No issue or bug.

**Comment by s150217754** [comment]
Logs on the Bug is available at #164

**Comment by sant0ro** [comment]
All bugs Fixed as far I know.

ANYWAYS, I fixed the checking system.
