### ISSUE TITLE
NUX Name Recommendation

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#166]
**Enhancement**

There should be a option to disable foreign character (e.g. à è ì ò ù) for NUX Name Recommendation.

**Comment by BobyTS** [comment]
I have the same opinion, a regex must be setup

**Comment by sant0ro** [comment]
Can you provide screens about it? If I understood you want that special characters with those symbols doesn't be included on name recommendations?

**Comment by s150217754** [comment]
I'm not on my computer right now. 

See #163 for screenshot that I have posted
That user name have special character.

**Comment by BobyTS** [comment]
### Based on Habbo.com :
**Your name can contain lowercase and uppercase letters, numbers and the characters _-=?!@:.,**

**Comment by sant0ro** [comment]
Okay! Will fix it.

**Comment by sant0ro** [comment]
I will submit a PR to the RandomGenerator repo including Username Generator (edited by me) probably this weekend.

**Comment by BobyTS** [comment]
@sant0ro Interesting, I will do FR version a little later

**Comment by sant0ro** [comment]
Coded the FIX for if the username have diacritics (accents)

**Comment by BobyTS** [comment]
**Habbo.com uses this regex:**

`"/^[a-zA-Z0-9_\\-\\=\\?\\!@\\:\\.,\\$]+$/"`


This regex is present in the script.js for avatar creation :)
