### ISSUE TITLE
 Problem in selecting an Avatar

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#168]
Unable to select Avatar when you are admin.

**When you have access to housekeeping**
![withhk](https://cloud.githubusercontent.com/assets/26801809/24982185/6ec8f058-1fe0-11e7-91cc-d3ffaf60f645.PNG)

**When you are a simple user**
![withouthk](https://cloud.githubusercontent.com/assets/26801809/24982188/73c321aa-1fe0-11e7-9403-9dbec5389cfc.PNG)

**Comment by BobyTS** [comment]
Ok, this is not a bug, actually Sulake seems to forbid staffs the ability to create other Avatar
I found this in the script.js:  require-non-staff-account-session

**Comment by sant0ro** [comment]
Yes. And I implemented it.

:P

**Comment by res7702** [comment]
Could there be an setting to allow staff to create multiple avatars?
