### ISSUE TITLE
Disable Create Avatars for STAFF

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#169]
I'm talking about this in Issue #168
Sulake prohibits create and select avatar for a STAFF session.
But we can still create an avatar, I don't know if the bug comes from script.js

What do you think ?

**Comment by sant0ro** [comment]
Oh yes, I though I have coded prohibiting staff creating more users.

Will code it.

**Comment by sant0ro** [comment]
Coded it.

**Comment by BobyTS** [comment]
Perfect, but the button is still present while it is useless, nothing we can do?

**Comment by sant0ro** [comment]
Sadly this is an HabboWEB thing. Obviously I can Inject code removing it. Will test it now.

**Comment by BobyTS** [comment]
Why does the "require-non-staff-account-session" not work? Strange

**Comment by sant0ro** [comment]
Fixed it.

The correct usage is `habbo-require-non-staff-account-session`
