### ISSUE TITLE
Selecting username

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#17]
![37d98609a02e4938bf5f39bbfc91a8f7](https://cloud.githubusercontent.com/assets/25616317/22850682/af0bed04-f016-11e6-95d8-6d009e10ff4d.png)

maybe add a limit to this form

**Comment by sant0ro** [comment]
Is this a bug? Or you wrote all those characters? But yes, it's a good idea putting a limit hahaha.

I will add as a priority.

Thanks!

**Comment by sant0ro** [comment]
Uncomment this on your php.ini from XAMPP

;extension=php_pdo_mysql.dll

And ensure that mysql it's enabled also.

**Comment by sant0ro** [comment]
Fixed.
