### ISSUE TITLE
Question about staff items on HabboWEB

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#170]
Analyzing the code, is possible to see multiple staff things implementations. I'm doing a research about it.

<pre>
    return s.register = function (s) {
        return a.register(s.birthdate), a.isLocked() ? t.reject({data: {error: "age"}}) : e.post(r.apiUrl + "/public/registration/new", s).then(function (e) {
            var r = t.defer();
            return 204 === e.status ? (n.trackEvent("Registration", "Registered", "Staff"), r.resolve(e)) : (n.trackEvent("Registration", "Registered", "User"), o.piwikTrack && (o._spef.push(["trackGoal", 1]), o.piwikTrack()), i.init(e.data).then(function () {
                r.resolve(e)
            })), r.promise
        })
    }, s
</pre>

**Comment by sant0ro** [comment]
@s150217754 I'm searching about "Server Announces" functionality. Does you ever seen something like that on Habbo?

**Comment by s150217754** [comment]
@sant0ro Hmm.. Will need more info. On which part of Habbo's CMS?

**Comment by sant0ro** [comment]
Like the modals that appears on the top (those green modals of success saving items..)

**Comment by s150217754** [comment]
Ah, ok. So you are looking for a modal that shows Server Announcement or something?

**Comment by sant0ro** [comment]
Yes. Does this exists on Habbo?

**Comment by s150217754** [comment]
@sant0ro Checked with a few friends whom are veterans of Habbo (playing ten years straight or so), none of them have stumbled any modal relating to "Server Announcement" on the new HabboWEB.

**Comment by sant0ro** [comment]
Thanks!
