### ISSUE TITLE
Missing drivers on instalation

### ISSUE THREAD

**Issue by RetroPiggy** [sant0ro/chocolatey#18]
When running the 'php artisan migrate' command installation 2 errors appear claiming some drivers cannot be found. Running Windows 10 with xampp and PHP version 7.0.15

http://i.imgur.com/E2yK1zd.png

**Comment by sant0ro** [comment]
Uncomment this on your php.ini from XAMPP

;extension=php_pdo_mysql.dll

And ensure that mysql it's enabled also.

**Comment by RetroPiggy** [comment]
Ok, got this step done and have everything configured but the site is just white. No errors in console :/

**Comment by sant0ro** [comment]
You enabled the PDO? And executed "php artisan migrate" ?

After execution the page it's just white?

Can you do CTRL + U on the page?

**Comment by RetroPiggy** [comment]
This is the result of pressing CTRL+U: http://i.imgur.com/k5zIrdj.png

And yes, I ran the command and the database tables have been created.

**Comment by sant0ro** [comment]
You forgot adding a slash "/" on the end of your URL.

**Comment by sant0ro** [comment]
If you see the URIs are http://localhosthabboweb.... but need to be http://localhost/habbo-web

Add a slash in the end of the URI on chocolatey.php

**Comment by RetroPiggy** [comment]
Yes, I did see that and I added the / but page is still white.

**Comment by RetroPiggy** [comment]
Oh, hold on. Its fixed :) I just downloaded it again and re-copied the files over. I guess it was something wrong with my download :/ Anyway, thanks for the help with the previous issue :)
