### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by BobyTS** [sant0ro/chocolatey#181]
**Lumen.log :**
[lumenlog.txt](https://github.com/sant0ro/chocolatey/files/926124/lumenlog.txt)

**Comment by sant0ro** [comment]
Did you see what I said on Forum. All accounts need to b reseted. (Database clean).

Anyways this error happens if password is wrong. Will fix it.

**Comment by sant0ro** [comment]
No problem in wrong password. You should read what i wrote in Development thread of Chocolatey.

**Comment by sant0ro** [comment]
@BobyTS ?

**Comment by BobyTS** [comment]
Yes, we are changing the structure of our database to avoid resetting.

**Comment by sant0ro** [comment]
Okay! Just check the structure of what changed. If you need help, just ask.

Onliest table that changed was `chocolatey_users_id`
You need migrate the users password unto chocolatey_users_id.

I think you will like the new system. Was made specially for you, @BobyTS 😄

**Comment by s150217754** [comment]
I just migrated the ```chocolatey_users_id``` manually by copying the password field from users table. Everything works great and flawlessly.

Meanwhile, closing this since its not an issue.
