### ISSUE TITLE
Chocolatey stuck on client-new-user

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#182]
@BobyTS does `client-new-user` is fixed? I didn't tested because I don't have SWF. Can you check it?

**Comment by s150217754** [comment]
**Problems with client-new-user on 3.000A:**
1. Refreshing Client after Account Creations will Trigged NUX Screen
2. NUX Screen allows multiple NUX rooms to be generated and Change of Name

**Comment by sant0ro** [comment]
That's weird. Will try to fix it.

**Comment by sant0ro** [comment]
@s150217754 ?

**Comment by s150217754** [comment]
@sant0ro Trying it now. Hold on

**Comment by sant0ro** [comment]
Okay! Thanks.

**Comment by s150217754** [comment]
@sant0ro Same issue after updating to latest binaries branch (download as zip not release). Able to return back to NUX screen to change name and select room.

**Comment by sant0ro** [comment]
<pre>
    /**
     * Select a Room.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function selectRoom(Request $request): Response
    {
        if (!in_array($request->json()->get('roomIndex'), [1, 2, 3])) {
            return response('', 400);
        }

        Nux::generateRoom($request);

        UserFacade::getUser()->traits = ['USER'];

        return response(null, 200);
    }
</pre>

Change the content of `selectRoom()` from `NuxController` to this one.
And try again.

**Comment by s150217754** [comment]
Problem solved!!! @sant0ro

**Comment by sant0ro** [comment]
Okay! Going to commit.

**Comment by BobyTS** [comment]
Oh perfect, thx you!
