### ISSUE TITLE
Group badge don't show up (habbo-imaging)

### ISSUE THREAD

**Issue by dracau18** [sant0ro/chocolatey#19]
Hey,
I don't know if its a cms related issue but the group badge in the client don't show up.
The .htaccess is well configured (the default one you provided), but when i request the badge via url, it print me a breaked gif.
"The image 'http://...." cannot be displayed because it contains errors." on Mozilla and http://prnt.sc/e7pkyf on Edge.

**Comment by sant0ro** [comment]
I don't know what this possible can be. I will investigate about it.

Thanks ;)

**Comment by s150217754** [comment]
Hello,

As an alternative workaround, if you used the Internal Badge Generator of Arcturus, you can do some changes to the scripts.js.

Go to **/public/habbo-web/scripts.js**

Replace:
`GroupBadgeController.imagingUrl + '/badge/' + GroupBadgeController.code + '.gif`
With:
`GroupBadgeController.imagingUrl + '' + GroupBadgeController.code + '.png`

And change your groupBadgeUrl parameter to your Generated folder (example for mine):
`groupBadgeUrl: "https://localhost:8080/c_images/Badgeparts/generated/",`

Hope this helps.

**Comment by sant0ro** [comment]
Isn't good, do multiple injections on Habbo Scripts.

Group Badge will only work if you setup correctly Arcturus Group Badge Configuration.

Request closed.
