### ISSUE TITLE
Verification email

### ISSUE THREAD

**Issue by mikkelbfriis** [sant0ro/chocolatey#194]
When trying to click "Send verification email" on user settings, I receive:

ErrorException in Mappable.php line 502:
Undefined property: App\Models\User::$email

**Comment by sant0ro** [comment]
Can you attach `lumen.log` @dominicusdev ?

**Comment by dominicusdev** [comment]
[2017-04-22 19:53:13] lumen.ERROR: ErrorException: Undefined property: App\Models\User::$email in /var/www/html/vendor/sofa/eloquence/src/Mappable.php:502
Stack trace:
#0 /var/www/html/vendor/sofa/eloquence/src/Mappable.php(502): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined prope...', '/var/www/html/v...', 502, Array)
#1 /var/www/html/vendor/sofa/eloquence/src/Mappable.php(485): App\Models\User->getTarget(Object(App\Models\User), Array)
#2 /var/www/html/vendor/sofa/eloquence/src/Mappable/Hooks.php(108): App\Models\User->mapAttribute('email')
#3 /var/www/html/vendor/sofa/hookable/src/Pipeline.php(84): App\Models\User->Sofa\Eloquence\Mappable\{closure}(Object(Closure), 'mikkelbfriis@ho...', Object(Sofa\Hookable\ArgumentBag))
#4 [internal function]: Sofa\Hookable\Pipeline->Sofa\Hookable\{closure}('mikkelbfriis@ho...', Object(Sofa\Hookable\ArgumentBag))
#5 /var/www/html/vendor/sofa/hookable/src/Pipeline.php(88): call_user_func_array(Object(Closure), Array)
#6 /var/www/html/vendor/sofa/hookable/src/Hookable.php(245): Sofa\Hookable\Pipeline->to(Object(Closure))
#7 /var/www/html/vendor/sofa/hookable/src/Hookable.php(95): App\Models\User->pipe(Array, 'mikkelbfriis@ho...', Array, Object(Closure))
#8 /var/www/html/vendor/illuminate/database/Eloquent/Model.php(1234): App\Models\User->getAttribute('email')
#9 /var/www/html/app/Http/Controllers/AccountController.php(211): Illuminate\Database\Eloquent\Model->__get('email')
#10 [internal function]: App\Http\Controllers\AccountController->verifyAccount(Object(Illuminate\Http\Request))
#11 /var/www/html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#12 /var/www/html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#14 /var/www/html/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#15 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#16 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#17 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'verifyAccount', Array)
#18 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#19 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#20 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /var/www/html/app/Http/Middleware/Authenticate.php(50): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/html/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#34 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#43 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#44 /var/www/html/index.php(31): Laravel\Lumen\Application->run()
#45 {main}

**Comment by sant0ro** [comment]
If possible, @dominicusdev attach as a file.

**Comment by sant0ro** [comment]
@dominicusdev what exactly happens does you know? @BobyTS can you try to recreate his steps?

I mean can you send a "Send verification email" to him?

**Comment by sant0ro** [comment]
![image](https://cloud.githubusercontent.com/assets/12037269/25388870/5ee42de6-29a5-11e7-8acf-a894c490bf91.png)
Here it works, @dominicusdev

**Comment by BobyTS** [comment]
It works for me too.

**Comment by s150217754** [comment]
@mikkelbfriis Please comment if you are still facing this issue. Closing this.
