### ISSUE TITLE
Help to translate to French

### ISSUE THREAD

**Issue by dracau18** [sant0ro/chocolatey#20]
Hey,
I want to help you to translate to french but i saw there is a lot of lines to translate.
There is any method to take text from french hotel with api ?

**Comment by sant0ro** [comment]
Hey @dracau18 i will create a translation Tutorial.

But in the Beta Releases, will be added the following languages.:

1. Spanish
2. French
3. German
4. Other Local Habbo's Languages

Chocolatey actually supports.:
1. English
2. Portuguese
