### ISSUE TITLE
Collaborators Only

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#207]
@s150217754 and @BobyTS are you still in there?

**Comment by BobyTS** [comment]
@sant0ro Yes

**Comment by sant0ro** [comment]
Okay! Read the Issues that you created :)

**Comment by s150217754** [comment]
@sant0ro Am aboard till end of this month. My activity will be limited till then. Will try to look into the issues whenever I'm free.

**Comment by sant0ro** [comment]
No probz.
