### ISSUE TITLE
Profile page incomplete?

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#21]
I haven't seen you mentioning anywhere that this is in progress so..
What's missing: 
- rooms
- friends
- rooms
- badges
- taken pictures

### Chocolatey:
![screenshot_4](https://cloud.githubusercontent.com/assets/25616317/22898296/67315e54-f22f-11e6-9707-22d49c0f027f.png)

### Habbo:
![screenshot_3](https://cloud.githubusercontent.com/assets/25616317/22898306/6e769aee-f22f-11e6-97a4-15cffc80bd7f.png)

**Comment by sant0ro** [comment]
Closing Issue.

This totally works on Chocolatey.

If you see a screenie of Chocolatey in Release Thread. Will see it.

Please see the full list of features before creating those Issues.
