### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by DenKyr** [sant0ro/chocolatey#217]
I translated the resource folder to Dutch,
how do i submit?

**Comment by sant0ro** [comment]
Create a Pull Request with the changes. Or attach the files here.

**Comment by DenKyr** [comment]
Here:
[dutchlanguage.zip](https://github.com/sant0ro/chocolatey/files/966880/dutchlanguage.zip)

**Comment by DenKyr** [comment]
**Forgot to change something here's and updated version:**
[dutchlanguage.zip](https://github.com/sant0ro/chocolatey/files/966926/dutchlanguage.zip)

**Comment by DenKyr** [comment]
@sant0ro

**Comment by sant0ro** [comment]
Thanks! Going to patch it.

**Comment by sant0ro** [comment]
@DenKyr your translation has some issues.

First in all templates you need change the targeting language from `english` to `dutch` 

![image](https://cloud.githubusercontent.com/assets/12037269/25585805/ba6e5d68-2e72-11e7-99bb-f4a65aa2dc32.png)

**Comment by sant0ro** [comment]
Secondly, please include also the following file `resources/views/hbbo-web-10ln/your-language.json`

**Comment by DenKyr** [comment]
@sant0ro Changed it including some other fixes
[dutchlanguage2.zip](https://github.com/sant0ro/chocolatey/files/968434/dutchlanguage2.zip)

**Comment by DenKyr** [comment]
@sant0ro 
[dutch.zip](https://github.com/sant0ro/chocolatey/files/968441/dutch.zip)
changed it including some other fixes :)

**Comment by sant0ro** [comment]
Okay, going to patch it.

**Comment by sant0ro** [comment]
Forgot to say, that I patched it successfully!
