### ISSUE TITLE
Error in getting avatar head

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#22]
### In /community/rooms
![screenshot_6](https://cloud.githubusercontent.com/assets/25616317/22899228/ca74994c-f232-11e6-87aa-72c7bbdeebaf.png)

### In /room/id
![screenshot_5](https://cloud.githubusercontent.com/assets/25616317/22899265/e22f01d0-f232-11e6-9b3b-1346fc7d1011.png)

**Link to the invalid image**:
https://www.habbo.de/habbo-imaging/avatarimage?figure=undefined%2Cs-2.g-1.d-2.h-2.a-0%2C2675ee9fc9f15a8878060adc6606ffb9&size=l&headonly=1

Also inspect element points to `/habbo-web/app.css:1760` for the image

**Comment by sant0ro** [comment]
Yes this is an common Error also in /community/photos

I'm searching about a workaround by injecting code on Habbo's Angular Core.

I will update this Issue when i accomplish new progresses.

**Comment by sant0ro** [comment]
Fixed in Last Commit.
