### ISSUE TITLE
HTTP 500 ERROR

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#239]
Hello.
I have install: php7 (manual from Wiki)
Apache2 (mod_rewrite is activate)
DB is for test external from lima-city.de.
OS: Debian 8.8

What I make false?

**Comment by sant0ro** [comment]
Hi @iPrinz96!

Thanks for reporting an Issue to the **Chocolatey Repository**.

We're glad that you're using our software. I need to remember that **this** message was generated automatically.

In order to **gracefully** report your Issue, please we recommend the followance of those requirements:

Here's what to do: if you need help:

* Inform a complete message of your problem, and what's happening.
* Attach your **lumen.log** if it exists.
* Attach images of the reported bugs/glitches.
* Attach also Information about Operational System, Web Server, PHP Versiom, and other infos.
* Explain what you tried and how tried.

Recommendations About your recently opened Issue?
--------------------------------

We really recommend using [Lightshot](https://app.prntscr.com/pt-br/download.html) to take your screenshot. It allows marks, annotations and more.

If you bug it's about a feature from **Chocolatey** or glitch, we **trully** recommend taking a **HAR File**. You can attach a [HAR File following this procedure](https://support.cloudflare.com/hc/en-us/articles/203118044-How-do-I-generate-a-HAR-file-).

A **HAR** file it's a complete log of the network requests of a specific page.

Also we recommend specify some Informations about your **OS** like.:

* Operational System
* Which Web Server are you using (like XAMPP)
* Which version of Web Server Using (eg.: 1.7.3)
* Which version of php & mysql & apache using. (Specify if is possible)
* How much RAM does you have?

Are you creating a Feature Request?
------------------------------

About Feature requests, we recommend you specify completely about what your **Feature Request** is. Tag the type of change that you want to be added.

Changes need to be specified, and you need specify why and what you want to be changed/added.

Be creatively and try explain in the best manner as possible.

Tag the Issue on the Title
-------------------------------

Tagging your Issue will be the best thing you can do for us. We separate issues by tags, and we can work more quickly by knowing from what is the Issue related.

**Those are the available tags:**

* Security
* Angular
* Feature Request
* Server Error
* HabboWEB Glitch
* Translation Mistake
* CSS Mistake/Glitch
* Feature not Working
* Help Wanted
* Can't Install
* Urgent Issue
* Game Bug
* Migration Bug
* Upgrading Bug

**Remember to tag on the title of the Issue [_Issue Type_]**

I updated my Issue.. And now?
---------------------------

You wait.

We have **ful-jobs** and a **life**, we will receive updates by e-mail and soon as possible update your **Issue** by tagging it correctly, assigning to our team and **obviously** answering it.

Then we will support you and help you in what we can.

Also if you Issue it's out of the **params** we will not answer it, or answer it **asking to you fix and correct the main message**

If you dom't know how to use GitHub correctly, check [this](https://guides.github.com/features/issues/) tutorial.

Further information
-------------------

* This **BOT** was originally created by @ajdlinux and @daxtens.
* Edited by @sant0ro for own purposes.
* Contributors of Chocolatey @BobyTS and @s150217754

**Comment by iPrinz96** [comment]
i have install it on Ubuntu 14 now.
i have a new Problem.
You Can #closed this issue

**Comment by sant0ro** [comment]
Okay!

**Comment by iPrinz96** [comment]
Okay.
php 7.0 dont work on Ubuntu. Iam to stupid to fixxed it. I think that is a error by my Provider img.
So i use again Debian 8.0 and have the self Problem.
HTTP 500 error..
PHP 7.0 is installed but i cant open the website.. On safarie browser is the site with(Blank) and on chrome come an HTTP 500 Error..
What i can do?..

**Comment by sant0ro** [comment]
You downloaded the Release, right?
So exists a folder called vendor, yeah?
You configured database on .env
and you executed "php artisan migrate"
right?
Also before running "migrate" you imported Arcturus 1.7.0 database, right?

**Comment by iPrinz96** [comment]
Yes. Db is uploaded and php arstian migrate is complete

**Comment by sant0ro** [comment]
Attach `lumen.log` from storage/logs folder.

**Comment by iPrinz96** [comment]
`[2017-05-24 15:54:15] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in /var/www/html/vendor/illuminate/database/Connectors/Connector.php:68
Stack trace:
#0 /var/www/html/vendor/illuminate/database/Connectors/Connector.php(68): PDO->__construct('mysql:host=127....', 'arcturus', 'arcturus', Array)
#1 /var/www/html/vendor/illuminate/database/Connectors/Connector.php(44): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'arcturus', 'arcturus', Array)
#2 /var/www/html/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /var/www/html/vendor/illuminate/database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/html/vendor/illuminate/database/Connection.php(882): call_user_func(Object(Closure))
#6 /var/www/html/vendor/illuminate/database/Connection.php(903): Illuminate\Database\Connection->getPdo()
#7 /var/www/html/vendor/illuminate/database/Connection.php(392): Illuminate\Database\Connection->getReadPdo()
#8 /var/www/html/vendor/illuminate/database/Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
#9 /var/www/html/vendor/illuminate/database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#10 /var/www/html/vendor/illuminate/database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#11 /var/www/html/vendor/illuminate/database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#12 /var/www/html/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#13 /var/www/html/vendor/illuminate/database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#14 /var/www/html/vendor/illuminate/database/Migrations/Migrator.php(538): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
#16 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#17 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#18 /var/www/html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#21 /var/www/html/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#22 /var/www/html/vendor/illuminate/console/Command.php(182): Illuminate\Container\Container->call(Array)
#23 /var/www/html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 /var/www/html/vendor/illuminate/console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 /var/www/html/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}  
[2017-05-24 15:54:15] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in /var/www/html/vendor/illuminate/database/Connectors/Connector.php:68
Stack trace:
#0 /var/www/html/vendor/illuminate/database/Connectors/Connector.php(68): PDO->__construct('mysql:host=127....', 'arcturus', 'arcturus', Array)
#1 /var/www/html/vendor/illuminate/database/Connectors/Connector.php(44): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=127....', 'arcturus', 'arcturus', Array)
#2 /var/www/html/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#3 /var/www/html/vendor/illuminate/database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 /var/www/html/vendor/illuminate/database/Connection.php(882): call_user_func(Object(Closure))
#6 /var/www/html/vendor/illuminate/database/Connection.php(903): Illuminate\Database\Connection->getPdo()
#7 /var/www/html/vendor/illuminate/database/Connection.php(392): Illuminate\Database\Connection->getReadPdo()
#8 /var/www/html/vendor/illuminate/database/Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
#9 /var/www/html/vendor/illuminate/database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#10 /var/www/html/vendor/illuminate/database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#11 /var/www/html/vendor/illuminate/database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#12 /var/www/html/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#13 /var/www/html/vendor/illuminate/database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#14 /var/www/html/vendor/illuminate/database/Migrations/Migrator.php(538): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
#16 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#17 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#18 /var/www/html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#19 /var/www/html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 /var/www/html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#21 /var/www/html/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#22 /var/www/html/vendor/illuminate/console/Command.php(182): Illuminate\Container\Container->call(Array)
#23 /var/www/html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#24 /var/www/html/vendor/illuminate/console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#25 /var/www/html/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = arcturus and table_name = migrations) in /var/www/html/vendor/illuminate/database/Connection.php:647
Stack trace:
#0 /var/www/html/vendor/illuminate/database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /var/www/html/vendor/illuminate/database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#2 /var/www/html/vendor/illuminate/database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#3 /var/www/html/vendor/illuminate/database/Migrations/DatabaseMigrationRepository.php(154): Illuminate\Database\Schema\MySqlBuilder->hasTable('migrations')
#4 /var/www/html/vendor/illuminate/database/Migrations/Migrator.php(538): Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists()
#5 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(96): Illuminate\Database\Migrations\Migrator->repositoryExists()
#6 /var/www/html/vendor/illuminate/database/Console/Migrations/MigrateCommand.php(62): Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase()
#7 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#8 /var/www/html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#11 /var/www/html/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#12 /var/www/html/vendor/illuminate/console/Command.php(182): Illuminate\Container\Container->call(Array)
#13 /var/www/html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 /var/www/html/vendor/illuminate/console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 /var/www/html/vendor/symfony/console/Application.php(835): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(200): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(84): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  
`

**Comment by s150217754** [comment]
Re-opening as the issue has yet to resolve.

From your `lumen.log` provided, it seems like your database is not accepting connection:

`Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = arcturus and table_name = migrations) in /var/www/html/vendor/illuminate/database/Connection.php:647`

Please check whether your database credential in `.env` file is accurate and ensure that your SQL User permission is set to the correct database and allows connection from where Chocolatey is hosted on.

**Comment by iPrinz96** [comment]
this problem is fixxed. i have edit the .env file with me correct MySQL data.
my database was Successful updated. But i cant still not open my site. HTTP 500 ERROR...

**Comment by s150217754** [comment]
Kindly delete your `lumen.log` again and re-access your Site **once**.

Then, let us have a look at your `lumen.log` again.

**Comment by iPrinz96** [comment]
After reboot and load the site, was no new log file created. In the sotrage folder is only lumen.log.save...

**Comment by sant0ro** [comment]
And what `lumen.log.save` has?

Does the page goes blank? what appears? Can you attach a screenshot?

**Comment by sant0ro** [comment]
Also does the folder `vendor` exists? Does the `/var/www/html` folder has the right group permissions?

Check the following.:

`nano /etc/httpd/conf/httpd.conf` and check which UserGroup your apache runs, if is apache or daemon.

Give `chown -R apache:apache /var/www/html`
Or `chown -R daemon:daemon /var/www/html`

Maybe this is a permission problem.

**Comment by iPrinz96** [comment]
User group ist right..
User is set on deamon

U can see self on music.iprinz.de
The site is blank..

**Comment by sant0ro** [comment]
No other logs on lumen.log?

Can you send a screenshot of the following command:

`ls -la /var/www/html`

and please do this command also:

`chown -R daemon:daemon /var/www/html`

**Comment by iPrinz96** [comment]
https://www.pic-upload.de/view-33226419/Bildschirmfoto2017-05-25um17.51.33.jpg.html

**Comment by iPrinz96** [comment]
U have testet this cms on raspberry pi? I think my img from my server is bugged. I can test it on raspbian

**Comment by s150217754** [comment]
Hello,

It should work on any platform provided you have Apache and PHP7 running (as recommended).

Another thing that you might want to check is that you have configured your Site URL accurately at `config/chocolatey.php`.

**Comment by iPrinz96** [comment]
Hotel Site URL is right..
i have configured chocolatey.php and database.php..

**Comment by iPrinz96** [comment]
http://music.iprinz.de/info.php

**Comment by iPrinz96** [comment]
i have found the Problem.
If i move the habbo-web folder from the public folder to var/www/html. than work it to 80%
See self on: music.iprinz.de
how i fix that?

**Comment by sant0ro** [comment]
That means that your .htaccess wasn't working. You need put it back to public folder.

It need to be on that place.

Pleace check if your apache is reading your `.htaccess`

**Comment by iPrinz96** [comment]
How i check it?

**Comment by iPrinz96** [comment]
i have fix it. it works..
But i have problems with recaptcha  xD
my key was safed

**Comment by s150217754** [comment]
What's the problem with Recaptcha?

You will need to provide more information on the Error message, for instance:

1. Chocolatey Error (the site itself)
2. Chrome Error Log
3. Lumen Log

**Comment by iPrinz96** [comment]
i think my DB was false configurated. Its work. Issue can closed. For new Problems i open a new Issue.

My solution:
Here a the command list:
- chown -R www-data:www-data /var/www/html
- a2enmod rewrite
- nano /etc/apache2/sites-available/htccess.conf
Past this:
```
DocumentRoot /var/www/html
<Directory /var/www/html/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

```
Save it

Next command:
a2ensite /etc/apache2/sites-available/htaccess.conf
service apache2 restart

And mod_rewirte was configured with apache2.4.
Its work on Debian8 and Ubuntu16.04

**Comment by s150217754** [comment]
Closing this as Reporter have resolved the issue.

**Comment by sant0ro** [comment]
Good to kniow that you solved.

As I said, basically the problem was rewrite engine.
