### ISSUE TITLE
ReCaptcha Problem

### ISSUE THREAD

**Issue by Glavez** [sant0ro/chocolatey#249]
![captcha](https://user-images.githubusercontent.com/29415509/27108988-250cdf06-506e-11e7-9040-436a3b2c8e7b.png)

Already to install the cms, I enter and I register but at the end leaves error of captcha, any solution?
Also change the key but still not working

---------------------------------------------------

ISSUE FIXED. CHOCOLATEY USERS ID MISSING

**Comment by sant0ro** [comment]
Oh, I see, good that you solved it :)
