### ISSUE TITLE
Unable to Install chocolatey 2.080

### ISSUE THREAD

**Issue by hersentooped86** [sant0ro/chocolatey#25]
1. Using the [binaries.zip](https://github.com/sant0ro/chocolatey/releases/download/2.080/binaries.zip) file provided.
2. Was using chocolatey 2.063 previously. Deleted the folder and extracted 2.080 and edited chocolatey.php and .env before running php artisan migrate in chocolatey folder.

Error message when running **php artisan migrate**:

> [Illuminate\Contracts\Container\BindingResolutionException]
> Target [Illuminate\Contracts\Console\Kernel] is not instantiable.

Please advice.

**Operating Environment**
Running on XAMPP for Windows with PHP7

**Comment by sant0ro** [comment]
Please use 2.095.

Version 2.080 has this accidentally bug.
