### ISSUE TITLE
Registration not possible

### ISSUE THREAD

**Issue by ElroyNL** [sant0ro/chocolatey#251]
![screenshot_17](https://user-images.githubusercontent.com/17785391/27095307-78cd1648-506d-11e7-9b52-7dd11513d8f1.png)

Hello,

I cannot register on the registration page. I fill in the whole registration form and mark the captcha, everything looks fine but when I press the register button I come back at the registration form with the notification that there is a server error and a captcha error (that last is impossible on localhost, so it has to be the coding I think).

Hope to see a fix for this soon.

Good luck developing this CMS further in the future! 👍 

PS How to import the chocolatey_ database tables? - Maybe that's why this happens.

**Comment by sant0ro** [comment]
You need read the instructions of the tutorial. I will not give support until your read them.

Chocolatey isn't bugged, and works flawlesly in many computers.

Please read the tutorial.

A little tip, `php artisan migrate`.

**Comment by iPrinz96** [comment]
i have the same Problem.
First Acc was without Problems. But the seccound test Acc dont work anymore.
I have test it on another PC Too..

**Comment by sant0ro** [comment]
@iPrinz96 your case it's different from the OP's one.

Please attach your `lumen.log`

**Comment by iPrinz96** [comment]
Is clear..

**Comment by sant0ro** [comment]
Okay, I will give a clean Chocolatey install and check what's happening.

Regards, Claudio

@s150217754 can you give a clean Install too?

**Comment by sant0ro** [comment]
Just a little note, I need to clarify, that the registration process it's simulated by our automated build system.

You can check which tests are made on each Chocolatey version, by accessing this folder:
https://github.com/sant0ro/chocolatey/tree/master/tests

Here it's the status of the last build.: https://travis-ci.org/sant0ro/chocolatey

**Comment by ElroyNL** [comment]
![screenshot_19](https://user-images.githubusercontent.com/17785391/27200127-f0b411f0-5218-11e7-9dfc-8f75b941f73b.png)

I followed the tutorial multiple times, but I cannot run a php command for some reason. Would you like to give some more information about it?

**Comment by sant0ro** [comment]
You need have php installed globally. If you use softwares like XAMPP put the complete path, like

`C:\xampp\php\php.exe artisan migrate`

**Comment by ElroyNL** [comment]
Solved:
First run Cd c:/xampp/htdocs, than run C:/xampp/php/php.exe artisan migrate.
