### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ElroyNL** [sant0ro/chocolatey#252]
![screenshot_20](https://user-images.githubusercontent.com/17785391/27202578-769629e4-5222-11e7-888f-4dd5da86664a.png)

Hello, I use chocolatey-3.000D without problems, but when I want to update to the very last version I get an instant error when I try to open the webpage.

I have already tried the reupload the Arcturus' and Chocolatey's database, and redownload the CMS, but nothing helps.

I use the latest version of Xampp with the highest available PHP.

**Comment by sant0ro** [comment]
Closing this Issue.

Please **read** the tutorial. You're not using latest version from Releases section.

Releases included vendor files. Please note that Chocolatey hasn't bugs, since the Build System provided by Travis-CI didn't detected it. And passed successfully.
