### ISSUE TITLE
How to disable Habbo's language redirector

### ISSUE THREAD

**Issue by ElroyNL** [sant0ro/chocolatey#254]
![screenshot_25](https://user-images.githubusercontent.com/17785391/27264356-e35afc74-547c-11e7-94b2-ffc7d1ed0176.png)

Hello,

How to disable the language redirector on the homepage beneath the register button?

Thanks in advance.

Have a good day.

**Comment by sant0ro** [comment]
I will remove it on the next version. Thanks.

**Comment by ElroyNL** [comment]
You haven't to delete it, you can edit 4 289 with slogan or other texts. Maybe it is an idea to add REGISTER_BANNER on the language files, so you can edit the banner in what you want in a simple way?

**Comment by sant0ro** [comment]
Exactly, like he said. But I will remove it on the next version.
