### ISSUE TITLE
Recaptcha not working

### ISSUE THREAD

**Issue by thedevilsden** [sant0ro/chocolatey#255]
Imported arcturus 1.8 db. Edited env. Migrated successfully artisan. Getting this error:
https://pastebin.com/jADVieMj
Apache/2.4.25 
Php 7.16
MariaDB 10.1.24 
If this can help. Thanks in advance.

**Comment by thedevilsden** [comment]
**OK**
## Fixed:
Dropped database
Imported arcturus db as SQL query
Migrated
Working now. Can Close.

**Comment by sant0ro** [comment]
That's very nice!

Great that you solved it. Closing it :)
