### ISSUE TITLE
Client load to 76%

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#256]
Hello.
I have reinstall my Linux Server.
After this clean install, dont work my Client.

Here all Erros and Logs:

Lumen:
<pre>
[2017-06-24 21:24:52] lumen.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php:9
Stack trace:
#0 /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php(9): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to get p...', '/var/www/html/s...', 9, Array)
#1 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/html/s...')
#2 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/r...', Array)
#4 /var/www/html/vendor/illuminate/view/View.php(120): Illuminate\View\View->getContents()
#5 /var/www/html/vendor/illuminate/view/View.php(85): Illuminate\View\View->renderContents()
#6 /var/www/html/vendor/illuminate/http/Response.php(38): Illuminate\View\View->render()
#7 /var/www/html/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /var/www/html/vendor/laravel/lumen-framework/src/Http/ResponseFactory.php(23): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#9 /var/www/html/vendor/laravel/lumen-framework/src/helpers.php(279): Laravel\Lumen\Http\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#10 /var/www/html/app/Exceptions/Handler.php(55): response(Object(Illuminate\View\View))
#11 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(78): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#12 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(54): Laravel\Lumen\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#13 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#20 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#21 /var/www/html/index.php(26): Laravel\Lumen\Application->run()
#22 {main}

Next ErrorException: Trying to get property of non-object (View: /var/www/html/resources/views/habbo-web-pages/habbo-web.blade.php) in /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php:9
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/r...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(120): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(85): Illuminate\View\View->renderContents()
#5 /var/www/html/vendor/illuminate/http/Response.php(38): Illuminate\View\View->render()
#6 /var/www/html/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/html/vendor/laravel/lumen-framework/src/Http/ResponseFactory.php(23): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#8 /var/www/html/vendor/laravel/lumen-framework/src/helpers.php(279): Laravel\Lumen\Http\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#9 /var/www/html/app/Exceptions/Handler.php(55): response(Object(Illuminate\View\View))
#10 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(78): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#11 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(54): Laravel\Lumen\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#12 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#19 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#20 /var/www/html/index.php(26): Laravel\Lumen\Application->run()
#21 {main}  
[2017-06-24 21:24:53] lumen.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php:9
Stack trace:
#0 /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php(9): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to get p...', '/var/www/html/s...', 9, Array)
#1 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(42): include('/var/www/html/s...')
#2 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/r...', Array)
#4 /var/www/html/vendor/illuminate/view/View.php(120): Illuminate\View\View->getContents()
#5 /var/www/html/vendor/illuminate/view/View.php(85): Illuminate\View\View->renderContents()
#6 /var/www/html/vendor/illuminate/http/Response.php(38): Illuminate\View\View->render()
#7 /var/www/html/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /var/www/html/vendor/laravel/lumen-framework/src/Http/ResponseFactory.php(23): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#9 /var/www/html/vendor/laravel/lumen-framework/src/helpers.php(279): Laravel\Lumen\Http\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#10 /var/www/html/app/Exceptions/Handler.php(55): response(Object(Illuminate\View\View))
#11 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(78): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#12 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(54): Laravel\Lumen\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#13 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#20 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#21 /var/www/html/index.php(26): Laravel\Lumen\Application->run()
#22 {main}

Next ErrorException: Trying to get property of non-object (View: /var/www/html/resources/views/habbo-web-pages/habbo-web.blade.php) in /var/www/html/storage/framework/views/18d49e0b10ffbd4fc26f5ee1f6f07f0ac54f1814.php:9
Stack trace:
#0 /var/www/html/vendor/illuminate/view/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/html/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#2 /var/www/html/vendor/illuminate/view/View.php(137): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/r...', Array)
#3 /var/www/html/vendor/illuminate/view/View.php(120): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/illuminate/view/View.php(85): Illuminate\View\View->renderContents()
#5 /var/www/html/vendor/illuminate/http/Response.php(38): Illuminate\View\View->render()
#6 /var/www/html/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/html/vendor/laravel/lumen-framework/src/Http/ResponseFactory.php(23): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#8 /var/www/html/vendor/laravel/lumen-framework/src/helpers.php(279): Laravel\Lumen\Http\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#9 /var/www/html/app/Exceptions/Handler.php(55): response(Object(Illuminate\View\View))
#10 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(78): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#11 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(54): Laravel\Lumen\Routing\Pipeline->handleException(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\NotFoundHttpException))
#12 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#19 /var/ww
w/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#20 /var/www/html/index.php(26): Laravel\Lumen\Application->run()
#21 {main}  
</pre>

WebBrowser Console ( first 3 lines)
<pre>
action = [clientload], label = [client.init.start], value = [undefined]
habboapi.js (148,9)

action = [clientload], label = [client.init.swf.loaded], value = [undefined]
habboapi.js (148,9)

action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 0/62005]
habboapi.js (148,9)
</pre>

Arcturus Log

<pre>
[LOADING] Configuration Manager -> Loaded!
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[LOADING] Database -> Connected! (1156 MS)
[LOADING] Loading configuration from database...
[LOADING] Configuration -> loaded! (157 MS)
[LOADING] Thread Pool -> Loaded!
[LOADING] Plugin Manager -> Loaded! 0 plugins! (39 MS)
[LOADING] Texts Manager -> Loaded! (40 MS)
[LOADING] Database -> Cleaned!
[LOADING] GameEnvironment -> Loading...
[LOADING] Habbo Manager -> Loaded! (0 MS)
[LOADING] Hotelview Manager -> Loaded! (15 MS)
[LOADING] Item Manager -> Loaded! (1741 MS)
[LOADING] Bot Manager -> Loaded! (68 MS)
[LOADING] Pet Manager -> Loaded! (68 MS)
[LOADING] Guild Manager -> Loaded! (27 MS)
[LOADING] Loaded 257 Catalog Pages!
[LOADING] Catalog Manager -> Loaded! (486 MS)
[LOADING] Room Manager -> Loaded! (12 MS)
[LOADING] Navigator Manager -> Loaded! (118 MS)
[LOADING] Command Handler -> Loaded! (31 MS)
[LOADING] Permissions Manager -> Loaded! (101 MS)
[LOADING] ModTool Manager -> Loaded! (33 MS)
[LOADING] Achievement Manager -> Loaded! (94 MS)
[LOADING] WordFilter -> Loaded! (4 MS)
[LOADING] GameEnvironment -> Loaded!
[main] WARN io.netty.channel.DefaultChannelId - Failed to find a usable hardware address from the network interfaces; using random bytes: 34:63:66:d1:xx:xxx:xx:xx:xx
[LOADING] Started GameServer on 127.0.0.1:1996
[LOADING] Badge Imager -> Disabled! Please check your configuration!
[CAMERA] Attempting to connect to the Camera server.
[LOADING] Habbo Hotel Emulator has succesfully loaded.
[LOADING] You're running: Version: 1.8.0
[LOADING] System launched in: 6666.019814ms. Using: 6 threads!
[LOADING] Memory: 23/11MB
[DEBUG] Debugging Enabled!
[CAMERA] Connected to the Camera Server. Attempting to login...
[CAMERA] You don't have a Camera Subscription and therefor cannot use the camera!
[CAMERA] Please consider making a donation to keep this project going. The emulator can be used free of charge!
[CAMERA] A trial version is available for $2.5. A year subscription is only $10 and a permanent subscription is $25.
[CAMERA] By donating this subscription you support the development of the emulator you are using :)
[CAMERA] Visit http://arcturus.wf/mysubscriptions.php to buy your subscription!

                                 Please Consider getting a subscription. Regards: The General
</pre>

external was set to: ads.domain=Domain.de/public/SWF
SWF: http://arcturus.wf/mirrors/asmd_PRODUCTION-201611291003-338511768.swf

**Comment by thedevilsden** [comment]
Before doing this, I recommend a **fresh install** of the CMS.
Make sure that in the config file all urls are 100% working. I got stuck on a simple **/** in the furnidata link for a couple of hours before realizing how handshakes and typing mistakes can make you feel really stupid. 
If you are using **Notepad++**, I really encourage you to get a clean **external vars** and **external vars override** and make sure to replace any YOURIP or localhost you find; with the abovementioned text editor, it's really easy. Press **CTRL+F**, go to the Replace tab, put the text you wanna find in the upper textbox, and what to replace with in the bottom one, then press Replace all.
Ensure that the base url in both **external variables** and **external variables override** is correct; by meaning correct I mean that it points to the main swf folder, the one that contains Habbo.swf

**Comment by sant0ro** [comment]
Please use `<pre>` and not `´`

I don't know if the error is really on the client.
Open the `resources/views/habbo-client.blade.php` on line 9. And show me what it's on this line.

But the errors may also be `external_variables` or misconfiguration on the urls on the configuration files.

**Comment by sant0ro** [comment]
Closed, since no feedback from author was given.

**Comment by iPrinz96** [comment]
Console say: 
www.facebook.com/impression.php/f19ecba1aa7ab2/?lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
19:39:08.741 www.facebook.com/impression.php/f2334352e0eccb4/?lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

externals was correct..

**Comment by iPrinz96** [comment]
habbo.iprinz.de

**Comment by sant0ro** [comment]
I think the IP address it's wrong on your client.

![image](https://user-images.githubusercontent.com/12037269/28640454-1a46a59a-7222-11e7-821e-dcfb204a229d.png)
This shouldn't be 127.0.0.1

**Comment by iPrinz96** [comment]
That is Emulator settings? I have change it to my domain. But dont work..

**Comment by TheOmanNorge** [comment]
Your saying that you have Linux as server. 
Instead of having the domain, try using the IP in chocolatey.php check if your port is also 
correct. Is it 996 or 30000? 

Also longer up I can see this: 
"[LOADING] Started GameServer on 127.0.0.1:1996" 

Should be the IP of the Linux server, if your running the emulator there. 
Nobody of us can connect to 127.0.0.1

If you have Skype I'll be more than happy to help you fix the issue.

**Comment by sant0ro** [comment]
Exactly like @TheOmanNorge said.

**Comment by iPrinz96** [comment]
How i change it?

**Comment by iPrinz96** [comment]
Skype: iPrinz96

**Comment by TheOmanNorge** [comment]
I've added you.

**Comment by iPrinz96** [comment]
We have Change:
config.ini from Arcturus Emulator (127.0.0.1 to Server IP)
chochlatey.php (furnidata'         => 'http://domain.de/game/gamedata/furnidata.xml/'; to 'http://domain.de/game/gamedata/furnidata.xml';) Without "/"

**Comment by sant0ro** [comment]
So your issue it's fixed?
