### ISSUE TITLE
Problem when i try to connect or register

### ISSUE THREAD

**Issue by Atroxways** [sant0ro/chocolatey#259]
Hello, I want to clarify that I am French and that, therefore, my English is not nice.

The problem: I have a problem with Chocolatey CMS 3.0. 
I can not register and log in, and I would like to know where this problem may originate.

I use php version 7.1 and my domain (in https) is hosted by my plesk server.

Here is a picture (HD) of the alert that appears when I try to log in or register : 

http://i.imgur.com/HYcIKoQ.png

Here is the image (HD) of my developer console on google chrome:

http://i.imgur.com/4NsKKZv.png

And finally, here is the image (HD) of the page mentioned by the developer console :

http://i.imgur.com/7Kzfd03.png

If you can help me fix this problem I would really appreciate it.
Thank you for taking the time to read. Cordially.

**Comment by thedevilsden** [comment]
Try reinstalling the cms (wipe the htdocs folder and replace everything back from a fresh archive)
Download the binaries, and don't forget to migrate artisan
Also totally drop the database and do this thing: open with any text editor the .sql file, select all, copy, and paste it into Mysql query. I had this issue and I couldn't migrate some tables, and had the same unknown error at registration.

**Comment by sant0ro** [comment]
The last image it's because the `registration` page can only by accessed by the Angular (CMS Core).

I recommend you open the `network` tab (console tools) after opening the register page and try register and check which error appears.

This is a very weird error.

**Comment by lElectrico** [comment]
I have the same problem, I reinstalled everything and I still having it, also, when I try to install from console, it brings an error

  [Seld\JsonLint\ParsingException]
  "./composer.lock" does not contain valid JSON
  Parse error on line 1:
  git {    "_readme":
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by Brianelvio** [comment]
I am unfortunately experiencing the exact same issue. Using Winbox xampp php 7.1
Can't seem to find a clear log anywhere other than '500 Internal Server Error'

**Comment by sant0ro** [comment]
If this happens, it's because you doesn't downloaded the binaries branch.

Only the binaries branch comes with the `vendor` files from composer packages.

Test with this: https://github.com/sant0ro/chocolatey/archive/binaries.zip
