### ISSUE TITLE
No binaries for chocolatey 2.095

### ISSUE THREAD

**Issue by ghost** [sant0ro/chocolatey#26]
As above, there is no binaries.zip file for chocolatey 2.095.

**Comment by sant0ro** [comment]
The branch "binaries" actually are the latest binaries.

Just download last "Source Code".

Starting from version 2.095 only the binaries will be included on Releases, that will be the "Source Code" uri.

**Comment by hersentooped86** [comment]
Okay, thanks for the clarification!

By the way, for the latest release (2.095), files under the /vendor/ folders were not included in the Source Code zip file.

**Comment by sant0ro** [comment]
Weird. Because the "binaries" branch actually have the vendor files.

**Comment by hersentooped86** [comment]
Yeah, vendor files that are submodules won't be in those zip files.

Example:
- /vendor/rdehnhardt/lumen-maintenance-mode/
- /vendor/sofa/eloquence/
- /vendor/sofa/hookable/
- /vendor/vlucas/phpdotenv/

**Comment by sant0ro** [comment]
Thanks @ghost i noticed that the packages that were cloned, automatically were added as untracked submodules. 

Composer doesn't remove their .git folders, so i created a bash script to do this trick.
