### ISSUE TITLE
I have an error with composer installation

### ISSUE THREAD

**Issue by lElectrico** [sant0ro/chocolatey#263]
When I try to install with composer, it brings an error:

[Seld\JsonLint\ParsingException]
"./composer.lock" does not contain valid JSON
Parse error on line 1:
git { "_readme":
^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

**Comment by sant0ro** [comment]
Delete file composer.lock

**Comment by sant0ro** [comment]
Closing due lack of updates.
