### ISSUE TITLE
Client disconnect when you click catalog item

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#265]
I change my old cms to Chotolatey. After that my catalogue is buggy. When I click any items client will be disconnect me. Catalogue work good on old cms. So how I can fix that catalogue disconnect bug?

Sry for my bad english. btw, cms is nice :)
(You can ask if you need more information or some picks)

Here is it some information:
Ubuntu Server 16.04 "Xenial Xerus" LTS (64bits)
Apache2 version 2.4.18
PHP7
Postfix
Acrturus Emulator 1.8.0

**Comment by sant0ro** [comment]
Hi @T0niiiiii, I was in a party. Does your issue it's solved?

The catalogue thing doesn't make any sense....
