### ISSUE TITLE
Text display bug

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#266]
When I load chocolatey index on my android phone I just see only text like REGISTER_PROMPT

Sry for my bad english. If you need more information, you just need ask

**Comment by sant0ro** [comment]
Can you attach your lumen.log and screenshots please?

Read CONTRIBUTING.md for how you need create Issues.

**Comment by T0niiiiii** [comment]
Problem solved. My bad. Url was bad for some reasons..

**Comment by sant0ro** [comment]
Glad to see you solved your problem.
