### ISSUE TITLE
Mail configuration

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#267]
I read wiki article about this but I am still not sure how I can get this to work. I have linux server apache2, php7, mysql and postfix. I made single email send php script and that work. But postfix don't uses username or password so how I must configure things right? 

'enable' => true,
'driver' => 'smtp',
'host' => 'localhost',
'port' => 25,
'from' => [
        'address' => 'asiakaspalvelu@onnelahotelli.com',
        'name'    => 'Onnela Hotelli',
    ],
'username' => '',
'password' => '',

sry for bad english.

**Comment by sant0ro** [comment]
I recommend you use your Google e-mail or create a Gmail account for your Hotel. Configuring SMTP isn't something really easy.

Postfix isn't recommended for that.

Just use a simple smtp server. There are a lot available on the Internet.

Cheers

**Comment by T0niiiiii** [comment]
Okay, I try my hotel gmail, but still can't get working

'enable' => true,
'expire' => 2,
'driver' => 'smtp',
'host' => 'smtp.gmail.com',
'port' => 587,
'from' => [
        'address' => 'onnelahotelli@gmail.com',
        'name'    => 'Onnela Hotelli',
    ],
'username' => 'onnelahotelli@gmail.com',
'password' => 'Secret',

Can you told me what's wrong? I make sure password was right.

**Comment by T0niiiiii** [comment]
[2017-07-23 16:23:34] lumen.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. d80sm5996449wmh.46 - gsmtp
" in /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.0 Must ...', Array)
#1 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<onne...', Array, Array)
#2 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(346): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<onne...', Array)
#3 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(416): Swift_Transport_EsmtpTransport->_doMailFromCommand('onnelahotelli@g...')
#4 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(443): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'onnelahotelli@g...', Array, Array)
#5 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'onnelahotelli@g...', Array, Array)
#6 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/onnelahotelli/public_html/vendor/illuminate/mail/Mailer.php(440): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/onnelahotelli/public_html/vendor/illuminate/mail/Mailer.php(211): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/onnelahotelli/public_html/vendor/illuminate/support/Facades/Facade.php(221): Illuminate\Mail\Mailer->send('habbo-web-mail....', Array, Object(Closure))
#10 /var/www/onnelahotelli/public_html/app/Helpers/Mail.php(34): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#11 /var/www/onnelahotelli/public_html/vendor/illuminate/support/Facades/Facade.php(221): App\Helpers\Mail->send(Array)
#12 /var/www/onnelahotelli/public_html/app/Http/Controllers/AccountController.php(147): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#13 /var/www/onnelahotelli/public_html/app/Http/Controllers/LoginController.php(81): App\Http\Controllers\AccountController->createUser(Object(Illuminate\Http\Request), Array, true)
#14 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#15 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#16 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#18 /var/www/onnelahotelli/public_html/vendor/illuminate/container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#19 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#20 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#21 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#22 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#23 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#24 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /var/www/onnelahotelli/public_html/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#33 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#34 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/onnelahotelli/public_html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#43 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#44 /var/www/onnelahotelli/public_html/index.php(26): Laravel\Lumen\Application->run()
#45 {main}  

there is my lumen.log

**Comment by sant0ro** [comment]
Working around the bug. Next commit will have it fixed.

**Comment by T0niiiiii** [comment]
Okay, thanks! Nice work btw. Keep that going.

**Comment by sant0ro** [comment]
I updated Chocolatey. Download a ZIP of latest Binaries branch.
