### ISSUE TITLE
Recaptcha bug on register

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#268]
Some screens:
http://imgur.com/a/tN7cq
http://imgur.com/a/c81s5

This recaptcha worked yesterday, but now isn't work. I just wonder what happen? and can I disable that? I can't find anything on lumen.log. I think I maybe just wanna disable this google feature. It's bad just like Ad Sense.

**Comment by sant0ro** [comment]
The problem isn't the captcha. Check the red error above. The error is in your server.

You enabled e-mail, but your mail isn't working. Because that register cannot be concluded. That's obvious.

I'm fixing the mail system to be compatible with TLS variants. Described on Issue #267

**Comment by T0niiiiii** [comment]
So this explain why my postfix server can't send it too? It uses tls like gmail..

**Comment by sant0ro** [comment]
Nope.

**Comment by sant0ro** [comment]
I updated Chocolatey. Download a ZIP of latest Binaries branch.
