### ISSUE TITLE
Add support for topsite voting

### ISSUE THREAD

**Issue by scottstamp** [sant0ro/chocolatey#27]
Wondering if y'all could add some sort of topsite voting system in the CMS? Maybe an option to force voting the first time you login that day?

**Comment by sant0ro** [comment]
Okay, adding it on the Task List.

**Comment by sant0ro** [comment]
@scottstamp can give example of how TopVote works?

**Comment by scottstamp** [comment]
Sure, just take a look at Habboon (boon.pw), when you register it forwards you to the findretros.com topsite voting link and you have to vote before it returns you to the client. Which while super annoying, seems like the best way to rack up votes.

**Comment by sant0ro** [comment]
Coded it on last version.

Give a try.
