### ISSUE TITLE
Suggestion - Referral

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#270]
Hi, could Chocolatey got a Referral system with link etc?

**Comment by T0niiiiii** [comment]
It's stupid old school thing. plz no

**Comment by sant0ro** [comment]
@Iluminatos the idea behind Chocolatey it's being a replica of Habbo.

The following things I will add on Chocolatey, since many users asked:

1. Staff Page
2. RCON Alert System

If more people ask about the referral system, I will add it. Thanks.
