### ISSUE TITLE
PHP Artian migrate issue

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#271]
Getting this when trying to migrate? (CLEAN Arcturus database)
https://gyazo.com/7747dffdba47c378a2160dbec26a0504?token=3901b7a6c7ade6b36d6b7233983bba26

**Comment by Iluminatos** [comment]
@s150217754 @sant0ro

**Comment by sant0ro** [comment]
You're not using latest version. Try to download the binaries branch as a zip.
