### ISSUE TITLE
mail sending isn't working

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#272]
I tried postfix and gmail, but nope. It's not working.  Santoro "fix" not actually fixed anything.

Plz just use mail() function. It's work better than this.

**Comment by T0niiiiii** [comment]
[2017-07-29 14:46:32] lumen.ERROR: Swift_TransportException: Expected response code 250 but got code "530", with message "530 5.7.0 Must issue a STARTTLS command first. t2sm5385663wmt.23 - gsmtp
" in /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('530 5.7.0 Must ...', Array)
#1 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('MAIL FROM:<onne...', Array, Array)
#2 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(346): Swift_Transport_EsmtpTransport->executeCommand('MAIL FROM:<onne...', Array)
#3 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(416): Swift_Transport_EsmtpTransport->_doMailFromCommand('onnelahotelli@g...')
#4 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(443): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'onnelahotelli@g...', Array, Array)
#5 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'onnelahotelli@g...', Array, Array)
#6 /var/www/onnelahotelli/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/onnelahotelli/public_html/vendor/illuminate/mail/Mailer.php(440): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/onnelahotelli/public_html/vendor/illuminate/mail/Mailer.php(211): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/onnelahotelli/public_html/vendor/illuminate/support/Facades/Facade.php(221): Illuminate\Mail\Mailer->send('habbo-web-mail....', Array, Object(Closure))
#10 /var/www/onnelahotelli/public_html/app/Helpers/Mail.php(34): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#11 /var/www/onnelahotelli/public_html/vendor/illuminate/support/Facades/Facade.php(221): App\Helpers\Mail->send(Array)
#12 /var/www/onnelahotelli/public_html/app/Http/Controllers/AccountController.php(214): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#13 [internal function]: App\Http\Controllers\AccountController->verifyAccount(Object(Illuminate\Http\Request))
#14 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/onnelahotelli/public_html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#17 /var/www/onnelahotelli/public_html/vendor/illuminate/container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#18 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#19 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#20 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'verifyAccount', Array)
#21 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#22 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#23 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/onnelahotelli/public_html/app/Http/Middleware/Authenticate.php(50): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /var/www/onnelahotelli/public_html/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#36 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#37 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /var/www/onnelahotelli/public_html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /var/www/onnelahotelli/public_html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#46 /var/www/onnelahotelli/public_html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#47 /var/www/onnelahotelli/public_html/index.php(26): Laravel\Lumen\Application->run()
#48 {main}

**Comment by sant0ro** [comment]
Sorry, the problem isn't on Chocolatey. tested right now.

I need to say, but you're a newbie, and **newbies** have the costume to say that the error comes from the developer.

First at all, ensure that your G-MAIL account support "Less secure apps" (https://support.google.com/accounts/answer/6010255?hl=pt-BR)

Also your postfix wont work, because POSTFIX isn't a mail server that you just install and _voilá done_. Configuring a mail server it's something hard, and not easy, my dear.

Postfix won't work with TLS or SSL by default. And wont work by default at all without configuring extended settings.

So please, BEFORE you point the error on Chocolatey. See yourself the error log on `lumen.log`

Please try to configure again. And check if all configurations are right.

**Comment by T0niiiiii** [comment]
It's not either Gmail or Postfix problem. Postfix and gmail work good with php mail() function (tested).
I check google "less secure apps" too

**Comment by sant0ro** [comment]
Strange. Because with me works flawlessly.

**Comment by sant0ro** [comment]
@T0niiiiii with me working 100% with gmail

![image](https://user-images.githubusercontent.com/12037269/28999193-48e20918-7a14-11e7-9639-e2b931c8205d.png)
