### ISSUE TITLE
How to add vip on shop? [helpwanted]

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#273]
So, how I can add "vip" rank on shop? Is there any tutorial for that?

**Comment by T0niiiiii** [comment]
Oh, and how I can delete "bete release" box?

**Comment by TheOmanNorge** [comment]
You should consider upgrading to the latest Chocolatey. 
It has the Beta Release box gone/deleted.

**Comment by T0niiiiii** [comment]
Give link, I download latest binary about 2-3 days ago and still have beta box

**Comment by TheOmanNorge** [comment]
That is strange, since it's removed from from what I can see. 
And I'm using the latest one here http://nightbox.cf and as you can see it's removed. 

Try this https://github.com/sant0ro/chocolatey/archive/master.zip

https://github.com/sant0ro/chocolatey/issues/258
 - Remove the Beta Overlay on Home Page ✔

**Comment by T0niiiiii** [comment]
Thx

**Comment by TheOmanNorge** [comment]
No problem 👍

**Comment by T0niiiiii** [comment]
Nice, now I have 500 error page

**Comment by T0niiiiii** [comment]
I migrate and install composer, and I take config from older binaries. Not work. WTF

**Comment by T0niiiiii** [comment]
Error is now gone, but I still have that fucking beta box D: https://onnelahotelli.com/

**Comment by sant0ro** [comment]
@TheOmanNorge the correct link is https://github.com/sant0ro/chocolatey/archive/binaries.zip

Since master doesn't come with the vendor files.

**Comment by TheOmanNorge** [comment]
Thanks for letting me know @sant0ro 
Was not sure what the difference was, but now I know that. 

I will not do that mistake again.

**Comment by T0niiiiii** [comment]
But binaries have beta release box :/
