### ISSUE TITLE
Suggestion - Alert sending page

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#274]
Can you make alert sending on page using rcon? 

Example: rank 2 (vip rank) can send :ha on page. But we don't want spam so user can send only 1 :ha in hour? And staff can unlimited...

Sry for bad english.

**Comment by sant0ro** [comment]
The intention of Chocolatey it's being a replica of HabboCMS. But I will give a look with Wesley (The General) if it's possible to add this.

**Comment by sant0ro** [comment]
Sorry. Wesley said that this idea isn't good. Since people that are on the CMS are actually logged on the Hotel.

And implement this would be hard.

Closing.

**Comment by T0niiiiii** [comment]
https://bitbucket.org/Wesley12312/arcturus/src/af8ff5813920639069b26cb58450afbaca7276e7/examples/RCON.php?at=master&fileviewer=file-view-default
