### ISSUE TITLE
PHP Artisan Error

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#275]
Posted this before but got closed, im not using a old update it is **# 3000.D**

Getting this when trying to migrate? (CLEAN Arcturus database)
https://gyazo.com/7747dffdba47c378a2160dbec26a0504?token=3901b7a6c7ade6b36d6b7233983bba26

@sant0ro @s150217754

**Comment by sant0ro** [comment]
You aren't using latest version. Latest version isn't available through the "Releases Page"

**Comment by Iluminatos** [comment]
ok got latest update but not php artisan command wont work? xD
