### ISSUE TITLE
Register Issue

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#279]
Getting this even when i confirm that im not a robot?
https://gyazo.com/448acda3c43a3f5f548beaaabd5eb41a

**Comment by TheOmanNorge** [comment]
Just to confirm, you have been at Google and got a site key for your site, and you saved the site key inside Chocolatey.php?

**Comment by Iluminatos** [comment]
Yes Recaptcha is correct and all working. :)

**Comment by Iluminatos** [comment]
@TheOmanNorge

**Comment by TheOmanNorge** [comment]
Ok. Are you using on a public domain or on your local pc with localhost as website address?

**Comment by Iluminatos** [comment]
Public

**Comment by TheOmanNorge** [comment]
Alright, I've never had issues like that before as It has been working all the time for me.
Sad your having problems right now. Let's hope Santoro can help you better or someone else. =)

**Comment by Iluminatos** [comment]
Yeah hope so. @sant0ro @s150217754

**Comment by Iluminatos** [comment]
solved. 
How to fix this issue: Reimport the Arcturus database and redo "php artisan migrate"
