### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by byOsorio** [sant0ro/chocolatey#28]
I have this problem when I install the CMS. I've done all perfect. Some vendor files missing. Here you have an screenshot:
![f025e2536bc8438098d388a996ac2e33](https://cloud.githubusercontent.com/assets/25869844/23096218/ec82695e-f617-11e6-9725-acfafa249df8.png)

[http://image.prntscr.com/image/f025e2536bc8438098d388a996ac2e33.png](url)

**Comment by sant0ro** [comment]
Fixed it.

Sorry was a git "submodules" fault.
