### ISSUE TITLE
How to add vip to shop?

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#280]
Is paypal payment supported yet? I just wanna add vip on shop, but not sure how to do it.

**Comment by Iluminatos** [comment]
**Following** this ticket.
Good point @T0niiiiii

**Comment by sant0ro** [comment]
Hi @T0niiiiii in thesis paypal transaction would work. But I never tested it before.

I will give a deeper look at this.

**Comment by Iluminatos** [comment]
@sant0ro Updates on this?

**Comment by sant0ro** [comment]
Nope.

**Comment by sant0ro** [comment]
Without time to test Paypal integration. It's something really complex.

**Comment by ovflowd** [comment]
Adding to #258
