### ISSUE TITLE
External Variables?

### ISSUE THREAD

**Issue by Iluminatos** [sant0ro/chocolatey#281]
What is wrong everything is linked correctly but client wont work.
Example: http://178.32.181.199/public/swf/flash_client_error (Doesnt work?)
@s150217754 @sant0ro

**Comment by TheOmanNorge** [comment]
What kind of emulator are you using? 
Could you post your chocolatey.php file? Not all just the SWF Settings.. 

Are you using the latest version of Chocolatey, could not see nux rooms spawning in first time. 
Is that disabled? 

Also your external_variables.txt looked kinda strange. Where did you download the swf pack?

**Comment by Iluminatos** [comment]
'game' => [
        'gordon'   => 'http://178.32.181.199/public/swf/gordon/PRODUCTION-201611291003-338511768/',
        'flash'    => 'http://178.32.181.199/public/swf/gordon/PRODUCTION-201611291003-338511768/Habbo.swf',
        'gamedata' => [
            'figuredata'        => 'http://178.32.181.199/public/swf/gamedata/figuredata.xml',
            'furnidata'         => 'http://178.32.181.199/public/swf/gamedata/furnidata.xml/',
            'productdata'       => 'http://178.32.181.199/public/swf/gamedata/productdata.txt',
            'variables'         => 'http://178.32.181.199/public/swf/gamedata/external_variables.txt',
            'texts'             => 'http://178.32.181.199/public/swf/gamedata/external_flash_texts.txt',
            'overrideVariables' => 'http://178.32.181.199/public/swf/override/external_override_variables.txt',
            'overrideTexts'     => 'http://178.32.181.199/public/swf/gamedata/override/external_flash_override_texts.txt',
        ],

**Comment by Iluminatos** [comment]
Im using Arcturus 1.8.0 EMulator.

Yes im using latest Version.

**Comment by Iluminatos** [comment]
SWF Pack is from Retroripper.

**Comment by TheOmanNorge** [comment]
First of all remove the / in end of the Furnidata line. 
'furnidata' => 'http://178.32.181.199/public/swf/gamedata/furnidata.xml -->  /',  <--

Are you sure this is correct path? gordon/PRODUCTION-201611291003-338511768/
Can't access the Habbo.swf file.

**Comment by sant0ro** [comment]
I'm really glad that people from the community are helping each others. Thanks @TheOmanNorge :)

A just little note: This CMS was only designed for Arcturus. But I already saw people making it work with Plus just using normally (but some functionalities doesn't will work).

**Comment by Iluminatos** [comment]
@TheOmanNorge You got skype / discord? ;D

**Comment by Iluminatos** [comment]
@sant0ro Yeah, saw that aswell haha.

**Comment by TheOmanNorge** [comment]
No problem, I like helping people @sant0ro =) 

Skype: daniel.andre.lian

**Comment by Iluminatos** [comment]
@TheOmanNorge Thanks 👍 

Now updating this ticket.
This is how it looks when i try to enter the client.
Every link in chocolatey configs work.
External variables work.

GIF: https://gyazo.com/3284b49e1de931492bd343adf6c052fe

**Comment by Iluminatos** [comment]
@s150217754 @sant0ro

**Comment by TheOmanNorge** [comment]
If you have Teamviewer I will fix your issue in a heartbeat. I can give you my swf pack to see if that is fixing the issue you have if that is the problem.

I will be home in around 1 hour, at work right now.

**Comment by Iluminatos** [comment]
@TheOmanNorge You can just connect to my VPS, we take the details to the VPS on Skype. Thanks for helping <3

**Comment by TheOmanNorge** [comment]
Sure lets do that. 
No problem :)

**Comment by Iluminatos** [comment]
Message me on Skype when ur home!
