### ISSUE TITLE
Staff Page and about updates

### ISSUE THREAD

**Issue by Kadoxyx** [sant0ro/chocolatey#282]
Hey!
I need to know. The staff page: why she is empty? i have search around but how we add ranks and show the users? I think i don't know how to update.

I'm manually changing all the files from the new folder (except the chocolatey.php). Will you make an updater? We need to erase all the CMS and extract the new? but we need to re-do the configuration? I'm not sure! I don't want to make something wrong, i already have more than 3K account with this CMS on my hotel. Thanks. Good Job :)

**Comment by sant0ro** [comment]
Hi!

If you changed nothing on any fiiles of the following folders: `resources`, `app` you can install it without problems.

Chocolatey automatically updates your old table definitions with the new ones, without deleting content (without data loss). Just run `php artisan migrate` and it will update your definitions.

The Staff page will be empty if you don't have any user with rank >= 4.

Can you attach a screenshot of your staff page? Maybe you will need to clear you cache.

Regards,

**Comment by Kadoxyx** [comment]
Perfect! Thank you for your FAST reply! :)

Le 1 août 2017 2:36 PM, "Claudio Santoro" <notifications@github.com> a
écrit :

**Comment by T0niiiiii** [comment]
Where I should see staff page in category and what is url? I think I don't have staff page

**Comment by Kadoxyx** [comment]
Everythings OK. But we have many users with rank >+4 and their not appear on the page.
you can test by yourself if you need: https://habbo.quebec
![capture](https://user-images.githubusercontent.com/30634827/28861570-7d7e0c5e-772f-11e7-88a6-4c0b7bbef347.PNG)

**Comment by sant0ro** [comment]
@Kadoxyx I will give a deeper look.

**Comment by sant0ro** [comment]
![image](https://user-images.githubusercontent.com/12037269/28999002-56db7fb8-7a0f-11e7-993c-90466af12062.png)

Something not right.

**Comment by sant0ro** [comment]
![image](https://user-images.githubusercontent.com/12037269/28999017-a5a450e8-7a0f-11e7-98ce-d59c484c7ea3.png)

Working here.

**Comment by s150217754** [comment]
No response from OP - Closing this.
