### ISSUE TITLE
Max_users and MAX_IP

### ISSUE THREAD

**Issue by Kadoxyx** [sant0ro/chocolatey#284]
Hey! This is very urgent for a community like mine.
We are an hotel where the trade function and casino are priority, everyone start with 5k creds.
But for now, everyone can create up to 50 avatars and can register unlimited time on the register page with fake email. Even if i edit the MAX_AVATARS in the script.js thats not working.

For the moment, we give the bonus credits manually.. but thats not nice haha. You think you will add this features? 
And where we can give donations? Hmm!  Thank you!

**Comment by sant0ro** [comment]
Sorry, what you mean with bonus credits? You mean the vouchers?

Not only editing MAX_AVATARS will work, need change in the Chocolatey CMS too.

Okay, adding as Issue IP validation. (Habbo doesn't do IP validation..)

**Comment by Kadoxyx** [comment]
Yes i know Habbo dont do that.. but all CMS for Habbo retros have this.. :(
thank you haha! and the "bonus" no, i mean the Start credits when you
register. It would be cool if people receive it only after they valid the
email adress but thats not much important hahaha! On my hotel the economy
is really important, the credits too. But since i have migrate to
Chocolatey people can create unlimited account and transfer all the credits
they want. Its just a suggestion.. :$ thank you.

Le 3 août 2017 11:53 AM, "Claudio Santoro" <notifications@github.com> a
écrit :

**Comment by sant0ro** [comment]
I see. I will give a look on it :)

**Comment by sant0ro** [comment]
Closing. Referred on other Issue

**Comment by sant0ro** [comment]
Reopened. Starting to code this now.

**Comment by sant0ro** [comment]
Fixed.
