### ISSUE TITLE
Error on Captcha?

### ISSUE THREAD

**Issue by NoNeed2** [sant0ro/chocolatey#285]
How do i fix this?
It's the correct key n etc..

https://gyazo.com/dc505649b2b57656c4b92e699b48f0db

**Comment by sant0ro** [comment]
How to fix what?

**Comment by NoNeed2** [comment]
my bad
https://gyazo.com/c46257b73afeee37b856c060f03a3592

**Comment by sant0ro** [comment]
This error may be many things. Read this: https://github.com/sant0ro/chocolatey/blob/master/ISSUES.md

**Comment by NoNeed2** [comment]
I tried this in console: C:\Users\Administrator>php artisan migrate
Could not open input file: artisan

Information about os etc
https://gyazo.com/71296b07f970b9a8db7672b39ddb4621

XAMPP v.3.2.2
Server version: Apache/2.4.26 (Win32)
Apache Lounge VC14 Server built:   Jun 15 2017 12:39:41

**Comment by sant0ro** [comment]
Guy you need read PROPERLY the Tutorial.

First you don't must open as administrador.
You need open the Command Prompt in the folder of where you downloaded Chocolatey. 
The artisan file only exists inside on the Chocolatey folder.

Just please read the errors, for good sake.

;)

**Comment by NoNeed2** [comment]
Thanks for the help, And i didnt open the cmd as admin at all.
At https://github.com/sant0ro/chocolatey/wiki/Installing-Chocolatey
it didnt say to open the cmd in the folder at all so how should i know? 

So chill wtf, not my fault the tutorial at that page didnt point it out lmao

**Comment by sant0ro** [comment]
Keep calm. I'm calm. Just saying think a little about it :) Also many people already created an issue asking the same question.

Just read the closed issues hehe.

Good luck.

**Comment by NoNeed2** [comment]
It wasnt suppose to be a hate comment btw xD
Keep up the hard work :)

**Comment by sant0ro** [comment]
@NoNeed2 did you solved the problem? :)
