### ISSUE TITLE
Error in captcha when registering

### ISSUE THREAD

**Issue by rabeloarthur** [sant0ro/chocolatey#286]
When I'm going to create a new user I passed on captcha, but it gives me an error asking me to prove that I'm not a robot
[http://prntscr.com/g4j177](http://prntscr.com/g4j177)
[http://prntscr.com/g4j1py](http://prntscr.com/g4j1py)

Sorry for english, i'm brazilian

**Comment by sant0ro** [comment]
Opa, o que aconteceu quando você executou "php artisan migrate" ?

English: What happened when you executed the command "php artisan migrate"?

For the OP: "Chocolatey também é disponível em português, basta mudar o idioma nas configurações. (Apenas a linguagem do Angular em português é suportada por enquanto. O conteúdo das páginas só tem em inglês, francês e holandês)"

**Comment by rabeloarthur** [comment]
[http://imgur.com/a/2NDee](http://imgur.com/a/2NDee) -> Execution of "php artisan migrate"

**Comment by rabeloarthur** [comment]
I was able to solve it, thank you.

**### What was the problem?**
The problem is not in the captcha.
I had enabled the email, but this one is not working. [#267](https://github.com/sant0ro/chocolatey/issues/267)

**Comment by sant0ro** [comment]
@rabeloarthur e-mail need to be configured in order to work. Only enable it if you're sure that you configured everything right. I will code something that will advise if mail isn't working.

**Comment by TheOmanNorge** [comment]
Good, was about to comment exacly the same asking if you had enabled mail. 
I had the same problem, but found the issue and solved it. 

Good that you have fixed it! 👍

**Comment by sant0ro** [comment]
Okay, I will give a deeper check now on mailing system. Keep tunned.

**Comment by sant0ro** [comment]
Closing since Issue was fixed. I will create another Issue for the Mail bug.

**Comment by sant0ro** [comment]
Tutorial for sending e-mails: https://github.com/sant0ro/chocolatey/wiki/Sending-E-Mail-with-Chocolatey

**Comment by sant0ro** [comment]
![image](https://user-images.githubusercontent.com/12037269/28999182-0c90ffe6-7a14-11e7-8196-1e9fd970dfc8.png)

Worked with me. 100% using GMAIL.
