### ISSUE TITLE
[Poll] New features for Chocolatey

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#287]
Hello, this **Issue** it's about to discuss new Feature Requests created by the community.

You can comment to contribute what you think about certain Feature request, or to create a new Feature Request. In order to **VOTE** you need put an Emoji on this comment.

**Feature Requests**
- Limit User Registration by IP Address and Proxy IP Address. **vote with: 🦁** #284 **CODED** :)
- Referral System **vote with: 🐰**  #283 
- Find Retros System **vote with 🐯** #341 

**Help us**
- If you like Chocolatey and what I do, follow me on GitHub 😃 
- Give an upvote on this comment.
- Star the repository 
![image](https://user-images.githubusercontent.com/12037269/28999081-373904d0-7a11-11e7-8d19-ca4a84f8bfab.png)

**Comment by iPrinz96** [comment]
Omg. You are the best *.*
You can send me your paypal adress for a small gift :P

When come the expresso hk? :3

**Comment by sant0ro** [comment]
Hi @iPrinz96 I will code Espresso as soon as possible. Probably tomorrow. Send me a PM on RaGEZONE. thanks for the support.

**Comment by TheOmanNorge** [comment]
1+ 🦁 
1+ 🐰

**Comment by vcoc** [comment]
1+ 🦁
1+ 🐰

**Comment by Kadoxyx** [comment]
1+ 🦁
1+ 🐰

**Comment by odrik** [comment]
1+ 🐰

**Comment by sant0ro** [comment]
Hey everyone. I want some help from everyone here. I see that the Staff page isn't really pretty. Can anyone here give me some tips?

Also how everyone here want to be coded the features of here?
Just Referral system needed now, how everyone here want the referral system to be?

**Comment by AntonSandin** [comment]
**Referral system:**
Every user has a _/username_ link for their friends to use. When used you recieve diamonds / credits. 
When register the friend will use the register link example: _habbo.com/register/santoro.

**Maybe?**

**Comment by sant0ro** [comment]
Added Referral System as suggestion by @AntonSandin and FindRetros by @Alex-Habbz

**Comment by iPrinz96** [comment]
How work the Referral system?

**Comment by ovflowd** [comment]
I didn't coded they, I just said that added they on the planned list.

I will code all the bug fixes and updates on this month, just after my semester ends 😄

**Comment by iPrinz96** [comment]
Okay. Have good luck :)

**Comment by ovflowd** [comment]
Poll ended.

**Comment by Hyvion** [comment]
If I can contribute something to improve Chocolatey, it would be some indicator of online users up on the right side would be fine. It would be something like this:

![screenshot_3](https://user-images.githubusercontent.com/35015483/34756358-ac400264-f5a0-11e7-8354-a1e9df319287.png)
It's just an idea

PD: Sorry for my English I'm Spanish :)
