### ISSUE TITLE
'Beta Release box' Translation

### ISSUE THREAD

**Issue by GahviBuru** [sant0ro/chocolatey#293]
Hi! Im looking and looking but I cannot find part where I can translate the top infobox:
![nayttokuva 2017-08-12 kello 11 02 26](https://user-images.githubusercontent.com/30950421/29239358-9b38d6e2-7f55-11e7-8fd8-51fd088b1e05.png)

Any idea where I can find this one?

Thanks for advance!

**Comment by sant0ro** [comment]
This box doesn't exists anymore on the newest releases. Please download latest release from Chocolatey,

**Comment by GahviBuru** [comment]
Could the code for that be found in later versions if we have older one?

**Comment by sant0ro** [comment]
Nope. This box was removed.
