### ISSUE TITLE
Suggestion:  Be able to choose the type of connection

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#294]
Hello,

 I propose to be able to choose the type of connection

1. First type is the connection with email and password as now
2. Second type is login with username and password (This is simpler for players because they tend to put false emails and so has forgotten them and can no longer connect)

Thank you

**Comment by PunchoDelta** [comment]
Where can we change this setting? In which file?

**Comment by sant0ro** [comment]
What you mean with change type of connection?

You mean user login? Like in Habbo, you can't only login by e-mail. Because Chocolatey also have "HabboID".

Closing Issue.
