### ISSUE TITLE
Problem with shop

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#296]
Hello, 

How do I run the shop with the Paypal payment method?

Thank

**Comment by sant0ro** [comment]
I already don't know if PayPal works with the Shop System. As I said in before issues I need to create a test and check it would work.

**Comment by PunchoDelta** [comment]
And what does it work and especially how to activate the store?

**Comment by sant0ro** [comment]
In thesis: Anything, but I really didn't tested yet the shop system with valid things. The customization of the store it's directly on the Database. And you can customize it totally. But isn't recommended for newbies. Since it's an advanced feature and I didn't documented all of it yet.
