### ISSUE TITLE
Install on WebServer

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#297]
Hello.
I will buy a WebServer only for CMS.
Is it possible to install the Chocolatey cms on a WebServer.
I think the Problem is: php artisan migrate.

Sorry for my bad English..

**Comment by TheOmanNorge** [comment]
php artisan migrate works fine if you have installed Composer. 

Just make sure.
1. Your in the right directory when lunching the command 
2. If you know that your in that directory and still is not working try using cmd: "composer install"

I don't really see the issue if you have configured the webserver correctly with all the requirements installed. Never used IIS or xampp for Windows as webserver, so don't know myself.

**Comment by sant0ro** [comment]
It's recommended run the php artisan command first on your PC. After that just upload the database to your webserver.

Artisan just migrates the database. So you can run it from your PC. Without problems.

**Comment by iPrinz96** [comment]
Okay. Thanks
