### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by GahviBuru** [sant0ro/chocolatey#298]
Where I could find the register page code to translate it, when It goes to client and have to choose name and clothing?

**Comment by sant0ro** [comment]
It's inside the .json `resources/views/habbo-web-10ln`

**Comment by GahviBuru** [comment]
There is no such file..

![nayttokuva 2017-08-13 kello 23 38 06](https://user-images.githubusercontent.com/30950421/29253252-8282beac-8080-11e7-8c24-5c5f51025648.png)

**Comment by sant0ro** [comment]
They are jSON files. Just see the content of those files.

**Comment by GahviBuru** [comment]
God this is getting so frustrating. We are 2 looking and nothing to be found of any of those files.

**Comment by TheOmanNorge** [comment]
This is what I found inside the Habbo.swf file.
I'm no decoder or swf expert. 

And when It comes to the Habbo.swf I can only change the image and never done anything besides that on the Habbo.swf file😅 

If this is something that can be changed in the Chocolatey CMS, and if @sant0ro has hidden it very good please tell me.

![actionscript](https://user-images.githubusercontent.com/15328445/29254141-39d50be2-808f-11e7-9e88-e0cfa6a39d79.png)

![habboswf](https://user-images.githubusercontent.com/15328445/29254125-bb8186da-808e-11e7-9348-027fc1d18067.png)

I tried to change the text, but failed. Might be because I'm a noob at that or it is simply protected I dont know. Wesley I'm pretty sure knows, but I dont have in the contacts so can't ask. 

Please try yourself and tell if it can be edited. 👍

**Comment by s150217754** [comment]
@TheOmanNorge is right. I am pretty sure this is not hard coded and can be overrided via variables.

The said file can be found at:

`/resources/views/habbo-web-pages/habbo-client.blade.php`

**Comment by GahviBuru** [comment]
Thanks we found the register texts :) 
Now Im looking for those time stamps for news.. 
![nayttokuva 2017-08-14 kello 14 03 42](https://user-images.githubusercontent.com/30950421/29269307-6b8e08c2-80f9-11e7-80c8-3132a7298dce.png)
Where that can be changed? All the months are translated already from resources/views/habbo-web-10ln blade and still those stays.

**Comment by sant0ro** [comment]
Since Chocolatey doesn't provide yet a Housekeeping, article are created directly upon the Database. Just insert a UNIX Timestamp (http://www.timestampgenerator.com) and put it on the table.

I'm going to code espresso son as possible.

**Comment by T0niiiiii** [comment]
http://imgur.com/a/2LzBF Yes, we found. 

resources/views/habbo-web-pages/habbo-client.blade.php you can change those text

**Comment by s150217754** [comment]
@GahviBuru To translate the Months (e.g. August to your language), go to:

**Open the following files:**
`/public/habbo-web/vendor.js`
`/public/habbo-web/vendor.min.js`

[Beautify](http://jsbeautifier.org/) the files for ease of editing.

**Go to Line 16482 after Beautify-ing, or search the following and edit accordingly:**
```
            e.value("$locale", {
                DATETIME_FORMATS: {
                    AMPMS: ["AM", "PM"],
                    DAY: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
                    ERANAMES: ["Before Christ", "Anno Domini"],
                    ERAS: ["BC", "AD"],
                    FIRSTDAYOFWEEK: 6,
                    MONTH: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
                    SHORTDAY: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
                    SHORTMONTH: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                    STANDALONEMONTH: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
                    WEEKENDRANGE: [5, 6],
                    fullDate: "EEEE, MMMM d, y",
                    longDate: "MMMM d, y",
                    medium: "MMM d, y h:mm:ss a",
                    mediumDate: "MMM d, y",
                    mediumTime: "h:mm:ss a",
                    "short": "M/d/yy h:mm a",
                    shortDate: "M/d/yy",
                    shortTime: "h:mm a"
                },
                NUMBER_FORMATS: {
                    CURRENCY_SYM: "$",
                    DECIMAL_SEP: ".",
                    GROUP_SEP: ",",
                    PATTERNS: [{
                        gSize: 3,
                        lgSize: 3,
                        maxFrac: 3,
                        minFrac: 0,
                        minInt: 1,
                        negPre: "-",
                        negSuf: "",
                        posPre: "",
                        posSuf: ""
                    }, {
                        gSize: 3,
                        lgSize: 3,
                        maxFrac: 2,
                        minFrac: 2,
                        minInt: 1,
                        negPre: "-Â¤",
                        negSuf: "",
                        posPre: "Â¤",
                        posSuf: ""
                    }]
                },
                id: "en-us",
                localeID: "en_US",
                pluralCat: function(e, t) {
                    var i = 0 | e,
                        o = n(e, t);
                    return 1 == i && 0 == o.v ? r.ONE : r.OTHER
                }
            })
```

[Minify](http://www.minifier.org/) the edited codes and save accordingly.

**Comment by s150217754** [comment]
@GahviBuru Please close this if you have resolved the issue. We will be closing it within a couple of hours due to non-response.
