### ISSUE TITLE
Advice for web hosting

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#299]
Hello,

Do you know a web host so that I can host Chocoley? Because now it is hosted on my VPS but it is getting DDOS all the time

Thank you

**Comment by sant0ro** [comment]
Any web host with php 7.0 support in theory would work.

You can also use Microsoft IIS server on your VPS, it's better for DDoS'ing. Also you can download DDoS firewalls.

**Comment by T0niiiiii** [comment]
Also you can buy https://www.ovh.com servers or https://www.soyoustart.com/. They have pretty good ddoss protection and not cheapest host. But if you buy ovh servers I recommed u use cloudflare cdn / proxy. If u use cloudflare proxy don't tell real ip to anyone. Maybe good idea configure virtualhost good. I recommed use linux with arcturus and chocolatey. 

Me and Gahviburu have dedicated server with udp firewall, cloudflare and 500mbit connection. You can test it https://onnelahotelli.com/. Language it's finnish

**Comment by PunchoDelta** [comment]
Do you have a server at OVH? Me too but under Windows 2008 R2 and my site works on it

**Comment by s150217754** [comment]
To be honest, the main thing you will need to do is:

1. **Concealing your True IP** - DDoS cannot take place if they do not know your True IP address. You can do this by using a Proxy Service or CDN Service (like Cloudflare, Incapsula, etc.)
2. **DDoS Mitigation Service** - Find a host that provides DDoS Protection. Your host will be responsible in blocking the attackers IP that are attempting to flood/DDoS your site. Not all hosts are willing to accept client's site that are being DDoSed frequently since it is labour intensive to manage. There is no 100% solution to this.

**Comment by PunchoDelta** [comment]
I use XAMPP on windows and I protect myself with wail2ban but it does not work. So I think go acehetr a shared hosting at OVH with a database that allows external connections to be able to communicate with the emulator that is on the server

**Comment by sant0ro** [comment]
Cloudflare it's a really good suggestion. Hiding your IP address it's important.

Also don't use XAMPP it's easy to put it down. Web hosting it's also a good suggestion if they have native Dados protection.

**Comment by T0niiiiii** [comment]
I always get 3-20Gbit massive ddoss attack and ovh server not go down. Ovh mitigation is really good.

Yeah, xampp has always too old apache2 version. It's easy make down. I recommed use apache2 only in linux. Ofc it must be always up to date.

**Comment by T0niiiiii** [comment]
PunchoDelta, yes, we have servers on ovh (SoYouStart exactly but it's same business with different name). Also we have cloudflare and hardware udp firewall...

We use Ubuntu server 16.04 and php7, apache2, mysql

**Comment by PunchoDelta** [comment]
Here it attacks port 80 and makes that the site has a 500 error but arcturus is always available and we always know how to play. Yet my site is equipped with cloudflare but it is nevertheless ddos. I will buy a shared hosting at OVH, the only problem is that the database must be able to have an external connection to be able to communicate with arcturus but I think there is a limit for external connections and it is problematic
