### ISSUE TITLE
Login Problem on Chocolatey 2.110

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#30]
Hello,

I am using [Chocolatey 2.110](https://github.com/sant0ro/chocolatey/archive/2.110.zip) and encountering an issue with the CMS.

I was able to see that my login credential were accepted (being logged in with my avatar on the top-right hand of the screen) but was being redirected back to the Homepage, with myself logged out, after one second or so.

Console Log from Chrome:
```
GET http://localhost:8080/extradata/private/moderations/recentModerations 401 (Unauthorized)
GET http://localhost:8080/api/client/clienturl 401 (Unauthorized)
Navigated to http://localhost:8080/
```

**Comment by sant0ro** [comment]
Here this bug doesn't happen.

And I'm using same version as you.

A question, are you accessing the CMS by http://localhost? or http://localhost:8080?

**Comment by s150217754** [comment]
Hi there,

That's weird. I'm accessing the CMS using http://localhost:8080/.

**Comment by sant0ro** [comment]
Yeah that's really weird. Is this account a new account that you registered with Chocolatey?

Or it's an already registered account?

Chocolatey doesn't support using old accounts before Chocolatey.

**Comment by s150217754** [comment]
Hello,

I actually migrated from Chocolatey 2.063 so there shouldn't be an issue.

To verify whether it is an isolated issue, I will be creating a new account now.

**Comment by sant0ro** [comment]
Okay! Keep me updated.

**Comment by s150217754** [comment]
Hi,

Just created a new account. After registration, able to retain login session (no logout) as per normal.

But, upon logout and re-login on the new account, the same problem occurs again.

**Comment by s150217754** [comment]
Hi,

Managed to further dig in with more trial and error.

Problem file/config discovered:

**FILE:** /config/chocolatey.php

```
    'security' => [
        'hash' => 'sha256',
        'session' => 'ChocolateyWEB'
    ],
```

If session is **NOT** ChocolateyWEB, user will face issue in logging in (see on-top for issue).

Hope this finding will help you in rectifying the session issue.

Cheers!

**Comment by sant0ro** [comment]
Thanks! Will do a research about that!

**Comment by sant0ro** [comment]
Okay i fixed it. Will create new binaries now.
