### ISSUE TITLE
issue with php artisan migrate

### ISSUE THREAD

**Issue by j0wad** [sant0ro/chocolatey#300]
http://prntscr.com/g8fixh this happens when i try to run php artisan migrate in cmd, i didnt have this issue instaling chocolatey on my main computer but im not home atm and im using a family members laptop for next cpl days

**Comment by sant0ro** [comment]
That's weird. You're using the latest binaries version?

If yes, I should investigate this.

**Comment by j0wad** [comment]
yeah i even tried archiving the copy on the working machine and using that instead and get the same error
also +1 for the quick response :P

**Comment by sant0ro** [comment]
Woah, so copying paste the version of the other machine results in the same error?

Can you attach here the output of `php -v`

It's something else on htdocs?
Where is php.exe located?

**Comment by j0wad** [comment]
yeah mate i actually tried to use the copy pasted version first and got the error then tried clean install using the github version and binaries and still got the same error this is php -v http://prntscr.com/g8fouq here is my htdocs http://prntscr.com/g8fp48 and php.exe is located at C:\xampp\php

**Comment by sant0ro** [comment]
Delete everything from the htdocs, and after that extract a clean binaries bundled with the vendor folder.

**Comment by j0wad** [comment]
tried it mate still getting the same issue using choclatey-binaries on fresh htdocs, also xampp was freshly installed too

**Comment by sant0ro** [comment]
This is really, really weird.

@s150217754 can you test latest Chocolatey version?

**Comment by j0wad** [comment]
is migration required or can i dump the db thats already been migrated n use that instead

**Comment by sant0ro** [comment]
You don't need delete or change anything on your database.

Just run `php artisan migrate`. Lumen will automatically check what it's migrated and what it's not, and only change the updates.

**Comment by j0wad** [comment]
no i mean the php artisan migrate wont run i keep getting that error i meant could i tv to my home pc and dump the database that the migration worked on and use that on my fam laptop without having to run the php migrate command

**Comment by sant0ro** [comment]
Oh yes, you can.

**Comment by j0wad** [comment]
so i imported the db that includes chocolatey tables and cant register or log into the account already registered also the news tile isnt showing on the index either

**Comment by s150217754** [comment]
@j0wad Are you still facing any issue? If so, please create a new Issue with the your Logs. Thank you. Closing this.
