### ISSUE TITLE
Try to install chocoley

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#302]
Hello,

I bought a shared hosting and I now try to install Chocoley but I get a php error

Warning: require_once(/home/habbodelcb/www/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/habbodelcb/www/bootstrap/app.php on line 3

Fatal error: require_once(): Failed opening required '/home/habbodelcb/www/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/php7.1/lib/php') in /home/habbodelcb/www/bootstrap/app.php on line 3

Thank you

**Comment by TheOmanNorge** [comment]
You have cPanel? 
Go and see if you have MultiPHP INI Editor in your control panel

Enable:
allow_url_fopen & allow_url_include

Hope that helps! :)

**Comment by PunchoDelta** [comment]
I didn't have control panel :( I'm at OVH

**Comment by TheOmanNorge** [comment]
You can't edit the php.ini file?

Hmm, ask support if thwy can enable it. 
I'm not home, and writing from my phone. 

If your issue is not solved until I'm done I'll try looking more into your problem later.

**Comment by TheOmanNorge** [comment]
Check this info, and see if that is being used to this day. 
https://www.ovh.co.uk/g1207.configure-php-web-hosting

If that is still relavant then try to add:

allow_url_include = On
allow_url_fopen = On

allow_url_include
This option allows the use of URL-aware fopen wrappers with the following functions: include(), include_once(), require(), require_once().

allow_url_fopen
This option enables the URL-aware fopen wrappers that enable accessing URL object like files. Default wrappers are provided for the access of remote files using the ftp or http protocol, some extensions like zlib may register additional wrappers.

If that does not fix your problem then take contact with your hosting provider and talk about the problem, if they can't help you
then you should maybe consider changing provider. 

I do believe this is your problem.
I MIGHT be wrong here, so if there is a geek in here please correct me and give correct answer! 

I'm not perfect, so please correct me. :)
Hope you get your issue resolved.

**Comment by TheOmanNorge** [comment]
Just a question. 
You have installed Composer? 

Just asking because I could see similar error on a different topic here. 

https://github.com/sant0ro/chocolatey/issues/305

**Comment by PunchoDelta** [comment]
I downloaded the version with the composer already included

**Comment by PunchoDelta** [comment]
I had the customer service response and it is not possible to change the PHP configuration. I think I'll have to change hosting

**Comment by PunchoDelta** [comment]
Or buy a VPS linux and make a web server on it but I'm not sure I can secure it against the DDOS

**Comment by PunchoDelta** [comment]
Hello, 

now, i have two errors on linux server

Warning: require(/var/www/html/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/html/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 66

**Comment by TheOmanNorge** [comment]
Do you use the binaries branch files? 
If not try to use them, and see if that maybe fix your issue. 

Did Composer get pre-installed on the server before you got it? Or did you install it yourself?

**Comment by PunchoDelta** [comment]
I have to download the zip that contains the composer files i think, so I have to do nothing more with the composer?

**Comment by TheOmanNorge** [comment]
Hmm, I'm no expert at this. But binaries branch contains all the files you need (If am not wrong) 

"I'm not sure I can secure it against the DDOS"
 - You can make it secure, as long as you hide the real IP very good. 
   Cloudflare might be an option. 

You still using Shared hosting or you have a linux server?

**Comment by PunchoDelta** [comment]
I have a linux server and I have installed fail2ban, iptables and a firewall and as you say I will also install cloudflare. But before that I will try to make Chocoley work

**Comment by PunchoDelta** [comment]
I have a other error

Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at /var/www/html/bootstrap/../.env. in /var/www/html/vendor/vlucas/phpdotenv/src/Loader.php:75 Stack trace: #0 /var/www/html/vendor/vlucas/phpdotenv/src/Loader.php(52): Dotenv\Loader->ensureFileIsReadable() #1 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(91): Dotenv\Loader->load() #2 /var/www/html/vendor/vlucas/phpdotenv/src/Dotenv.php(48): Dotenv\Dotenv->loadData() #3 /var/www/html/bootstrap/app.php(6): Dotenv\Dotenv->load() #4 /var/www/html/index.php(18): require('/var/www/html/b...') #5 {main} thrown in /var/www/html/vendor/vlucas/phpdotenv/src/Loader.php on line 75

**Comment by TheOmanNorge** [comment]
Alright ok didnt know that. 

What kind of OS do you run? CentOS, Debian? 
Have you checked that you are running PHP 7?

Are you using some kind of controlpanel or have you done everything with command lines?

**Comment by PunchoDelta** [comment]
I have debian8 (jessie), PHP7 is properly installed. I use SSH directly for editing with the root user

**Comment by sant0ro** [comment]
You're not using binaries branch or the latest release source code. Please use it. Master branch doesn't comes with .env

**Comment by PunchoDelta** [comment]
I used the binary branch, I still have the errors -> hdelta.net

**Comment by PunchoDelta** [comment]
It's OK, it was chmod

**Comment by sant0ro** [comment]
Yeah. Nice. Issue solved?

**Comment by PunchoDelta** [comment]
Yes,
Thanks for your help
