### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <<

### ISSUE THREAD

**Issue by fakuch1** [sant0ro/chocolatey#303]
I have php 7
I have xampp-win32-7.1.7-0-VC14-installer

I can not access
Please help! :(

http://fotos.subefotos.com/eadf045804f9dca36bc17848ff84fe96o.png

**Comment by fakuch1** [comment]
yes!
http://fotos.subefotos.com/8480cbe7e06fbee351569d40f0f4889bo.png

**Comment by fakuch1** [comment]
I followed this tutorial exactly: https://github.com/sant0ro/chocolatey/wiki/Installing-Chocolatey
I changed with the **sublime text** everything that says "arcturus" by "holodb"

**Comment by TheOmanNorge** [comment]
Hmm very strange, not sure how to fix your problem. 
@sant0ro might be able to help you more on this. 👍 

Sorry I can't, never come across the issue before.

**Comment by fakuch1** [comment]
I've solved it, files were missing!
When installing Chocolatey
With the command:
**Git clone https://github.com/sant0ro/chocolatey/**
Not all necessary files were installed.

What I did was install chocolatey from: 
**https://github.com/sant0ro/chocolatey/archive/master.zip**

Thanks!

**Comment by sant0ro** [comment]
@fakuch1 recommendation only use BINARIES branch.
