### ISSUE TITLE
Error registering (solved)

### ISSUE THREAD

**Issue by fakuch1** [sant0ro/chocolatey#304]
Someone help me with this error? I can not register :disappointed: 
http://fotos.subefotos.com/abd1e1d0b106c1d527db8e11a43dba6eo.png

**Comment by TheOmanNorge** [comment]
Very strange... 

Your using a site key in Recaptcha?
Do you mail enabled?

**Comment by fakuch1** [comment]
I have already created a ReCAPTCHA with domain localhost, 127.0.0.1!
http://fotos.subefotos.com/04e90dc11e55099e4132e1ba6f18c980o.png

**Comment by TheOmanNorge** [comment]
Alright if you did what i suggested then ok. 
Sorry I can't help you. Unsure what causing your problem.

**Comment by sant0ro** [comment]
@fakuch1 are you using latest version? check `config/mail.php` and check if 'enabled' is set to true.

**Comment by fakuch1** [comment]
Can you give me the cms already configured? I have a lot of problems installing it :sob:

**Comment by fakuch1** [comment]
>  I already configured mail.php and it is in true, I have php 7
> I already configured mail.php and I have got php 7 

Sorry for my spelling, I'm Spanish.

**I still can not solve the problem!**

**Comment by fakuch1** [comment]
I already configured mail.php and I have got php 7

**I still can not solve the problem!**

**Comment by fakuch1** [comment]
**Solved!** 
It looks like you need to remove reCAPTCHA from https://www.google.com/recaptcha/admin
Or do not register with the same email with the one I have on reCAPTCHA in "Owners"
Sorry for my spelling, i'm spanish

thank you very much :+1:  :)

**Comment by s150217754** [comment]
Issue resolved - Closing this.
