### ISSUE TITLE
xampp/php error (solved)

### ISSUE THREAD

**Issue by fakuch1** [sant0ro/chocolatey#305]
I use **xampp-win32-7.1.7-0-VC14-installer** & **PHP 7**
https://image.prntscr.com/image/k8Fwv8sKTZWZhpCmXMRssw.png
https://image.prntscr.com/image/6-URJKykS3K5x1ICeKoe4A.png

What should I do? :(

**Comment by Nenglish7** [comment]
You have to run composer.

Install composer if you do not already have it.
https://getcomposer.org/

Then go to your htdocs directory in cmd.
ex: cd ../../xampp/htdocs

after that type:
composer install

after that the vendor directory should appear and the error should go away.

**Comment by fakuch1** [comment]
Thank you very much!
You solved the problem :)
The only thing I lack is the register, I can not register! :crying_cat_face: https://github.com/sant0ro/chocolatey/issues/304

**Comment by sant0ro** [comment]
It's recommended downloading binaries branch as they comes with the vendor files.

Please read Chocolatey wiki before starting to use it. I already said it more than 150 times.

Also please run "php artisan migrate" on the htdocs folder. Ensure that php.exe is accessible from that path.

Or try

"..\php\php.exe artisan migrate"

**Comment by s150217754** [comment]
Issue resolved - Closing this.
