### ISSUE TITLE
swf - problem (solved)

### ISSUE THREAD

**Issue by fakuch1** [sant0ro/chocolatey#306]
_Sorry for my spelling, I'm Spanish._

The camera does not appear, 
the furniture in the welcome room does not appear either.
http://prntscr.com/g96611

Is there a more up-to-date emulator?
thanks

**Comment by s150217754** [comment]
Hi,

### Missing Camera Icon

This is not an issue of Chocolatey. You have probably disabled the Camera Icon in your External Variables or Database. 

### NUX / Welcome Room

Chocolatey recommends the use of Arcturus Catalog by Jmandupree which is available on RZ.

As you are not using the recommended catalog, you will need to modify the Item IDs to match what's on your items_base at `app/Helpers/Nux.php`.

We are currently exploring other alternatives to have NUX compatible across different items_base. See #183 for info.

### Other Emulator

Chocolatey is designed to support Arcturus. In our opinion, Arcturus is one of the most up-to-date Emulator available right now.

**Comment by fakuch1** [comment]
oh.. furnis solved, Still missing camera!

> camera.effects.enabled=true
> camera.enabled.android=0
> camera.enabled.desktop=1
> camera.enabled.ios=0
> camera.enabled=true

Install the new catalog and now this appears in the emulator: https://prnt.sc/g987iq
mhm

**Comment by sant0ro** [comment]
@fakuch1 search for `stories.` on the variables.

**Comment by TheOmanNorge** [comment]
Tips. 
Go to db -> emulator settings, look and see if your camera.enabled is set to 1. 
Go to db -> Permissions and see if your userlevel has Camera enabled. 
acc_camera must be on 1

Remember to use :update_permissions in-game.

**Comment by fakuch1** [comment]
The problem was the permissions table! 
But now when I take a photo that the camera is disabled
http://prntscr.com/g98lhq
That error appears to me in the emulator since I updated the catalog!

**Comment by s150217754** [comment]
@fakuch1 The recommended catalogue should not affect your Camera Subscription in anyway. I believe that the previous process was not ended completely - hence showing that it is still "logged in from somewhere else". Consider restarting your server or ending the process completely.

At the same time, we would like to remind that this is not a Help Centre for Arcturus related issue. We are not obligated to assist any issue other than a clean copy of Chocolatey.

**Comment by fakuch1** [comment]
Already solved, thank you very much for your help
@s150217754, @TheOmanNorge & @sant0ro

**Comment by s150217754** [comment]
Your welcome @fakuch1 ! Closing this.
