### ISSUE TITLE
Bug with writings

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#307]
When we add www. after http:// or https:// To the url, the writings no longer work
https://i.gyazo.com/981ffd0b0329ef4fe4fa273b0d884e24.png

**Comment by s150217754** [comment]
Hi,

You will need to include the full hotel url (including www) in `config/chocolatey.php`.

**Comment by PunchoDelta** [comment]
When i put https://www.URL.domain then https:/url.domain does not display the writings
 I tried a thread 
'hotelUrl' => [ 'https://url.domain', 'https://www.url.domain' ], but doesn't work

**Comment by sant0ro** [comment]
Puncho add the domains on the CORS array of config/Chocolatey.php

**Comment by sant0ro** [comment]
So.. Fixed?
