### ISSUE TITLE
Bug with maintenance message

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#308]
Hello, 

when the maintenance mode is off, there is still from time to time the notification "Hotel is in maintenance. We come back very quickly"

**Comment by sant0ro** [comment]
That's really weird. Never happened with me..

**Comment by PunchoDelta** [comment]
When the message appears, in the network console there is the page "ping" that responds with an error 503
https://i.gyazo.com/f68fb67f21b6bb57314c020a77fb5293.png

**Comment by sant0ro** [comment]
That has nothing related to maintenance dude. XHR = You have a CORS problem.

**Comment by PunchoDelta** [comment]
Yes i know but t first it loads 4/5 times the file and it does not load it anymore
https://i.gyazo.com/a01a45cf86e6d01b7ffd09cb6d8f16ab.png
