### ISSUE TITLE
Can't verify Email if user is registered with Facebook

### ISSUE THREAD

**Issue by TheOmanNorge** [sant0ro/chocolatey#309]
Hello.

I noticed today that when I use Facebook and registering a new user with it.
That the email I recieve about verifying the account email does not work.

You click the email link and you get to a Whops, Bobba can't load this page site, instead of verifying the account. 

And also registered the normal way without facebook and trying to verify the email does work! 
But not when using facebook. 

This was the steps I did with using Facebook.
https://www.youtube.com/watch?v=pX5UVIkWR6U

The Normal Way. 
https://www.youtube.com/watch?v=BC-fVD6g_Xk

Sorry for the radio starting sometimes during the video, but i quickly pausing it. 

I'm not sure if this is somehow because of me configuring something wrong or if this is a bug. 
Or if that is meant to be like that. 

Just wanted to tell this, since I noticed this for like 1 hour ago or something. 
Sorry if this is a known issue.

**Comment by sant0ro** [comment]
I see. This is a real issue. Probably because Facebook user creation method is different. I will give a deeper look today :)

**Comment by TheOmanNorge** [comment]
Alright, just noticed also a few things. 

- If you logged in with facebook, you will also get an error when you go to Avatars in settings. 
- In the database in chocolatey_users_mail_requests the "used" get triggered to 1 when the link has being used. But as you know you don't get verified and the link results in a error.

**Comment by sant0ro** [comment]
used it's only a parameter to say that the link is expired.

All those errors happens because users logged in with facebook doesn't get an habboID account created. I will check how Habbo.com manage with facebook users.

**Comment by sant0ro** [comment]
Fixed.
