### ISSUE TITLE
Joined Habbo Date Translation

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#31]
Hello!

The Joined Date on user's profile page requires translation based on the selected language.

Currently, it is showing in Portuguese, example:
JOINED HABBO ON 20 DE JULHO DE 2014

Thanks!

**Comment by sant0ro** [comment]
Your question is translate the word "Joined Habbo" or the Date?

**Comment by s150217754** [comment]
Hello,

It would be the date. It should be displaying July 20, 2014 for English.

**Comment by sant0ro** [comment]
I think i didn't understood correctly the question.

You don't want the date translated? Or you want?

**Comment by s150217754** [comment]
Hello,

I would like the date to be translated.

It is displaying in **Portuguese** currently - _JOINED HABBO ON 20 DE JULHO DE 2014_ but I would like it to be displaying in **English** - _July 20, 2014_.

Thanks!

**Comment by sant0ro** [comment]
Will show in portuguese if your php locale settings are in Portuguese.

I will code a feature that you choose time zone.

But that's easy to be changed.

**Comment by resrvoir** [comment]
You can manually change it in vendor.js on line 17483

**Comment by s150217754** [comment]
@resrvoir Thanks! That helps alot!

**Comment by sant0ro** [comment]
Oh now i see this bug.

Okay putting it on English by default.

**Comment by sant0ro** [comment]
Fixed it. Commiting it now.
