### ISSUE TITLE
User Maximal

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#310]
Hello. How i can set user maximal from 1 to 5 or more?

**Comment by sant0ro** [comment]
What you mean with that?

**Comment by iPrinz96** [comment]
Bevor Chocolatey 2.0 i can create 50 users with 1 account..

**Comment by sant0ro** [comment]
Sorry I didn't understood what you mean.

In Chocolatey you can create 50 accounts. See #284, I will create an option to limit MAX_Accounts

Remember.: Staff accounts can only have 1 account.

**Comment by sant0ro** [comment]
Fixed.

**Comment by sant0ro** [comment]
:)
