### ISSUE TITLE
ISSUE: Registration.

### ISSUE THREAD

**Issue by DabbelNL** [sant0ro/chocolatey#312]
Hi.

I am having an issue running the php artisan migrate command. 
My php: 7.1.7 [xampp]
Operational System: windows 2012 R2 2012

**Comment by sant0ro** [comment]
Please give more details, like the error.

**Comment by sant0ro** [comment]
Asking again, please give more details. @DabbelNL

**Comment by sant0ro** [comment]
Closing.
