### ISSUE TITLE
Group fix

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#313]
Hello. I use 
- Chocolatey CMS
- Arcturus 1.9.0
- SWF pack from RetroRipper.com with Habbo.swf from Arcturus Emulator 

Group Badges dont work.
How to fix that?
I use linux debian 8.0
The part in Emulator_setting was edited to /var/www/html/public/swf/"part to badge Order and generate part"

**Comment by TheOmanNorge** [comment]
This is not a issue related to Chocolatey CMS, consider open a topic at RageZone or Arcturus. 

I've fixed the issue many times and are able to help you later today when done from work. If you have not fixed until then. 

I think I still have you added on Skype, I will take contact later. :)

**Comment by s150217754** [comment]
Unfortunately this is not an issue with Chocolatey and thus support can't be rendered.

See @TheOmanNorge suggestion. Hope that s/he would be able to resolve this with you.

Closing this.
