### ISSUE TITLE
ISSUE: can't change password

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#319]
My change email, change password, safety question, password verification is gone D: so what the fuck?

**Comment by TheOmanNorge** [comment]
I can comfirm this as well. 

I used both Firefox and Chrome logged in and checked.
Poof, is gone! 🎃

**Comment by T0niiiiii** [comment]
screen: ![choco_ug](https://user-images.githubusercontent.com/30376926/29741802-0d7d4cc0-8a7c-11e7-81a1-46b056e19c4d.PNG)

**Comment by T0niiiiii** [comment]
also this profile time is bug :o ![choco_sad](https://user-images.githubusercontent.com/30376926/29741808-48e76b4c-8a7c-11e7-95c7-b7cf504d90e7.PNG)

**Comment by TheOmanNorge** [comment]
I don't experience the same thing as you have on your picture. 
Date works good for me. 

-->

![](https://user-images.githubusercontent.com/30376926/29741808-48e76b4c-8a7c-11e7-95c7-b7cf504d90e7.PNG)

**Comment by TheOmanNorge** [comment]
Wow, I noticed something. Do you have a .php ini file in your root folder or someone can edit it?
Try remove date.timezone line.

That fixed my problem on the Profile page. And I had no clue that would work, but somehow it did and not sure why. 

**BEFORE:** 
----------------------------------------------------------------


![before](https://user-images.githubusercontent.com/15328445/29748415-d4e12f44-8b16-11e7-9e33-2674de48a976.png)

![editphp](https://user-images.githubusercontent.com/15328445/29748417-d76416dc-8b16-11e7-9522-1a2b74879a71.png)



**AFTER**
----------------------------------------------------------------

![after](https://user-images.githubusercontent.com/15328445/29748423-edbb85d2-8b16-11e7-85bb-ba9018a8a1de.png)

![aftereditphp](https://user-images.githubusercontent.com/15328445/29748433-28c0b5b2-8b17-11e7-9284-e945bddbff7c.png)

---

**Might not fix your issue, but somehow i did for me. I did this on a different server yesterday and had never had this issue before now**

**Comment by RShizZle** [comment]
I'm also suffering from it? My options are not there anymore .. somebody fix?
http://prntscr.com/gdkv0m

**Comment by TheOmanNorge** [comment]
Yes, looks like everyone has it.
The new update might have broken something. 
Let's see what @sant0ro says about this.

**Comment by sant0ro** [comment]
That's curious. And I need advice that this isn't a Chocolatey bug. But your servers Time Configuration. As @TheOmanNorge changed his configuration on the php.ini, solved the issue.

My country time configuration works by default flawlessly with Chocolatey.

I`m going to close this issue.

Just a question, @TheOmanNorge are those accounts, Facebook accounts? Maybe I messed up things when an account isn't a Facebook account.

**Comment by TheOmanNorge** [comment]
That might be the case @sant0ro 
That something got messed up when you tried to change something there. 

I tried with Facebook and with normal login without facebook. 
Went to Settings, and with logged in the normal way you are still not able to change email, change password or security answers and this is with not logged in as a Facebook account.

**Comment by sant0ro** [comment]
Yes, was able. I will investigate. Soon as possible

**Comment by sant0ro** [comment]
Reopening since the bug wasn't fixed yet.

**Comment by sant0ro** [comment]
Fixed.

**Comment by T0niiiiii** [comment]
So you fix that? I think I must download latest binaries..

**Comment by sant0ro** [comment]
Yes.
