### ISSUE TITLE
How to update Chocolatey ?

### ISSUE THREAD

**Issue by killerrichard** [sant0ro/chocolatey#320]
Hello,

First thanks for chocolatey but how i can update with the new release without remove my hotel ?

Copy file then php artisan migrate ?
 i don't know

I have already chocolatey installed on ubuntu 17.04 / php 7.2

Thanks in advance

**Comment by TheOmanNorge** [comment]
What I do, when updating. 
Not sure if this is the right way or wrong. If wrong not sure how to do it correclty. 

I take the latest binary branch. 
(Most important files for me is .env - chocolatey.php & mail.php in the config folder.)

- Cheching the latest update, what changes it has had.
- If there is any changes to the files, then I just adjust the files so it has all the information it needs. 
so it still has the new updated code inside of the file.
- Upload the files to root directory and volla, updated.

**Comment by sant0ro** [comment]
Migrating Chocolatey it`s really easy, if you haven't done any modifications in the `app` and ` resources`  folders. If any database structure was changed, you just need to run ` php artisan migrate` . Artisan will check if any database update it's available. Database changes are made in a way that you don"t need drop or change anything. The migrations system do the updates without any bother.

Consider checking the changed files on the affected commits.

Remember, use binaries branch. Also all the tips provided by @TheOmanNorge are really useful.

If you had done any modification on the folders that I said that you need to be careful, check what changed versus what you changed. In order of not creating any conflict.

I hope your question was solved. Closing it. If you have any other question, feel free to reopen this issue.
