### ISSUE TITLE
Mail Problem with mail configured properly 

### ISSUE THREAD

**Issue by killerrichard** [sant0ro/chocolatey#321]
Error come from index : fblogin box ( the retrieve password box)

[2017-08-28 15:58:55] lumen.ERROR: Swift_RfcComplianceException: Address in mailbox given [fblogin] does not comply with RFC 2822, 3.6.2. in /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:345
Stack trace:
#0 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(261): Swift_Mime_Headers_MailboxHeader->_assertValidAddress('fblogin')
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(106): Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(Array)
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php(63): Swift_Mime_Headers_MailboxHeader->setNameAddresses(Array)
#3 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderFactory.php(58): Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(Array)
#4 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleHeaderSet.php(68): Swift_Mime_SimpleHeaderFactory->createMailboxHeader('To', Array)
#5 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(329): Swift_Mime_SimpleHeaderSet->addMailboxHeader('To', Array)
#6 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/SimpleMessage.php(305): Swift_Mime_SimpleMessage->setTo(Array)
#7 /var/www/html/vendor/illuminate/mail/Message.php(158): Swift_Mime_SimpleMessage->addTo('fblogin', NULL)
#8 /var/www/html/vendor/illuminate/mail/Message.php(92): Illuminate\Mail\Message->addAddresses('fblogin', NULL, 'To')
#9 /var/www/html/app/Helpers/Mail.php(33): Illuminate\Mail\Message->to('fblogin')
#10 [internal function]: App\Helpers\Mail->App\Helpers\{closure}(Object(Illuminate\Mail\Message))
#11 /var/www/html/vendor/illuminate/mail/Mailer.php(202): call_user_func(Object(Closure), Object(Illuminate\Mail\Message))
#12 /var/www/html/vendor/illuminate/support/Facades/Facade.php(221): Illuminate\Mail\Mailer->send('habbo-web-mail....', Array, Object(Closure))
#13 /var/www/html/app/Helpers/Mail.php(34): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#14 /var/www/html/vendor/illuminate/support/Facades/Facade.php(221): App\Helpers\Mail->send(Array, 'habbo-web-mail....')
#15 /var/www/html/app/Http/Controllers/AccountController.php(205): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#16 [internal function]: App\Http\Controllers\AccountController->forgotPassword(Object(Illuminate\Http\Request))
#17 /var/www/html/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /var/www/html/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#19 /var/www/html/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#20 /var/www/html/vendor/illuminate/container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#21 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#22 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#23 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'forgotPassword', Array)
#24 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#25 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#26 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/html/app/Http/Middleware/Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#35 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#36 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/rdehnhardt/lumen-maintenance-mode/src/Http/Middleware/MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#45 /var/www/html/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#46 /var/www/html/index.php(26): Laravel\Lumen\Application->run()
#47 {main}

**Comment by killerrichard** [comment]
Mail only work with mail send after registration .

**Comment by sant0ro** [comment]
That's really weird. It's your account a Facebook account?

Will give a check now.

**Comment by sant0ro** [comment]
Fixed.
