### ISSUE TITLE
Change the connection method

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#325]
Hello,

 I would like to change the connection method by "Pseudonym and Password". In what file can I change this

Thank you

**Comment by sant0ro** [comment]
Sorry @PunchoDelta I just saw your issue now. What you mean with that? Be able to login by username and password?

I think this is not possible, since the CMS uses HabboID, so only e-mail logins are possible.

**Comment by PunchoDelta** [comment]
Hello, thanks you for your response 
And it is not possible to modify the request for the data to be taken from the table "users"

**Comment by sant0ro** [comment]
Maybe, but hard. Since the entire CMS depends on HabboID this could break the entire system.

But I'll give a look :eyeballs:

**Comment by ovflowd** [comment]
Added this change for our roadmap in #258
