### ISSUE TITLE
Banning message exist?

### ISSUE THREAD

**Issue by PunchoDelta** [sant0ro/chocolatey#327]
When an account is banned, the player can still log into his account, there is no banning message. It's normal?

**Comment by TheOmanNorge** [comment]
No, I remember before that there was a banning message. But might be a bug on it.

**Comment by sant0ro** [comment]
There exists a banning message.

Closed.

**Comment by PunchoDelta** [comment]
strange not at home, has this been added recently?

**Comment by sant0ro** [comment]
Ban message exists since may of this year.

**Comment by PunchoDelta** [comment]
It's weird because an account is banned and he wants to log in to his account he gets there. But his client is blocking at 76%. But at no time there is a message that it would be banned

**Comment by sant0ro** [comment]
What? So a banned account can log in on the CMS? That should not happen. He would be blocked by accessing Chocolatey and a banned message would show.

**Comment by PunchoDelta** [comment]
Precisely, it happens to access the CMS without any message

**Comment by sant0ro** [comment]
I will give a check. That's weird. Issue reopened since I check completely this bug.

**Comment by sant0ro** [comment]
I will give a look today for banned accounts can log in at Chocolatey.

**Comment by ovflowd** [comment]
Added to #258
