### ISSUE TITLE
Need help with installing php craftsman migrate.

### ISSUE THREAD

**Issue by Laptek** [sant0ro/chocolatey#329]
Good evening,

I will need help to install php artisan migrate with CMD!

I did not install this correctly, so I ask if anyone can explain in detail how to proceed with this installation.

Thank you very much.

Yours.

**Comment by sant0ro** [comment]
The details of how install Chocolatey is available on our Wiki.

Just click on it. If you have any further questions, just answer here.

If you having trouble, upload screenshots of what you are experiencing.

**Comment by Laptek** [comment]
Hello dear sant0ro,

Thank you for your reply.

I explain my problem to detail!

I followed the installation to the letter of Chocolatey, everything goes very well as expected! (Import of the database Arcturus and so on ..)

After editing the .env file,

I then run the Command Prompt (CMD)

I write therefore: CD C:\xampp\htdocs then I write afterwards: php artisan migrate

The command does not execute correctly and therefore I have this message displayed: (Picture below)

<img src="https://img.lght.pics/faPJ.png" style="width:979px; height:512px;" />

I test another thing, when I run CMD (Command Prompt) and then I write: php artisan migrate

The command does not execute correctly and therefore I have this message sui displayed: (Picture below)

<img src="https://img2.lght.pics/faP8.png" style="width:980px; height:512px;" />

Hope to have was clear enough! :)

I am waiting for an answer from you.

Yours truly!

**Comment by s150217754** [comment]
Run

``C:\xampp\php\php.exe artisan migrate``

**Comment by Laptek** [comment]
Unfortunately it still does not work ..: /

<img src="https://img.lght.pics/fajg.png" style="width:980px; height:512px;" />

**Comment by sant0ro** [comment]
Exactly like @s150217754 said. I was going to answer that ;)

**Comment by sant0ro** [comment]
Just run the command that @s150217754 said. What you executed is different.

**Comment by sant0ro** [comment]
Open the CMD on the htdocs folder and write `C:\xampp\php\php.exe artisan migrate`

or `..\php\php.exe artisan migrate`

**Comment by Laptek** [comment]
> Just run the command that @s150217754 said. What you executed is different.

Anything ... it still does not work ..

**Comment by Laptek** [comment]
> Open the CMD on the htdocs folder and write C:\xampp\php\php.exe artisan migrate

or ..\php\php.exe artisan migrate


The problem is resolved, the migration has been done successfully!

Thank you so much to both of you!

**Comment by sant0ro** [comment]
We're glad that you solved it.

Closing this issue. If you have any other questions, create a new Issue.
