### ISSUE TITLE
Incorrect My Purse Info (HabboMall)

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#33]
Hello,

Presently, only credits are displaying accurately under My Purse (HabboMall).

Developer may wish to tap to the following tables to display Diamonds and HC correctly:

**Diamonds**
users_currency > type = "5"

**Habbo Club (HC)**
users_settings > club_expire_timestamp

**Builders Club**
As Builders Club are not coded, or planned to be coded in Arcturus, at least for the near future, another currency can be displayed (i.e. Duckets - users_currency > type = "0").

Thanks!

**Comment by sant0ro** [comment]
Okay, i will give a research about that.

Wait for internal updates.

**Comment by sant0ro** [comment]
Fixed.
