### ISSUE TITLE
Someone access my .env file via web browser

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#330]
Hi, someone send me mail and told me something: he can see .env file on web browser.
so, I just edit my .htaccess file and problem solved. Anyone have same problem?
If you have you need just add this to .htaccess:  ( inside <IfModule mod_rewrite.c> )

<Files ~ "\.(env)$">
	deny from all
</Files

**Comment by T0niiiiii** [comment]
EDIT: inside IfModule mod_rewrite.c

**Comment by TheOmanNorge** [comment]
This has already been fixed in the latest update.

**Comment by s150217754** [comment]
For additional security, you are advised to change your database credential and disallow external IP access to your database.

Closing this.
