### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by matotubol** [sant0ro/chocolatey#331]
Whenever i try to make Chocolatey work  i get this error.
<pre>

(1/1) FatalErrorExceptionCannot use App\Facades\Session as Session because the name is already in use
--
in User.php (line 5)
at Application->handleShutdown()in RegistersExceptionHandlers.php (line 54)
at Application->Laravel\Lumen\Concerns\{closure}()

</pre>

@sant0ro

**Comment by sant0ro** [comment]
Author abandoned this Issue. Closing.
