### ISSUE TITLE
Issue: Cant Register. useing plusemu.

### ISSUE THREAD

**Issue by PowerTurtle** [sant0ro/chocolatey#332]
Hello! I know that you guys recommend Arcturus Emulator, but i am playing around with the plus emulator.
So i will understand if i dont get any support, but i give it a try.

The console (In google chrome dev menu) Show an internal error:

api/public/registration/new Failed to load resource: the server responded with a status of 500 (Internal Server Error)
And at the same time, it say i need to verify that i am not a robot.

I have been trying to find the registration file, where is would put the info into the database, but cant find that file, as i think that is my problem.

System:
Windows 10 pro.
Xampp with php 7.0/7.1 (Cant remember wich one, but i know it is one of them.

**Comment by s150217754** [comment]
Hello!

As you have know... We don't provide support if you edit any core files of Chocolatey.

However, I will be happy to help if you do use Arcturus + a untouched copy of Chocolatey, and is experiencing the same issue.

Let us know. :)

**Comment by sant0ro** [comment]
Like @s150217754 isn't because we don't want to support you. It's because Chocolatey wasn't designed for any other Database schema or Emulator. Just because that.

If you want help from switching from Plus to Arcturus, I would really enjoy to help you.

But not on this repository, since we just provide Chocolatey help here.

**Comment by PowerTurtle** [comment]
I understand that.
I have not edit any of the core files (only the files the wiki says i need to edit when setting it up.
I have just set up a database with the sql from Arcturus, stil got the same problem. As i understand, i do not need a reCAPTCHA apikey when useing it local, or?

**Comment by PowerTurtle** [comment]
Nevermind, i had forgot to run: php artisan migrate on the new database... *facepalm*

**Comment by PowerTurtle** [comment]
I have the following error when i upload the database, and i am getting disconected when trying to join...
![screenshot_11](https://user-images.githubusercontent.com/17236810/30516153-cb5db57a-9b36-11e7-810d-0165600075c6.png)

**Comment by sant0ro** [comment]
In think latest arcturus database that I uploaded has a problem. You can download the fixed version at https://bitbucket.com/Wesley12312/arcturus

**Comment by PowerTurtle** [comment]
Same error with a new one.

**Comment by PowerTurtle** [comment]
I did found a solution, i ran the sql for 1.8.0, and used the upgrade sql from 1.8.0 to 1.9.0.

**Comment by PowerTurtle** [comment]
Hello, it may be a little problem, just for the look, but where is crossdomain.xml file path defined?

i get this 2 errors:
![image](https://user-images.githubusercontent.com/17236810/30551812-133e19a0-9c9c-11e7-8ba0-d7ae7ba9f734.png)

**Comment by sant0ro** [comment]
The crossdomain it's a route created by Chocolatey. Isn't a real file.

The problem on that case it's that on the url settings in chocolatey you forgot adding a slash on the end "/"

**Comment by sant0ro** [comment]
Closing since lack of answer.
