### ISSUE TITLE
NL catalog

### ISSUE THREAD

**Issue by Seblar** [sant0ro/chocolatey#333]
The catalog is always in dutch(?) no matter what I do.
I've checked catalog_pages in db and it's in English, tried removing catalog_pages and somehow the catalog still loads and still in dutch. Edited categories in catalog_pages but nothing changes in the catalog.

Screen:
https://gyazo.com/4ddeef38b3aac2fa83db1f6897b71007

**Comment by TheOmanNorge** [comment]
Have you tried to reset your history, deleting everything? 
Might load in the old data. 

Not sure, but might fix your problem. 

![history](https://user-images.githubusercontent.com/15328445/30524505-5be9c5d4-9bf5-11e7-99a4-f771647923ae.png)

**Comment by Seblar** [comment]
Yeah tried clearing cache and history didn't work also tried incognito. Checked furnidata.xml no dutch there what I can see.

**Comment by Seblar** [comment]
Just saw this error in lumen.log don't know if it's related. 
`[2017-09-17 21:41:58] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php:68`

**Comment by Seblar** [comment]
Somehow solved. Not really sure how I fixed it. I tested several different things and suddenly it changed language to English.
