### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Flavorounet** [sant0ro/chocolatey#334]
Hi,

I'm building my retroserver with Chocolatey, and since two days i try to find an issue to my problem but i can't find it or make anything... I'm using Apache 2.4.27, Php 7.0 and Mysql 1.4.19.0. I've listen all the tutorial, set the public key of recaptcha in the chocolatey.php file of the config/ folder but i still have this error when i'm trying to register :

> POST http://habbokappa.ml/api/public/registration/new 500 (Internal Server Error) vendor.min.js:1

If that could help you, to see what happened, you can find my retro server at http://habbokappa.ml ! I hope that you can help me !

**Comment by mackenziexD** [comment]
getting the same issue!

**Comment by sant0ro** [comment]
Hi, how are you? I will give a look on this tomorrow. Can you check if you already followed exactly the tutorial on the wiki of this repository?

Many times the problem it's the following:
- You didn't imported Arcturus Database (don't use the included with Chocolatey)
- You forgot to run "php artisan migrate"
- You forgot to configure recaptcha.

**Comment by sant0ro** [comment]
Closing, since lack of answer.
