### ISSUE TITLE
Cant Register

### ISSUE THREAD

**Issue by mackenziexD** [sant0ro/chocolatey#335]
trying to register and it keeps saying my recapture hasnt been submitted when it has. started to see a few people get this.

my recap key works fine as it lets me validate im not a robot and im using recapV2

this is the error i get
```
POST http://arcturus-hotel.com/api/public/authentication/login 500 (Internal Server Error)

(anonymous) @ VM1629:1
(anonymous) @ vendor.min.js:1
p @ vendor.min.js:1
(anonymous) @ vendor.min.js:1
u @ vendor.min.js:1
(anonymous) @ vendor.min.js:1
$eval @ vendor.min.js:1
$digest @ vendor.min.js:1
$apply @ vendor.min.js:1
(anonymous) @ vendor.min.js:1
dispatch @ vendor.min.js:1
g.handle @ vendor.min.js:1
```

using xampp with php7.0 also get the same thing with facebook when i try and register with that. but not sure if its something seperate

**Comment by sant0ro** [comment]
Hi, how are you? I will give a look on this tomorrow. Can you check if you already followed exactly the tutorial on the wiki of this repository?

Many times the problem it's the following:
- You didn't imported Arcturus Database (don't use the included with Chocolatey)
- You forgot to run "php artisan migrate"
- You forgot to configure recaptcha.

**Comment by sant0ro** [comment]
Waiting your answer.

**Comment by BoZzZzZ** [comment]
Hey i cant register because the recaptcha i have configurate the 'recaptcha' => '6LdCFDQUAAAAAKrNCriaceWBYCnjG3r9tSKd_Wan',

**Comment by sant0ro** [comment]
Closing since lack of answer.
