### ISSUE TITLE
Error 500, Windows Server 2012 R2, I believe I configured and did everything correctly.

### ISSUE THREAD

**Issue by FL4ZH** [sant0ro/chocolatey#336]
I've tried a few times to configure everything correctly and use Arcturus 1.9.0 with Chocolatey.
I'm getting a HTTP Error 500, when trying to access the site.
The config files should be configured correctly.

No log files in `storage/logs`

Edit 1: URL Rewrite, PHP 7.1.7, PHP 7.0.21 & PHP 5.3.28 is installed.

**Comment by s150217754** [comment]
> I got BrainCMS to work-ish, only thing that remained unsolvable on BrainCMS was that I couldn't connect to the client/emulator.

We do not provide support assistance on BrianCMS or Arcturus Emulator. Thank you for your understanding.

**Comment by FL4ZH** [comment]
> We do not provide support assistance on BrianCMS or Arcturus Emulator. Thank you for your understanding.
Now... I wasn't asking for support assistance on BrainCMS nor Arcturus Emulator.
Sorry for not staying clear that when I "install" Chocolatey that the server comes up with a HTTP 500 error, when trying to access the website.

**Comment by s150217754** [comment]
Now, how did you install Chocolatey?

Follow this [Tutorial](https://github.com/sant0ro/chocolatey/wiki/Installing-Chocolatey-(Noob-Friendly)#installing-chocolatey)

**Comment by FL4ZH** [comment]
I was not sure whether to configure chocolatey.php after the migration or before.

So what I did was:
> Download the latest release.
> Configure .env
> Configure chocolatey.php
> Execute `php artisan migrate` inside the Chocolatey folder.

**Comment by s150217754** [comment]
What did the command return when you execute [php artisan migrate](url)

**Comment by FL4ZH** [comment]
[This is what it returned.](https://i.imgur.com/xzoPQtI.png)

**Comment by s150217754** [comment]
Go to your Production Site (hotel url) and it still shows HTTP Error 500?

**Comment by FL4ZH** [comment]
[Still shows HTTP Error 500](https://i.imgur.com/m1lvO90.png)

**Comment by s150217754** [comment]
Are you able to confirm:

1. Chocolatey Tables is present in your MySQL Database
2. Your Production Site URL is correct
-- Verify by moving Chocolatey files in another folder where you are able to access the Index of your directory.

**Comment by FL4ZH** [comment]
1. [Chocolatey seems to be present.](https://i.imgur.com/5VNzByl.png)
2. I'm not sure what you meant by accessing the index? Do you mean something like file explorer?

**Comment by s150217754** [comment]
E.g. Move everything in /wwwroot/ to another folder and try accessing your Production Site.

**Comment by FL4ZH** [comment]
As I said before, BrainCMS seemed to work fine in /wwwroot/
[My chocolatey.php](https://pastebin.com/9BMtrrH7). I wasn't sure if I could leave the SWFs as they were, for now.

**Comment by s150217754** [comment]
Try removing the ² sign.

**Comment by FL4ZH** [comment]
I removed it from the chocolatey.php (I'm quite certain it isn't anywhere else) But should I just reload the website after editing chocolatey.php? If yes.. Then there's the same error 500.

**Comment by s150217754** [comment]
Are there any logs available at this instance?

**Comment by FL4ZH** [comment]
[Not as far as I can see.](https://i.imgur.com/bWJvW4v.png)

**Comment by s150217754** [comment]
Send us a screenshot when you execute `php artisan migrate ` again (do not change anything on your database).

**Comment by FL4ZH** [comment]
[Changed nothing in my database.](https://i.imgur.com/EaQIa0d.png)

**Comment by s150217754** [comment]
I'll let @sant0ro to follow up from here.

**Comment by FL4ZH** [comment]
Alright, thanks for your help & time.

**Comment by sant0ro** [comment]
Hi @FL4ZH sorry for the lack of updates. I was sick. I will analyze now your case. Just wait a sec.

**Comment by sant0ro** [comment]
(Observation I'm only going to answer tomorrow, still sick)

**Comment by FL4ZH** [comment]
Fixed it by Disabling some administrative rights. Cause I needed some permissions before, apparently.

**Comment by sant0ro** [comment]
Oh yeah, that's right. You added administrator account usage for the `wwroot` folder, right? I was thinking this too. Glad that you solved and I'm really sorry about the lack of updates.

**Comment by FL4ZH** [comment]
I can't remember exactly what I did, but it was something along those lines.
Keep up the great work with Chocolatey! 👍
Any chance HK is gonna be implemented soon? 🤔

**Comment by sant0ro** [comment]
Probably on my next vacations 🤔
