### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by BoZzZzZ** [sant0ro/chocolatey#337]
I have configurate the Config Failed to load resource i have looked in the google chrome console and that came Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by PunchoDelta** [comment]
Try to enable PHP errors on your server

**Comment by sant0ro** [comment]
Exactly like @PunchoDelta said. Try to enable your php error logging.

Also did you configured chocolatey correctly? It's the `vendor` folder present? Does you imported the Arcturus Database and executed `php artisan migrate` ?

**Comment by sant0ro** [comment]
Author abandoned Issue.
