### ISSUE TITLE
Blank white page, possible error 500?

### ISSUE THREAD

**Issue by Reznal** [sant0ro/chocolatey#339]
Ok so not sure what this error is caused by but ill try my best to give all the details.

Have installed the website onto my windows server as directed and migrated the db successfully.
No console logs, no logs in storage

**Comment by sant0ro** [comment]
Did you downloaded the `binaries` version?

**Comment by Reznal** [comment]
Yes, this is with the binaries version

**Comment by sant0ro** [comment]
Did you followed the instructions?

* Is your php version 7.0 or higher?
* Does you have the `vendor` folder included?
* Did you executed `php artisan migrate`?

**Comment by Reznal** [comment]
Yes to all 3.
I attempted to php migrate before I installed php 7.0+, however that didnt work so i dont think that should matter?

**Comment by JustFerry** [comment]
I am having this issue as well. Are you using XAMP, Apache or Nginx?

**Comment by Reznal** [comment]
I am using iis

**Comment by sant0ro** [comment]
Can you give me detailed logs from your IIS instance, or PHP logs generated by IIS?

**Comment by Reznal** [comment]
> `[25-Oct-2017 23:25:58 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot/storage/logs/lumen.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:107
Stack trace:
#0 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Logger.php(616): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Exceptions\Handler.php(45): Monolog\Logger->error(Object(UnexpectedValueException))
#4 C:\inetpub\wwwroot\app\Exceptions\Handler.php(41): Laravel\Lumen\Exceptions\Handler->report(Object(UnexpectedValueException))
#5 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\Registe in C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 107
[25-Oct-2017 23:25:58 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot/storage/logs/lumen.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:107
Stack trace:
#0 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Logger.php(616): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Exceptions\Handler.php(45): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 C:\inetpub\wwwroot\app\Exceptions\Handler.php(41): Laravel\Lumen\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErr in C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 107
`

**Comment by sant0ro** [comment]
You forgot giving permissions to your IIS instance.

Go on IIS, select your website in settings where is "basic permissions", select a custom account and provide your administrator login and password from your Virtual Private Server.

**Comment by sant0ro** [comment]
Author fixed the Issue.

Closing,
