### ISSUE TITLE
FindRetros on Chocolatey?

### ISSUE THREAD

**Issue by Alex-Habbz** [sant0ro/chocolatey#341]
Is there any way of implementing the FindRetros api to force votes either on the CMS or client itself? Tried to myself but wherever I put the api it stops the website from loading.

**Comment by Alex-Habbz** [comment]
https://github.com/FindRetros/Vote-Validator

That's the files there, so all three of the PHP files go in their own folder then at the top of the client or a webpage you would put "require_once 'example.php';".

That should redirect you to vote if you haven't already voted or if already voted it would carry on as normal but no matter where I put "require_once 'example.php';" it returns a error and wont load any of the CMS.

**Comment by sant0ro** [comment]
Right, seems pretty easy to integrate. I will try to code soon as possible a FindRetros plugin for Chocolatey. 

Seeya! 😃

**Comment by Alex-Habbz** [comment]
Thank you, looking forward!

**Comment by sant0ro** [comment]
@Alex-Habbz could you add this to this Issue? https://github.com/sant0ro/chocolatey/issues/287

**Comment by ovflowd** [comment]
Added to #258
