### ISSUE TITLE
(1/1) FatalErrorException syntax error, unexpected '?'

### ISSUE THREAD

**Issue by matiaspicca** [sant0ro/chocolatey#343]
(1/1) FatalErrorExceptionsyntax error, unexpected '?'
--
in ViewServiceProvider.php (line 24)
at Application->handleShutdown()in RegistersExceptionHandlers.php (line 54)
at Application->Laravel\Lumen\Concerns\{closure}()
error capture 
![noanda](https://user-images.githubusercontent.com/15640713/32247867-839e4304-be62-11e7-9ed4-affd87c05124.png)

**Comment by sant0ro** [comment]
You need read the instructions of Chocolatey.

You're not running the right php version. I will not give support if you don't follow the instructions.

Install PHP 7.0 at least.

**Comment by matiaspicca** [comment]
ahh ok

**Comment by matiaspicca** [comment]
me sale este error   no se porque tengo php 7.0.25  
![erro1](https://user-images.githubusercontent.com/15640713/32291107-d97c6f4a-bf1a-11e7-8b55-c506a1f5e04d.png)

Aquí vez no carga el contenido dentro del body  
![erro2](https://user-images.githubusercontent.com/15640713/32291115-de1d76de-bf1a-11e7-92b9-9e9543d75c70.png)
