### ISSUE TITLE
i search the Password crypt/encrypt file

### ISSUE THREAD

**Issue by iPrinz96** [sant0ro/chocolatey#344]
Hello.
I will add a Price list Site for my Rare.

i have a CMS for it.
But i will that all users was automatically registered.
This CMS use MD5 and chocolatey sha256.

i Need the crypt/encrypt Code/commands to paste it in my Price List CMS.

My current Code is:
`
function PW_HASH($password){
				$password = utf8_decode($password);
					$hash_secret = "xCg532%@%gdvf^5DGaa6&*rFTfg^FD4\$OIFThrR_gh(ugf*/";
					$string = md5($password.($hash_secret));
					return $string;
		}
`

**Comment by sant0ro** [comment]
I didn't understood your question and what is related to Chocolatey. Also Chocolatey doesn't uses sha256,
