### ISSUE TITLE
Nubs-error in Register

### ISSUE THREAD

**Issue by OliverFIN** [sant0ro/chocolatey#345]
**Hello**,

Love your work with Cholatey, but I can't fix register. I have tried my best and I will list down my Lumen errors.

`[2017-11-04 19:20:40] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Nubs\RandomNameGenerator\Alliteration' not found in C:\inetpub\wwwroot\app\Http\Controllers\AccountController.php:148
Stack trace:
#0 C:\inetpub\wwwroot\app\Http\Controllers\AccountController.php(129): App\Http\Controllers\AccountController->uniqueName('randomname@asd....')
#1 C:\inetpub\wwwroot\app\Http\Controllers\LoginController.php(85): App\Http\Controllers\AccountController->createUser(Object(Illuminate\Http\Request), Array, true)
#2 [internal function]: App\Http\Controllers\LoginController->register(Object(Illuminate\Http\Request))
#3 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#4 C:\inetpub\wwwroot\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#6 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#7 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#8 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#9 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#10 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\LoginController), 'register', Array)
#11 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#12 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#13 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#22 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#23 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#32 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#33 C:\inetpub\wwwroot\index.php(26): Laravel\Lumen\Application->run()
#34 {main}  
`

**Comment by OliverFIN** [comment]
Returns the same error 500 on api/register/new as I saw others have. I have migrated everything...

**Comment by sant0ro** [comment]
This error it's very strange. Nubs generates random usernames based on your e-mail.

Have you downloaded a `binary` version of Chocolatey through the Releases page? Or did you downloaded the source code of this repository and ran `composer install`?

**Comment by OliverFIN** [comment]
I downloaded the chocolatey from this Github and did the tutorial

**Comment by OliverFIN** [comment]
Could the error be because I use PHP 7.1.7? I read that PHP 7.1.x has a lot of changes.. @sant0ro

**Comment by sant0ro** [comment]
Please download from this link: https://github.com/sant0ro/chocolatey/releases/tag/3.000M

**Comment by OliverFIN** [comment]
This is fixed now, thank you.

What I did:
- Downloaded the reposity
- Cleared cache and deleted old tables
- Re-migrate

**Comment by ovflowd** [comment]
Glad to see that you fixed it.

Closing.
