### ISSUE TITLE
Chocolatey Habbo Setup

### ISSUE THREAD

**Issue by AntonSandin** [sant0ro/chocolatey#346]
Trying to setup my hotel with PHP 7. & MySQL & Arcturus EMU & Chocolatey CMS.
But when i try to go onto my website it shows this: 
Image of the error
https://i.imgur.com/Qb7iwYT.png

Any ideas?

**Comment by AntonSandin** [comment]
@sant0ro @s150217754

**Comment by sant0ro** [comment]
Did you downloaded the binaries? This seems that your Composer Dependencies aren't installed. Have you also configured your .env and ran `php artisan migrate` ?

**Comment by AntonSandin** [comment]
How do i run the php artisan again? And install composer? Too newb, so sorry.

**Comment by AntonSandin** [comment]
How do i install it inside of chocolatey folder?
https://gyazo.com/cc6b2d1bda5b62fd2457f92537e58b0a

**Comment by sant0ro** [comment]
You don't need install composer. Just go on Releases Page and download a binaries.zip. 

After that, open CMD on Chocolatey folder after importing your database and configuring .env and run `php artisan migrate`

If you use XAMPP run `C:\xampp\php\php.exe artisan migrate`

**Comment by AntonSandin** [comment]
Alright, all setup with 3000K Chocolatey.
Migrate succesfully, database no errors, all config are done. 

**Still:**
The page does not work
spacedream.org can not currently handle the request.

**Comment by koenno7** [comment]
I have the same problem. When I use xampp, everything works well. However when I use IIS, the same error occurs.

**Comment by AntonSandin** [comment]
@koenno7 All configs setup, migrate was succesfull, .env file is configured, IIS, MySQL 5.5, PHP 7. is installed. Really doesnt understand.

**Comment by AntonSandin** [comment]
**Update on this issue 10h after:**
Everything is setup correctly
**Config's:** All are confiugred 
**Migrate:** Migrate was successfull
**MySQL:** Using the suggested 5.5 
**PHP:** Using the suggested 7
**IIS:** Using IIS and should work fine.
**Database & Emulator:** Worked like a charm, no errros. 
Yes there is a web.config & .env file is configured.

**But the page still does not want to work. Any ideas why?**
@s150217754 @sant0ro

**Comment by sant0ro** [comment]
@AntonSandin go to this page please.

![image](https://user-images.githubusercontent.com/12037269/32439358-7d92ad5c-c2d5-11e7-8033-b9789a0415e0.png)

Put your username and password on specific user.

**Comment by sant0ro** [comment]
Also the last version is Chocolatey 3.000M, download here: https://github.com/sant0ro/chocolatey/releases/tag/3.000M

**Comment by AntonSandin** [comment]
@sant0ro Thanks, updated it to 3000M now. 
And the website works but just with **_"Whoops, looks like something went wrong."_**

**Comment by AntonSandin** [comment]
@s150217754 @sant0ro Any more ideas?

**Comment by sant0ro** [comment]
@AntonSandin I'm going to update the binaries once more again.

Configure what I said on [this screen](https://github.com/sant0ro/chocolatey/issues/346#issuecomment-342122799).

I tell you when I update it.

**Comment by AntonSandin** [comment]
@sant0ro Thanks dude. 
Hmm.. already configured that

**Comment by AntonSandin** [comment]
@sant0ro Any news?

**Comment by AntonSandin** [comment]
@sant0ro Solved this issue now.
Exactly how do i setup the recaptcha?
Site Key & Secret Key?

**Comment by sant0ro** [comment]
Follow the tutorial.

You need edit your configuration file of Chocolatey putting only the site key of your Google reCaptcha. It's easy.

**Comment by sant0ro** [comment]
Also glad you solved, what you did?

**Comment by AntonSandin** [comment]
@sant0ro Thanks, i was thinking to complicated xD 
How i solved it.. yeah let me check that.

**Comment by AntonSandin** [comment]
Client wont load o.O
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by AntonSandin** [comment]
Error fixed due to wrong production.
