### ISSUE TITLE
Habbo Club

### ISSUE THREAD

**Issue by fluxsystem** [sant0ro/chocolatey#347]
Hello.

I have a issue.

How can i fix the habbo club issue, that someone can finally use habbo club.
Without the paypal checkout fail.

Thanks

**Comment by AntonSandin** [comment]
Do you mean the payment system?

**Comment by fluxsystem** [comment]
No, more that a player can buy hc with credits

**Comment by sant0ro** [comment]
@fluxsystem you mean the ability of purchase Habbo Club directly from the CMS?

**Comment by fluxsystem** [comment]
Yes correctly or via the client

**Comment by fluxsystem** [comment]
@sant0ro so whats the solution to this problem

**Comment by sant0ro** [comment]
I think Wesley the creator of Arcturus, removed Habbo Club. Since it's useless. All features of Habbo Club are enabled by default, as far I know.

The Shop of Chocolatey isn't done, and for today it's useless. New features will come in Chocolatey in this year.

**Comment by fluxsystem** [comment]
Nope it isnt the clothing etc doesnt work, it says hey you need habbo club -,-

**Comment by sant0ro** [comment]
This isn't a Chocolatey Issue, this is an Arcturus Issue, I recommend you create an Issue on his Bitbucket or on the Help Section of RaGEZONE.

Anyways, I know that the built-in catalogue from Arcturus doesn't have working Habbo Club.

I recommend the catalogue made by JmanDupree.

If you have any other questions, feel free to ask :)

Also you can disable in the table "emulator_settings" the needing of Habbo Club.

**Comment by fluxsystem** [comment]
Thanks, but how can i implent JmanDupree his catalogue and where can find it

**Comment by sant0ro** [comment]
His catalogue can be found in RaGEZONE releases page.

http://forum.ragezone.com/f353/plus-emulator-complete-header-list-1138248/ this is the direct link for the v2 of the Catalogue, that it's an edit from the v1.

**Comment by fluxsystem** [comment]
Hmmh Where can i turn the needing of hc off (emulator_settings ->)

**Comment by sant0ro** [comment]
I will give a little research and tell you sooner as possible. But try using the catalogue that I sent to you.

**Comment by fluxsystem** [comment]
Its weird because only two dev codes

**Comment by AntonSandin** [comment]
Following this ticket, interested in this aswell.
@sant0ro May you check my issue aswell?

**Comment by TheOmanNorge** [comment]
The link you posted was about Plus Emulator header list. 

Here is the link for the catalogue. 
http://forum.ragezone.com/f353/arcturus-catalog-v2-hotelmaker-1133385/

I'm currently is using that one, and you can buy HC directly from the catalogue.
