### ISSUE TITLE
Recaptcha doesn't verify and 500 internal error on register.

### ISSUE THREAD

**Issue by RetroPiggy** [sant0ro/chocolatey#35]
Ever since the first release of this CMS, I have not been able to register :/
Below is a link to a GIF of the errors and response in the console.

http://i.imgur.com/4H2lVd0.gifv

**Comment by sant0ro** [comment]
Hi @RetroPiggy it seems that the CMS cannot find the MySQL Driver.

Please download latest XAMPP Version, and try use Chocolatey with it.

**Comment by RetroPiggy** [comment]
Wow, never thought of that. Im used to working with older projects so never thought about updating the whole of xampp. All works fine now! Thanks for the help :)

**Comment by sant0ro** [comment]
I'm glad to hear that.
