### ISSUE TITLE
Error after installed

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#350]
I have changed DocumentRoot property and Directory to "C:/xampp/htdocs/public".
Now I'm getting this error when I try lo load localhost.
![screenshot_1](https://user-images.githubusercontent.com/26200747/32453971-15950166-c31e-11e7-9880-2309a03fb489.png)

**Comment by sant0ro** [comment]
I forgot adding the vendor files. Sorry.

New release: https://github.com/sant0ro/chocolatey/releases/tag/3.000P
