### ISSUE TITLE
Client disconnect

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#352]
Client disconnect after 76%.
![screenshot_2](https://user-images.githubusercontent.com/26200747/32459358-b23c80aa-c32f-11e7-91c1-147c7c15dcee.png)

Also the client loads index.php (actually not found)
![screenshot_3](https://user-images.githubusercontent.com/26200747/32459394-dbdca368-c32f-11e7-92bb-6996bf72881c.png)

And i got this error on lumen's log: (it happens when I access to /community/rooms)

`[2017-11-06 20:26:46] lumen.ERROR: ErrorException: Trying to get property of non-object in C:\xampp\htdocs\app\Http\Controllers\ImagingController.php:29
Stack trace:
#0 C:\xampp\htdocs\app\Http\Controllers\ImagingController.php(29): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 29, Array)
#1 [internal function]: App\Http\Controllers\ImagingController->getUserHead(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(29): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#5 C:\xampp\htdocs\vendor\illuminate\container\Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#6 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(373): Illuminate\Container\Container->call(Array, Array)
#7 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(339): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#8 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(313): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ImagingController), 'getUserHead', Array)
#9 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(275): Laravel\Lumen\Application->callControllerAction(Array)
#10 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(260): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#11 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#12 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#13 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#21 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#22 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#23 {main}

**Comment by sant0ro** [comment]
This error has nothing to do with Client. It's about Habbo-Imaging.

Please check your network tab in Chrome. You probably forgot configuring something.

**Comment by Ninktos** [comment]
I have the default chocolatey habbo-imaging config

**Comment by Ninktos** [comment]
It just happens when i'm on /community/rooms
![screenshot_4](https://user-images.githubusercontent.com/26200747/32460116-f9a1c6d8-c331-11e7-8b02-5b7d5450c248.png)
![screenshot_5](https://user-images.githubusercontent.com/26200747/32460119-fbcc5b1c-c331-11e7-821c-b341e735045e.png)

**Comment by sant0ro** [comment]
Okay. Check your client configuration. 99% you configured something wrong.

**Comment by Ninktos** [comment]
Checked and still the same, i've checked 1by1 urls and they are ok. Registered a new account, allowed me to change their name to Heartz, but when i closed the browser and reoppened the account. The name didn't change to Heartz. What?

**Comment by Ninktos** [comment]
Could I have problem with loginstep?
![screenshot_1](https://user-images.githubusercontent.com/26200747/32467372-b26ec37e-c34a-11e7-9bdc-403f8a53e81d.png)

**Comment by sant0ro** [comment]
All those are normal. PLEASE send me a screen of your NETWORK tab.

I'm 99% sure that something in your URLs are wrong, or something in your external_variables is wrong.

Chocolatey works 100%. I tested it today with Arcturus 1.10.0

**Comment by Ninktos** [comment]
![screenshot_3](https://user-images.githubusercontent.com/26200747/32497575-4a78c584-c3cd-11e7-9e73-97e544d0150c.png)
![screenshot_4](https://user-images.githubusercontent.com/26200747/32497577-4ccb4848-c3cd-11e7-9acc-ef42cb11f4b7.png)

**Comment by sant0ro** [comment]
Sadly I cannot see what is wrong. Follow the contents of [this](https://github.com/sant0ro/chocolatey/blob/master/SUPPORT.md) file.
