### ISSUE TITLE
cms error

### ISSUE THREAD

**Issue by matiaspicca** [sant0ro/chocolatey#353]
This appears to me I do not know how to fix it, help

![errorcms](https://user-images.githubusercontent.com/15640713/32471669-530f0496-c33d-11e7-8eec-b37951c79f5c.png)

**Comment by sant0ro** [comment]
You probably forgot to run `php artisan migrate`

**Comment by matiaspicca** [comment]
error
![errorcms](https://user-images.githubusercontent.com/15640713/32472315-dcefc01c-c340-11e7-86a6-6ef65be85c73.png)

**Comment by sant0ro** [comment]
You don't have MySQL and PDO enabled on your PHP environment. If you have XAMPP (that I recommend) use `C:\xampp\php\php.exe artisan migrate`

**Comment by matiaspicca** [comment]
is already enabled that comes by default from the version 5.3+ php
https://secure.php.net/manual/es/pdo.installation.php
http://php.net/manual/es/mysqli.installation.php  
![php](https://user-images.githubusercontent.com/15640713/32510539-b99f86e4-c3cf-11e7-8ffc-12d5b5e7fa58.png)

**Comment by TheOmanNorge** [comment]
In chocolatey.php, what have you put in as site url? 

I had the same issue before, and the reason was simply because I had put https.
When entering the site, it loaded into http:// and all the text was messed up like yours on the image.

I made it force into https in the .htaccess file and all the text got fixed.¨
If you ever return back to Chocolatey at Habboup.org, let me know. And I'll help you out if the problem still occour.

**Comment by sant0ro** [comment]
@TheOmanNorge I think he's problem it's the migration. He isn't even imported the Chocolatey CORE tables.

@matiaspicca MySQL adapter is disabled by default since PHP 7.0

You need on your `php.ini` enable the MySQL driver.

**Comment by matiaspicca** [comment]
where is the CORE tables for download???

**Comment by sant0ro** [comment]
If you read correctly my comment. The CORE tables are IMPORTED when you run `php artisan migrate`

**Comment by sant0ro** [comment]
But you're getting PDOException saying that the MySQL adapter isn't enabled. Soooo... If you don't know enabling the MySQL adapter on PHP, just download XAMPP and run the command using the PHP from XAMPP 👍

**Comment by matiaspicca** [comment]
Can you import the core table without doing artisan php?

**Comment by matiaspicca** [comment]
http://habboup.org/version.php

**Comment by sant0ro** [comment]
Nope. They are made with Laravel. They do a lot of commands inside your Arcturus database.

I recommend you just download some other php that already has mysql configured. And run it.

In the future versions of chocolatey I will try to make more easier importing the core tables, directly from the browser.

Another observation: this error that it's happening isn't only for the `php artisan migrate`, your php doesn't have MySQL enabled. That means that Chocolate wouldn't work anyways.

**Comment by sant0ro** [comment]
http://habboup.org/version.php

Are you sure that this php running on your browser, it's the same from where you ran the migrate command?

Because that `phpinfo()` says MySQL it`s enabled.

**Comment by matiaspicca** [comment]
http://habboup.org/version.php aqui me dice que uso php7
![php5](https://user-images.githubusercontent.com/15640713/32574998-94d3be06-c4b1-11e7-97a9-c39c8d142be9.png)
y aca dice que uso php 5  :( joder

**Comment by ovflowd** [comment]
What is this HabboUP folder? A web server?

**Comment by matiaspicca** [comment]
yes

**Comment by matiaspicca** [comment]
Full Webserver (Apache,PHP, MySQL, navicat

**Comment by matiaspicca** [comment]
no uso iis ni xampp

**Comment by ovflowd** [comment]
Can you send a photo of the folder of HabboUP?

Maybe you can just do `C:\HabboUP\php\php.exe artisan migrate` inside the folder of Chocolatey.

**Comment by matiaspicca** [comment]
![php6](https://user-images.githubusercontent.com/15640713/32576267-3c1ab298-c4b5-11e7-8752-def66e5b9631.png)

**Comment by ovflowd** [comment]
Try `C:\HabboUP\php7\php.exe artisan migrate`

**Comment by matiaspicca** [comment]
si eso hize ante eso 
![ultmo](https://user-images.githubusercontent.com/15640713/32576478-d6404cfc-c4b5-11e7-9fed-56eefeaffef9.png)

**Comment by ovflowd** [comment]
Weird. Can you check which php version is your Web Server running?

**Comment by matiaspicca** [comment]
https://user-images.githubusercontent.com/15640713/32574998-94d3be06-c4b1-11e7-97a9-c39c8d142be9.png

http://habboup.org/version.php

**Comment by ovflowd** [comment]
That wasn't what I meant to say. Open C:\habboUP\conf\httpd.conf and search for php

**Comment by matiaspicca** [comment]
![ultmoporfin](https://user-images.githubusercontent.com/15640713/32580315-64dfedca-c4c3-11e7-8169-a9538752db6a.png)
No entiendo men porque no anda si esta bien :(

**Comment by ovflowd** [comment]
Wierd, it's using php7. Can you just test with Xampp, please?

**Comment by matiaspicca** [comment]
ahora pruebo

**Comment by matiaspicca** [comment]
6Ld0ejcUAAAAAJPAr4dYmy9-PzqZp_P-Uvvk7ROV

**Comment by matiaspicca** [comment]
Ya pude 
![yapude](https://user-images.githubusercontent.com/15640713/32624769-ff8d5c5e-c568-11e7-9cf0-81be429c3e91.png)
este era el error 
![yapude1](https://user-images.githubusercontent.com/15640713/32624777-07ee0484-c569-11e7-9a50-5e0454c15659.png)
pero lo mismo sigue apareciendo esto sabes porque paa esto? 
![yapude2](https://user-images.githubusercontent.com/15640713/32624795-17333e64-c569-11e7-8c79-34106b87a315.png)

**Comment by ovflowd** [comment]
Nice that you solved it. Open the network tab and check how it's trying to open the language file.

**Comment by matiaspicca** [comment]
![errolenguake](https://user-images.githubusercontent.com/15640713/32625595-68eca25c-c56b-11e7-892a-aaa170ab00d7.png)


eso me aparece

**Comment by matiaspicca** [comment]
![errolenguake2](https://user-images.githubusercontent.com/15640713/32625798-00215370-c56c-11e7-83a7-860e815060a7.png)

**Comment by ovflowd** [comment]
You're using Chocolatey completely wrong wtf.

First you need set the DocumentRoot of your web server to the public folder of chocolatey. And need ensure that the .htaccess is working.

This isn't the correct file to access the language system...

Chocolatey doesn't load this file. It loads /habbo-web-10ln/com.json

What you opened on your browser it's just an template file.

**Comment by matiaspicca** [comment]
Ahi esta men pero no anda sigue igual y lo de htaccss no se que teng que hacer ahi ?
![httpd](https://user-images.githubusercontent.com/15640713/32676074-022a1450-c638-11e7-82ec-51cee97899fc.png)
![httpd2](https://user-images.githubusercontent.com/15640713/32676079-063ae0ec-c638-11e7-9f49-7fd3adc7ebad.png)

**Comment by ovflowd** [comment]
after the htdocs put /public on the end.

And be sure you're using the latest version from chocolatey.

**Comment by matiaspicca** [comment]
si eso hize ante pero lo mismo da el mismo error uso  >  chocolatey-3.000I

**Comment by matiaspicca** [comment]
vez si pongo /public
![httpd3](https://user-images.githubusercontent.com/15640713/32676738-7eae06e2-c63a-11e7-8dac-50d426cb5715.png)

**Comment by matiaspicca** [comment]
ya FUNCIONAAAAA :OO   GRACIAASSSSSSSSSSSSSSSSS XDDDD

**Comment by matiaspicca** [comment]
mira no se porque pasa esto cuando quiere registrate 
![image](https://user-images.githubusercontent.com/15640713/32678935-51f30572-c643-11e7-8975-d805a329b827.png)

le doy a registrar  y aparece esto ya puse el recaptcha

![image](https://user-images.githubusercontent.com/15640713/32678974-7967f842-c643-11e7-9232-fc8982deb2bf.png)

![image](https://user-images.githubusercontent.com/15640713/32678999-9329aaaa-c643-11e7-88f5-473469173712.png)

**Comment by matiaspicca** [comment]
![image](https://user-images.githubusercontent.com/15640713/32679463-474764c2-c645-11e7-82e6-2d64dde72b42.png)
ahora si jodidoo

**Comment by ovflowd** [comment]
The error appears if you didn't run with success "php artisan migrate" make sure that you first imported Arcturus Database and after that run the migration. Also check if the .env configuration it's 100% right.

**Comment by matiaspicca** [comment]
ya intente de nuevo y nada  hace lo mismo   
![image](https://user-images.githubusercontent.com/15640713/32684350-7e447296-c661-11e7-9c22-caa917825c24.png)

extension=php_pdo_mysql.dll tengo activado el pdo de mysql esta bien o hay que usar el pdo_mysqli? es que el pdo_mysqli no esta en php 7 no se si puede ser por eso 

pero  esta bien configurado el .env  
estas seguro que no anda porque no esta mal el php artisan migrate ?
![image](https://user-images.githubusercontent.com/15640713/32684391-d4a2040a-c661-11e7-86d5-79a7628bf9f9.png)

no tenes por algun lado la tablas par pasarmela y la importo sin hacer el php artisan migrate

**Comment by matiaspicca** [comment]
???

**Comment by ovflowd** [comment]
I really don't know what it's happening, @matiaspicca I can't seem to solve it for you, since I never though about this HabboUP web server before.

I just recommend you using normal and common web servers, like IIS, XAMPP, Vertrigo or WAMP.

**Comment by matiaspicca** [comment]
:( es que usar xampp y iis no es seguro en holo  aparte eso se utiliza en desarrollo  :(
