### ISSUE TITLE
Chocolatey Swedish

### ISSUE THREAD

**Issue by AntonSandin** [sant0ro/chocolatey#354]
Is there any Swedish version of Chocolatey?

**Comment by sant0ro** [comment]
I didn't translated it yet to Swedish but I can.

**Comment by AntonSandin** [comment]
@sant0ro Alright, btw why does my website do this?
https://gyazo.com/085fafb6be6e98403f59a784f04274bd?token=9f758e876283b5b09103a4953170916c
_o.O_

**Comment by sant0ro** [comment]
On my phone the gif isn't playing..

**Comment by sant0ro** [comment]
Opened the gif. But I can't see what is wrong.

**Comment by sant0ro** [comment]
![image](https://user-images.githubusercontent.com/12037269/32508897-f382e8d0-c3d2-11e7-89a6-9cb7d223fbac.png)

Loaded fine here.

**Comment by AntonSandin** [comment]
@sant0ro Yeah fixed that xD, Do you know why the client is 76%? Seems like some swf or smtng

**Comment by sant0ro** [comment]
I will give a check.

**Comment by AntonSandin** [comment]
@sant0ro Thanks 🗡

**Comment by TheOmanNorge** [comment]
The most common mistake a see many people do, is that they are using the wrong Habbo.swf file. 
That is the reason for me aleast I'm stuck at 79%, my test hotel is working fine. 

Of course I might be wrong in your case, but try using this Habbo.swf file I'm providing. 

You're using the latest Arcturus Emulator v1.10.0? 
Download this. Remember to take Backup of your old file in case if it does not work. 
[Habboswf.zip](https://github.com/sant0ro/chocolatey/files/1455147/Habboswf.zip)

When the file is repleaced, delete cache and try again and enter your hotel. 

Hope you get it working.

**Comment by sant0ro** [comment]
AS @TheOmanNorge said, also checked right here. Everything working on my local instance of Chocolatey 😅

**Comment by AntonSandin** [comment]
@TheOmanNorge I've tried your SWF & actually wrong version of emulator fixed that to and the config, migration. 
Cleared cache in CloudFlare & computer. Still 76%. 

Is it possible for you to connect to the VPS and check it out? **Thanks.**

**Comment by AntonSandin** [comment]
@sant0ro Yeah ^

**Comment by ovflowd** [comment]
I hope @TheOmanNorge can help you because I had no time. Sorry.

**Comment by AntonSandin** [comment]
@sant0ro No worries, i hope so aswell ^

**Comment by TheOmanNorge** [comment]
I'll help you out later today with it, when i get home from my job. 
Meanwhile accept my Skype friend request. 

I will be in touch.

**Comment by AntonSandin** [comment]
@TheOmanNorge Thanks!

**Comment by TheOmanNorge** [comment]
Regarding the client loading to only 76%.
Problem has been fixed.  👍

Was not a Chocolatey issue/problem. But wrong settings in the emulator.
