### ISSUE TITLE
Installition problem

### ISSUE THREAD

**Issue by T0niiiiii** [sant0ro/chocolatey#355]
So I download latest binaries and upgrade cms. Now when I go site I see only: "Warning. Please read Chocolatey Installation Tutorial. You need configure your servers DocumentRoot to the public folder of this CMS. Thanks!". I have installed succesfully this cms many time but now I have some problem. Any advice?

**Comment by T0niiiiii** [comment]
Lumen.log is empty btw

**Comment by sant0ro** [comment]
Just read what the message is saying. I just changed those things. Change your DocumentRoot or whatever from your webserver to the public folder of Chocolatey....

**Comment by sant0ro** [comment]
(/var/www/hotel/public_html/public/)

Change on your Apache configurations "/var/www/hotel/public_html/" to "/var/www/hotel/public_html/public"

**Comment by T0niiiiii** [comment]
Oh okey, but index.php and .htaccess is on /var/www/hotel/public_html so why /var/www/hotel/public_html/public/? it's just not make any sense to me. public have swf etc

**Comment by T0niiiiii** [comment]
Oh, so you just change index.php and .htaccess to public folder. now I understand. Did you update anything else? When espresso housekeeping is ready to use?

**Comment by ovflowd** [comment]
I did updated some things, yes. But they're minor changes. Buggers changes will come next month.
