### ISSUE TITLE
News Title Issue

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#36]
Hello,

News, and its Alt Tag etc., is showing "Race to the Limit!" rather than the actual title.

**Needs replacement in:**
- /resources/views/habbo-web-news/articles-front.blade.php 
- /resources/views/habbo-web-news/articles-category.blade.php 
- /resources/views/habbo-web-news/articles-view.blade.php 

Thanks!

**Comment by s150217754** [comment]
If anyone wants a quick fix, here it is:

**/resources/views/habbo-web-news/articles-front.blade.php**
**Replace** _Race to the limit!_ **to** _{{$articleContent->title}}_

**/resources/views/habbo-web-news/articles-category.blade.php**
**Replace** _Race to the limit!_ **to** _{{$articleContent->title}}_

**/resources/views/habbo-web-news/articles-view.blade.php**
**Replace** _Race to the limit!_ **to** _{{$article->title}}_

**Comment by sant0ro** [comment]
Fixed it.

Will commit soon as possible.
