### ISSUE TITLE
Client disconnects with 403 Forbidden on SWFS

### ISSUE THREAD

**Issue by RetroPiggy** [sant0ro/chocolatey#38]
Ok, after getting everything working and creating an account, I went to load the client and it disconnects just after it loads.

Looking in the console, I see the link to my SWF folder which failed to load due to a 403 forbidden. I'm guessing this is what is causing the problem as if the client can't access my main SWF folder, none of the other items like texts and variables cannot be loaded either.

I have tried changing the allowed ips in the .env file to see if that helps but it doesn't :/

**Comment by sant0ro** [comment]
You need host the SWF's in a different path.

You cannot store the SWF's directly on Chocolatey's folder.

If you want i can create the ability of allowing any content inside /public to be used in URIs

**Comment by RetroPiggy** [comment]
Yes, I think that would be useful :)

Thanks :)

**Comment by sant0ro** [comment]
Okay, you just need put the content of your SWF on public/

And in the `chocolatey.php` SWFs section add something like

http://myhotel.com/public/swf-folder/blah-blah
