### ISSUE TITLE
Can't register, captcha and artisan migrate question

### ISSUE THREAD

**Issue by Kaizeer** [sant0ro/chocolatey#39]
Hey. I'm experiencing the same error as RetroPiggy in the issue #35 
I'm using chocolatey with the latest version of XAMPP. I've configured the database information in the .env file. I have some trouble understanding how to execute the migration correctly, how exactly do I do it and is this the reason for not being able to register og sign in? 

Thanks in advance!

**Comment by RetroPiggy** [comment]
You need to open a CMD window in the htdocs directory by holding shift and right clicking while in the htdocs directory. Once done, type in C:\xampp\php\php artisan migrate

That will work if you installed xampp to the default directory

Here is an image of what I mean: http://i.imgur.com/eKPORRa.png

**Comment by Kaizeer** [comment]
Works like a charm. Thank you very much!
