### ISSUE TITLE
Unable to View News

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#42]
Hello,

URL **/habbo-web-news/en/production/articles/1_content.html** is showing a 500 (Internal Server Error).

To fix this, a small code change is required.

In **/resources/views/habbo-web-news/articles-view.blade.php**

**Line 11:**
Replace _{{$articleContent->title}}_ with _{{$article->title}}_

Thanks!

**Comment by sant0ro** [comment]
I probably created this bug by trying to fix #36 

Will fix it now.
