### ISSUE TITLE
Purse - Habbo Club Date

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#43]
Hello,

Habbo Club remaining days is showing incorrectly due to a small error.

To fix this, a small code change is required:

In **/app/Models/Purse.php** 

**Line 60:**

Replace:
`$habboDays = floor(($habboDays->club_expire_timestamp ?? 0) - time() / 86400);`

With:
`$habboDays = floor((($habboDays->club_expire_timestamp ?? 0) - time()) / 86400);`

Thanks!

**Comment by sant0ro** [comment]
Okay, going to fix it. Thanks, it's a really small error.

**Comment by sant0ro** [comment]
Anyways this method it's little embarrassing. I think it's the poorest method of the cms in a Model.

Anyways, fixed. Commiting.
