### ISSUE TITLE
Habbo Mall - Purchase Section

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#44]
Hello,

There should be two separate section under "BUY HABBO CREDITS AND MORE":

1. Membership and bundles
2. Credits

See screenshot from Habbo:
http://imgur.com/a/bkAs0

Thanks!

**Comment by sant0ro** [comment]
Closing this Issue because it's nonsense.

In Chocolatey you configure in the database how you want to the Buy Page be.

You just need insert what you want and configure what you want. Everything it's customizable.

But i recommend wait the release of Espreso Housekeeping.

**Comment by s150217754** [comment]
Hi,

My bad. It was a database error on my part. All good now!

**Comment by sant0ro** [comment]
Nice!
