### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by xInuyasha** [sant0ro/chocolatey#46]
I got the same problem like in #35 but i have the newest Version of Xampp and PHP.

**Comment by sant0ro** [comment]
Does you configured and followed the Wiki Tutorial?
Does you also configurated Recaptcha?

**Comment by xInuyasha** [comment]
Sure, did everything.

**Comment by sant0ro** [comment]
That doesn't make any sense. Can you send me the logs?

**Comment by xInuyasha** [comment]
The lumen file in the storage folder?

**Comment by sant0ro** [comment]
Yes! /storage/logs/lumen. Attach it here please.

**Comment by xInuyasha** [comment]
[lumen.txt](https://github.com/sant0ro/chocolatey/files/790813/lumen.txt)

**Comment by sant0ro** [comment]
Based on the errors. Does you migrated the database, by running "php artisan migrate"?

**Comment by xInuyasha** [comment]
Yes, i did

**Comment by sant0ro** [comment]
No you didn't.

All errors are about non-existent tables.

Make sure you migrated to correct database. And the database exists.

MAKE really sure that the migration didn't answered any errors.

**Comment by xInuyasha** [comment]
k, i set it new up, write u when i finished.

**Comment by xInuyasha** [comment]
Ok, register works now, thanks for ur help! :)

**Comment by sant0ro** [comment]
Thanks,

I'm glad to hear you fixed it.
