### ISSUE TITLE
Category Sorting and Multiple Categories

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#47]
Hi,

Some low-priority suggestions:

**Category Sorting**
Is it possible to sort categories so that important/hot categories such as "Campaign & Activities" are first?

Screenshot from Habbo: http://imgur.com/a/L794s

**Multiple Categories**

Also, would it be possible to have one article to be listed on multiple categories? I have tried using commas (e.g. _safety, technical.updates_ under "categories" of chocolatey_articles table) but it wouldn't work.

Screenshot from Habbo: http://imgur.com/a/kC4Nw

Thanks!

**Comment by sant0ro** [comment]
As far I know in Chocolatey, multiple categories are separated by `;`

As an example `credit.promo;fansites`

**Comment by s150217754** [comment]
Just tried it. Doesn't seem to work.

**Comment by sant0ro** [comment]
Tried with `,` also?

But what exactly you want? Those multiple categories appear on an article, right?

If yes, that should work.

I will check this. Transferring this as an Issue.

**Comment by s150217754** [comment]
Yes. Article to display on multiple categories. Thanks!

**Comment by sant0ro** [comment]
Okay, i will give a check and notify you with updates.

**Comment by s150217754** [comment]
@sant0ro Multiple categories works with `,` now; after downloading the new binaries.

Any updates whether **Category Sorting** (see above) will be included on Chocolatey?

Thanks!

**Comment by sant0ro** [comment]
I think Category Sorting will be a Housekeeping Feature.

**Comment by sant0ro** [comment]
This Issue it's fixed. Asking to @Emeto code a "custom category sorting" thing.

But for me this feature requests it's just bullshit. You just can sort it directly from the database...

Anyways.

**Comment by s150217754** [comment]
Yeah, I personally sorted mine via the database.
