### ISSUE TITLE
Facebook Login/Register is not working

### ISSUE THREAD

**Issue by joostply4** [sant0ro/chocolatey#48]
**Console error:**
TypeError: Cannot read property 'toString' of undefined vendor.js:3226
    at Object.o.create (https://***/habbo-web/scripts.js:48:4489)
    at i.create (https://***/habbo-web/scripts.js:48:2920)
    at a (https://***/habbo-web/vendor.js:3573:42)
    at https://***/habbo-web/vendor.js:3582:21
    at p.$eval (https://***/habbo-web/vendor.js:3934:36)
    at p.$digest (https://***/habbo-web/vendor.js:3889:60)
    at p.$apply (https://***/habbo-web/vendor.js:3960:35)
    at s (https://***/habbo-web/vendor.js:2797:126)
    at b (https://***/habbo-web/vendor.js:2873:56)
    at XMLHttpRequest.E.onload (https://***/habbo-web/vendor.js:2891:88) undefined

**Lumen log:**
[2017-02-22 14:09:08] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) in C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php:68
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(68): PDO->__construct('mysql:host=loca...', 'forge', '', Array)
#1 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'forge', '', Array)
#2 C:\xampp\htdocs\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 C:\xampp\htdocs\vendor\illuminate\database\Connectors\ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(882): call_user_func(Object(Closure))
#6 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(903): Illuminate\Database\Connection->getPdo()
#7 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(392): Illuminate\Database\Connection->getReadPdo()
#8 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(318): Illuminate\Database\Connection->getPdoForSelect(true)
#9 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#10 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(326): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#12 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1718): Illuminate\Database\Connection->select('select * from `...', Array, true)
#13 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1703): Illuminate\Database\Query\Builder->runSelect()
#14 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(485): Illuminate\Database\Query\Builder->get(Array)
#15 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(469): Illuminate\Database\Eloquent\Builder->getModels(Array)
#16 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(401): Illuminate\Database\Eloquent\Builder->get(Array)
#17 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(276): Illuminate\Database\Eloquent\Builder->first(Array)
#18 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1316): Illuminate\Database\Eloquent\Builder->find(false)
#19 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1328): Illuminate\Database\Eloquent\Model->__call('find', Array)
#20 C:\xampp\htdocs\app\Http\Controllers\ArticleController.php(27): Illuminate\Database\Eloquent\Model::__callStatic('find', Array)
#21 [internal function]: App\Http\Controllers\ArticleController->many('en', 'front')
#22 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(28): call_user_func_array(Array, Array)
#23 C:\xampp\htdocs\vendor\illuminate\support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#24 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(86): value(Object(Closure))
#25 C:\xampp\htdocs\vendor\illuminate\container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#26 C:\xampp\htdocs\vendor\illuminate\container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#27 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(743): Illuminate\Container\Container->call(Array, Array)
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(709): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(683): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ArticleController), 'many', Array)
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(645): Laravel\Lumen\Application->callControllerAction(Array)
#31 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(630): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(600): Laravel\Lumen\Application->handleFoundRoute(Array)
#33 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(532): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#34 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(48): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#41 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(780): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#43 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#44 C:\xampp\htdocs\index.php(27): Laravel\Lumen\Application->run()
#45 {main} 

And a lot more of similar errors

**Comment by sant0ro** [comment]
First, we don't support actually Facebook login.

Secondly, your database connection details are wrong

`lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) in `

**Comment by joostply4** [comment]
@sant0ro will it be supported in the future? 
I've set my .env files. But somewhere.... idk where, it grabs forge :/

**Comment by sant0ro** [comment]
That's weird.

Yes Facebook is planned to be a common feature. I forgot to create an Issue for that.

**Comment by sant0ro** [comment]
Closing this Issue and reffering it.
