### ISSUE TITLE
NUX not available after first time

### ISSUE THREAD

**Issue by resrvoir** [sant0ro/chocolatey#51]
So what happens is that when people join the hotel they dont get to the client because of the "Missing Flash Player" and they fix it by logging again to their new account and by doing that they dont get to change their name, also this 
![screenshot_1](https://cloud.githubusercontent.com/assets/25616317/23322594/5cc43056-faed-11e6-806c-c699a1011cb2.png)
is a error that happens every so often and haven't found anything related to it

**Comment by sant0ro** [comment]
I will give a check.

**Comment by sant0ro** [comment]
This doesn't happens with me.. I can't reproduce this, sorry.
