### ISSUE TITLE
Privacy Setting not updating correctly

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#53]
Hi,

The Privacy Settings (Online Status, Follow Me Setting, Accept Friend Request, etc.) on Chocolatey are not updating to the correct users_settings.

Thanks!

**Comment by sant0ro** [comment]
That's weird.. But Chocolatey doesn't update all users_settings records. I didn't finished to code it totally. Only some things works.

**Comment by s150217754** [comment]
**Not updating users_settings correctly - instead duplicate rows were created**
Instead of updating to the correct row, Chocolatey creates additional rows in **users_settings** every time you save the setting. This resulted in multiple rows under **users_settings** for the same **user_id**.

**Value should be 0 instead of empty (not NULL)**
Furthermore, when un-ticking options (like Online Status, Follow Me Setting, Accept Friend Requests, etc.); Chocolatey leaves the field (e.g. block_following, block_friendrequests, etc.) in **users_settings** as empty (not NULL) when it should be "0".

This "empty field" issue also applies to **chocolatey_users_preferences** table when the Profile settings is updated.

**Suggestions**
When fully coded, fields such as friendCanFollow, friendRequestEnabled, etc. can be removed from **chocolatey_users_preferences** since Chocolatey will reference and update directly to **users_settings** which Arcturus will follow.

**Comment by s150217754** [comment]
## Tables/Fields where Profile Settings should update

**Online Status**
`Unknown`

**Follow Me Settings**
`users_settings > block_following`

**Friend Requests**
`users_settings > block_friendrequests`

**Offline Messaging**
`Unknown - Not sure whether the Offline Messaging refers to in-client or website messaging`

**Comment by sant0ro** [comment]
Follow Me Settings & Friend Requests i think it's already coded.

Will give a double check.

**Comment by sant0ro** [comment]
Okay i will also give a triple check about those duplicating thing and all bugs reported on this Issue.

**Comment by sant0ro** [comment]
If you discover those other settings like "Offline Messaging"

update me.

Fixed all bugs. Commiting soon as possible.

**Comment by s150217754** [comment]
When **Follow Me Settings** and **Friend Requests** is ticked/enabled, **block_following** and **block_following** field in **users_settings** is left empty (see image: http://imgur.com/a/xIFsm).

The field should be "0".

**Comment by sant0ro** [comment]
Fixed, and commiting soon as possible.
