### ISSUE TITLE
NUX Figure don't update

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#55]
Hi,

The chosen Figure in NUX (upon registration) doesn't update to the database's **users > look** field. Instead, the default figure set from chocolatey.php is being used.

Also, can I just confirm that NUX rooms are presently not coded? Anyway to disable the selection of rooms for the time being?

Thanks.

**Comment by sant0ro** [comment]
NUX Rooms aren't coded.

I'm asking to Wesley aka The General code this for me.

**Comment by sant0ro** [comment]
Will give a check about the figure don't being updated.

**Comment by sant0ro** [comment]
Fixed it. Commiting soon as possible.
