### ISSUE TITLE
Room Gallery

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#59]
Hi,

Rooms that are set to Invisible (under Room Settings) should not be shown under Room Gallery (Community > Rooms) since they are only visible to Room Rights holder.

**Comment by s150217754** [comment]
The same goes for Rooms shown under User Profile.

**Comment by sant0ro** [comment]
Ok, will fix this soon as possible.

**Comment by sant0ro** [comment]
Where is the invisible room setting? I didn't found it on rooms table.

**Comment by sant0ro** [comment]
Found it.

**Comment by sant0ro** [comment]
Fixed it. Commiting it.
