### ISSUE TITLE
Ban Profile Page

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#60]
Hello, 

If a user is banned, their Profile Page would be a 404.

**Comment by sant0ro** [comment]
Okay will code this soon as possible.

**Comment by sant0ro** [comment]
Fixed it. Commiting it.

**Comment by s150217754** [comment]
Updated to Commit 4247a76 (Development Branch):

Profile Page of Ban users are still displaying their Avatar and Name. While, Badges, Friend List, Rooms and Groups, are not showing.

The proper way a Profile Page of a Ban user should display would be a full 404 page with the following message:

```
OH BOBBA! PAGE NOT FOUND.

Frank can't find the page you're looking for. Please check the URL or try starting over from the Habbo front page.
```

**Comment by sant0ro** [comment]
Fixed it.
