### ISSUE TITLE
E-mail Suggestions

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#62]
Hi,

For Email:

### Email Subject
Presently, email sent out by Chocolatey does not contain a Email Subject. Most mail client just show it as (No Subject) which may be a turn off. There should be a default Email Header for different kind (i.e. Activation, Password Reset, Change Email, etc.) of emails sent.

Based on Google search, here are some of the Email Subjects used by Habbo:
```
Welcome to Habbo
Email change alert
Email change confirmation
Email change completed
Password reset confirmation
```

### Global From Address
Chocolatey uses the Hotel Name and the Hotel Contact Email defined in **config/chocolatey.php** instead of the Global From Name and Address defined in **config/mail.php**.

The Global From Name and Address should supersede the settings of **config/chocolatey.php** so that Hotel Owners may set a _noreply_ or whatever email Name and Address as they wish instead.

**Comment by sant0ro** [comment]
So you're saying to use "from" from mail.php?

Okay.

Also I will add those subjects.

**Comment by s150217754** [comment]
Yes, use the From Name and Address as defined in **config/mail.php**.

**Comment by sant0ro** [comment]
Coded.
