### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#64]
I have created a reCaptcha key and inserted the public key in chocolatey.php, but when I try to register, reCaptcha it says 'You need to verify that you're not a robot.'

I am using last version.

**Comment by sant0ro** [comment]
@s150217754 are you having this problem too?

**Comment by s150217754** [comment]
@sant0ro Just gave it a try. No problems, able to register and pass recaptcha.

**Comment by Ninktos** [comment]
So, what can i do?

**Comment by s150217754** [comment]
@Ninktos I would suggest:

- Ensure that your reCaptcha Public Key is correct and is defined within:
`    'recaptcha' => 'recaptcha_public_key_here',`
- Clear your Browser Cache and Purge your CDN Cache (if any)
- Provide a screenshot of your Chrome Console Log if possible

**Comment by Ninktos** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/26200747/23589677/bbe9a2d8-01d1-11e7-964b-0cd4b6a98b57.png)

**Comment by Ninktos** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/26200747/23589718/632015e6-01d2-11e7-9cf2-29d51df852e0.png)

**Comment by s150217754** [comment]
@Ninktos And your Lumen Logs in `/storage/logs/lumen.log`

**Comment by Ninktos** [comment]
http://pastebin.com/rwH2QCAe

**Comment by s150217754** [comment]
`[05/03/2017 17:28:06] lumen.ERROR: Swift_TransportException: Could not be established Connection With host localhost [Can not establish a connection because the target machine expressly denied such a connection.`

Seems like Chocolatey cannot access your database which resulted in the error. Check your database configurations and settings (grant access to the server running Chocolatey).

**Comment by Ninktos** [comment]
However, I created a user in database and logged in successfully

**Comment by RetroPiggy** [comment]
Just thought I'd mention, I'm having the same issue with the same errors. All database connections are configured correctly and like Ninktos, creating a user manually still allows me to log in...

**Comment by Ninktos** [comment]
Ok, the problem that i had was because I did not have Free SMTP Server installed. Now it's solver

**Comment by s150217754** [comment]
@Ninktos @RetroPiggy I managed to do some digging and trial and error at my end. Seems like the `Swift_TransportException` is relating to the mail server rather than sql database.

Could you guys try use the `config/mail.php` from the binaries branch and leave it as it is?

**Comment by s150217754** [comment]
@Ninktos Glad you got it sorted out.

**Comment by sant0ro** [comment]
Exactly. I will create a configuration entry to "manually" enable mailing system.

Putting try/catches on the system isn't good.
