### ISSUE TITLE
News loop

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#65]
When there is no news on chocolatey_articles, and you navigate to NEWS section, it do a loop between:
/community/category/all/archive/1 **and** /community/category/all/1

**Comment by s150217754** [comment]
Do you have any rows under **chocolatey_articles**?

**Comment by Ninktos** [comment]
No

**Comment by s150217754** [comment]
That's the reason why there is redirect loop.

**Comment by Ninktos** [comment]
Yes, I opened a issue to know if can avoid this redirect loop.

**Comment by sant0ro** [comment]
This is a HabboWEB bug. Not a Chocolatey bug.

The News system wasn't made to doesn't have any Article.
