### ISSUE TITLE
Account Date of Birth

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#66]
Hi,

Small suggestion:

Since registration actually prompts for the user's Date of Birth (DOB), why not save their DOB into this field:
`users > account_day_of_birth`

This would be useful to render support assistance using DOB as a verification in a large hotel scale.

**Comment by sant0ro** [comment]
Maybe I'll do it later.

But wish will be the purpose of this? Account restrictions?

**Comment by s150217754** [comment]
@sant0ro I understand you might be developing a similar Habbo Help Tool (something like Zendesk) using their template in the future so this addition would be great in the future.

On Habbo, the Support personnel would request the following info as verification to prove you are the legitimate owner of the account:
- Registration IP / Country
- E-mail Address
- Date of Birth

These info (DoB is one of them) can be accessed by the Support personnel when viewing the ticket for verification. Too early to comment/suggest right now on the Help Tool.

**Comment by sant0ro** [comment]
I understand your point @s150217754, but I don't know which Hotel will use Help Center and use ir correctly. xD

But anyways...

**Comment by s150217754** [comment]
Yeah, small low priority addition. No rush man!

**Comment by sant0ro** [comment]
No problem! If I code the whole Help Center, sure I'll add it.

**Comment by s150217754** [comment]
@sant0ro Actually, it would be great to store DoB in future Chocolatey release. Doesn't have to be "help-centre" exclusive feature.

DoB can be used in many occasions such as verifying account ownership via alternative means (i.e. in-game client or on 3rd party forum, etc.)

**Comment by sant0ro** [comment]
Next Release will have it.

**Comment by sant0ro** [comment]
Coded It. Next Release will have it.
