### ISSUE TITLE
NUX Furni Rotation Issue

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#68]
Hi,

Updated to 6914d07. Everything looks fine except the Furni Rotation.

Example:
![rot](https://cloud.githubusercontent.com/assets/25793165/23622910/66d78c50-02db-11e7-8f11-86dbcf3b3008.png)

**Comment by s150217754** [comment]
Room 2 (Pool) looks fine:
![room2](https://cloud.githubusercontent.com/assets/25793165/23623353/b4f5bb7c-02dc-11e7-940c-58170dc91e20.png)


However, Room 3 (Club) needs some adjustment to rotation and floor/wallpaper:
![room3](https://cloud.githubusercontent.com/assets/25793165/23623359/b860ec5a-02dc-11e7-8f2a-42b8d1cd19a9.png)

And my bad, forgotten to provide you with Room 3 floor/wallpaper data.
- Paper_Floor 307
- Paper_Wall 3104

**Comment by s150217754** [comment]
Lastly, please remove Room name's additional `'` at the end.

![nux](https://cloud.githubusercontent.com/assets/25793165/23623502/3b254582-02dd-11e7-931c-34d4667d5ad7.png)

**Comment by sant0ro** [comment]
Fixed. Commiting.

**Comment by s150217754** [comment]
@sant0ro I swear I did copied the right field. Must be my eyes.

Room 3 floor/wallpaper data should be:
- Paper_Floor 409
- Paper_Wall 1902

(I triple checked the data this time round)

Sorry man @sant0ro !

**Comment by sant0ro** [comment]
Fixed it.
