### ISSUE TITLE
Group badges not loading [500 Internal Server Error]

### ISSUE THREAD

**Issue by RetroPiggy** [sant0ro/chocolatey#70]
When viewing a users profile page, the group badges do not load, and the console shows a 500 internal server error on the URL of the badge.

Navigating to the URL of the badge shows this: http://i.imgur.com/8tepJpC.png

**Comment by sant0ro** [comment]
They only will load if you configure correctly Arcturus Group Badges.

Arcturus generates by itself group badges. Please READ Arcturus FAQ.

After configuring it correctly. Please edit or create a new group badge on group settings.

Remembering.: It's recommended configuring Arcturus Badge Imager BEFORE creating ANY GROUP.
