### ISSUE TITLE
Multiple Language Support on NUX

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#72]
Code multiple language support on NUX texts.

Maybe creating a Client for each Language?

**Comment by Anthologique** [comment]
Yes, please.

**Comment by sant0ro** [comment]
Coding in next release.

**Comment by sant0ro** [comment]
@s150217754 is this useful?

**Comment by s150217754** [comment]
To be honest, they can just edit the Loading Text (on config/chocolatey.php) and the habbo-client.blade.php for the NUX text if they'd like to translate.

I would say this should be low priority and not useful at the moment with the number of collaborators and contributors on this project. Maybe next time after clearing backlogs.

**Comment by sant0ro** [comment]
Right, @Anthologique we closing the Issue, but we will code it later.
