### ISSUE TITLE
Translate HabboWEB Pages

### ISSUE THREAD

**Issue by sant0ro** [sant0ro/chocolatey#74]
Translate HabboWEB Pages to most common Languages.

**Comment by Joorren** [comment]
Or put every bit of text in a seperate file so the community can translate it to their own language :D

**Comment by sant0ro** [comment]
@Joorren yeah it's a good idea. But since all HabboWEB Pages are 99% texts. This isn't really necessary. Just create each HabboWEB file for each language xD.

Obviously I will do it.

**Comment by sant0ro** [comment]
Coded it.
