### ISSUE TITLE
Twitter Widget

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#75]
Hi,

The present Twitter Widget will not work for new accounts since Twitter's Widget ID have already phased out last year.

This means that hotels can no longer create Widget IDs and developers would need to rely on the new oEmbed.

More info on: https://twittercommunity.com/t/how-can-i-get-a-twitter-widget-id/68917/18

**Comment by sant0ro** [comment]
Fixed it.

Next commit will have it.

**Comment by s150217754** [comment]
Twitter API implemented since Chocolatey 2.300.
