### ISSUE TITLE
Maintenance Translation

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#76]
Hi,

Maintenance Page at **/resources/views/errors/503.blade.php** should correspond to the translations in **/resources/views/habbo-web-l10n/**.

**To use:**
- MAINTENANCE_HEADER
- MAINTENANCE_CONTENT

**Comment by sant0ro** [comment]
That's weird. Maintenance Page doesn't use HabboWEB Engine.

Remember.: I'm using the old HabboWEB Maintenance Page. Actually Habbo only shows a popup saying that Habbo is under maintenance. (And I hate it) beside that, I created this maintenance page.

**Comment by sant0ro** [comment]
But yes I will code an option for custom texts on Maintenance.

Probably some Espreso thing. Yeah, @Emeto

**Comment by s150217754** [comment]
Ah! Didn't know that the new Maintenance Page is simply a popup! Great decision to bring back the standalone maintenance page!

Anyway, hotel owners can easily modify the text of the maintenance page prior to the release of Espresso. 

Cheers mate

**Comment by sant0ro** [comment]
#offtopic
Ah, I mentioned you on RZ to you give me more feature requests, tips, opinions and other things like that in order to I improved Chocolatey.

But yes, with Chocolatey will be easy. Anyways for now, will add an option to change the text on a config file called maintenance.php

**Comment by s150217754** [comment]
@sant0ro You didn't mention me on RZ 😆 

Anyway, just confirmed that the new maintenance option works flawlessly.
