### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#78]
How can I update correctly.

It shows this in lumes: http://pastebin.com/0mcTq1nY

**Comment by s150217754** [comment]
Hi,

Seems like a missing table called `camera_web`. Based on the emulator's issue tracker, Wesley will be adding support on Arcturus 1.4.0.

@sant0ro can you provide the SQLs for this table as 1.3.0 is missing this table rendering Community Section not being able to load.

**Comment by sant0ro** [comment]
I can provide the table, BUT, It's recommended only using latest Chocolatey version when Arcturus 1.4.0 being released.

SQL:
[code]
CREATE TABLE `camera_web` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `timestamp` INT NOT NULL,
    `url` VARCHAR(128) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    INDEX (`user_id`),
    UNIQUE (`id`)
) ENGINE = INNODB;
[/code]
