### ISSUE TITLE
Apostrophe Symbol in Client Revolving Message

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#85]
Hello,

Client Revolving Message does not properly parse Apostrophe `'` symbol despite having to put a backward slash `\'` infront of it.

**Example:**
```
    'loading' => [
        'Loading Habbo Hotel',
        'See those Yellow Duckies, It\'s Wesley, no?',
        'I would like to eat some chocolate cookies.. You know.',
        'Claudio it\'s you?'
    ],
```

**Will show as:**
![loading](https://cloud.githubusercontent.com/assets/25793165/23887643/28a78550-08be-11e7-9e59-f2a55534f211.png)

**Source Code:**
`"client.starting.revolving": "Loading Habbo Hotel/See those Yellow Duckies, It&#039;s Wesley, no?/I would like to eat some chocolate cookies.. You know./Claudio it&#039;s you?",`

**Reason:**
All forward slash was converted to ALT codes.

**Comment by sant0ro** [comment]
So the solution it's replacing each ' with an "\\'" ?

**Comment by s150217754** [comment]
@sant0ro Or maybe prevent `\'` from being converted to ALT codes?

**Comment by sant0ro** [comment]
Try it again. Commited.

**Comment by s150217754** [comment]
Still the same after updating to the latest commit.

**Comment by s150217754** [comment]
Found out a way to fix the issue. Will be initiating a pull request. @sant0ro
