### ISSUE TITLE
XML Parsing Error

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#87]
http://prntscr.com/ejz8bq
http://prntscr.com/ejz8ld

No show errors in lumen.log

**Comment by s150217754** [comment]
Can you briefly explain what you are trying to do and how did you encounter this message? @Ninktos

**Comment by Ninktos** [comment]
I encounter this message updating figuredata and figuremap

**Comment by s150217754** [comment]
@Ninktos Hi, not sure whether you have resolved this issue. Or else, I would need to know how can I replicate this issue (i.e. what did you do - step by step).

**Comment by s150217754** [comment]
Issue Closed due to no feedback from OP.
