### ISSUE TITLE
Impossible delete picture.

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/chocolatey#89]
Delete picture button dont work.

**Comment by Anthologique** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/6734589/23962202/9effc452-09ad-11e7-8ef1-5a05f5efb78e.png)
When i click on this button, i received a success message, and the picture dont deleted.

**Comment by sant0ro** [comment]
I never saw this button before. Maybe they only appear for the Photo Owners.

Can you follow this procedure and send to me the output?

https://datameer.zendesk.com/hc/en-us/articles/204847860-How-to-Collect-the-Network-HAR-File-Logs-from-a-Developer-Tools-Session

**Comment by Anthologique** [comment]
Just you added a remove line on database (camera_web table) when a user click on this button please.

**Comment by sant0ro** [comment]
@Anthologique I'm waiting you follow those instructions.

**Comment by sant0ro** [comment]
@s150217754 can you try tho replicate this? I need the HAR Output to know how it's the communication.

**Comment by s150217754** [comment]
@sant0ro Unfortunately not, I don't have camera subscription to replicate this page.

**Comment by sant0ro** [comment]
@s150217754 send me a PM no RZ, I'll give mine.

**Comment by s150217754** [comment]
@sant0ro sent.

**Comment by sant0ro** [comment]
Anyways, I Fixed it.
