### ISSUE TITLE
Impossible acces on Housekeeping (espreso).

### ISSUE THREAD

**Issue by Anthologique** [sant0ro/chocolatey#90]
When i click on "Go to espreso housekeeping" button, i have a error.
![1](https://cloud.githubusercontent.com/assets/6734589/23967673/1c11e210-09c0-11e7-8bbd-0102f2bcb8a1.png)
![2](https://cloud.githubusercontent.com/assets/6734589/23967674/1c153fbe-09c0-11e7-881a-824bd856cf44.png)

**Comment by s150217754** [comment]
Espreso Housekeeping is a add-on to Chocolatey and is not released officially yet. 

With that said, Chocolatey does not ship Espreso together and you have to download it separately when it gets released.

**Comment by s150217754** [comment]
He's probably missing the **/resources/views/errors/espreso.blade.php** file or his .htaccess is preventing it from showing.

**Comment by sant0ro** [comment]
@s150217754 you confirm that in your installation the espreso.blade.php shows up?

**Comment by s150217754** [comment]
Yes @sant0ro just confirmed and it is showing the Espreso not installed page

**Comment by s150217754** [comment]
Issue Closed due to no feedback from OP.

**Comment by sant0ro** [comment]
@s150217754 that's weird. I will give a check.

Reopening, it's a bug.

**Comment by sant0ro** [comment]
Fixed it.

**Comment by s150217754** [comment]
Kind of odd that it is displaying well for me 😂

**Comment by sant0ro** [comment]
Yeah, the real bugs were about URIs.

But it need to display.
