### ISSUE TITLE
ErrorException in Facade.php

### ISSUE THREAD

**Issue by iHxFall** [sant0ro/chocolatey#91]
When I try to open my hotel,it gives this error:
http://i.imgur.com/03p4mC0.png

Give the same error when I use _php artisan migrate_ on the CMD

http://i.imgur.com/YzgLwkU.png

I use Xampp Control Panel v3.2.1

**Comment by s150217754** [comment]
Hi,

Please ensure that you use this version of XAMPP: 7.1.1 / PHP 7.1.1.

Also, run `php artisan migrate ` this way via Command Prompt in your htdocs directory:
`c:/xampp/php/php.exe artisan migrate`

**Comment by sant0ro** [comment]
Hi @iHxFall this hapens because you don't have the correct version of php.

Need be php 7.0 or higher.
