### ISSUE TITLE
Client new user

### ISSUE THREAD

**Issue by Ninktos** [sant0ro/chocolatey#92]
When someone register and go to hotel's page to choose their nickname, the web does not load.

http://prntscr.com/ekikxg

I'm using apache from IIS and mysql from Xampp. It does not happens when I use Xampp.

No lumen.log logged

**Comment by sant0ro** [comment]
Can you show me the "Response" tab of this?

**Comment by Ninktos** [comment]
http://prntscr.com/ekow6v

**Comment by sant0ro** [comment]
That's really weird.

**Comment by s150217754** [comment]
@Ninktos By any chance there is any error_logs or something?

**Comment by s150217754** [comment]
Issue Closed due to no feedback from OP.
