### ISSUE TITLE
Chocolatey not working on IIS

### ISSUE THREAD

**Issue by xInuyasha** [sant0ro/chocolatey#94]
I don't know why, but my Website is not shown, using PHP 7+.
Also where can i change the Language for website into german?
Thanks for help! :)

**Comment by s150217754** [comment]
Hi, you can change the language via *config/chocolatey.php*.

Change *page_language* from *en* to *de*.

**Comment by xInuyasha** [comment]
Thanks, do you also know something about the IIS Problem?

**Comment by s150217754** [comment]
Unfortunately I don't get your question on the IIS. 

You will need to provide more info and upload your **Chrome Console Log** and **lumen.log**.

I will try to help to the best of my ability as I don't use IIS.

**Comment by xInuyasha** [comment]
Nothing in the Console Log and the lumen.log is empty. :/

**Comment by sant0ro** [comment]
@xInuyasha what exactly happens on the browser? Appears something? Blank Screen?

Are you using PHP 7 on IIS?

Have you configured database?

Are you using the `binaries´ ?

**Comment by xInuyasha** [comment]
Die Seite habboe.eu funktioniert nicht

habboe.eu kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

on Browser, i'm using PHP 7.1.1 on IIS, config is done and i'm using the chocolatey-2.305 version.

**Comment by sant0ro** [comment]
Yes, but a little question.

Does you download this: https://github.com/sant0ro/chocolatey/releases/tag/2.305 ?

Also did you configured the ".env" file and executed "php artisan migrate" on your console?

**Comment by xInuyasha** [comment]
Yes, i did everything. The lumen log doesn't show anything.

**Comment by sant0ro** [comment]
I really don't know what it can be.

I'm really sorry.

**Comment by xInuyasha** [comment]
It's ok, hope it works in the future releases :) Anyway thanks for help.

**Comment by sant0ro** [comment]
Will be hard to confirm this. Because I really don't know what happened.

I'm running IIS, and it's working really nice. Why isn't seem to working with you? I don't know.

Closing Issue. I'm really sorry for not solving it.
