### ISSUE TITLE
No Owner for NUX Furni

### ISSUE THREAD

**Issue by s150217754** [sant0ro/chocolatey#95]
Hi,

Furnis from NUX Room should have their Owner_ID assigned.

**Comment by sant0ro** [comment]
Owner ID, Isn't being assigned?

**Comment by s150217754** [comment]
Yep @sant0ro . It's inserted to the "items" table where owner_id = "0".

**Comment by sant0ro** [comment]
Fixed it.

**Comment by s150217754** [comment]
@sant0ro Updated to latest commit. NUX Items is not inserted into the items table.

**Comment by s150217754** [comment]
@sant0ro Fixed in Pull Request #97
